### ISSUE TITLE
Support couchbase collections and scopes

### ISSUE THREAD

**Issue by jorgerod** [lukas-krecan/ShedLock#1006]
Couchbase has added support to [collections and scopes.](https://docs.couchbase.com/server/current/learn/data/scopes-and-collections.html)

**Describe the solution you'd like**
Currently, the couchbase provider only allows to use the default-collection but neither the collection nor the scope.

https://github.com/lukas-krecan/ShedLock/blob/51e6c89cbd790fb6eacc58ce23bb53bb63403e3d/providers/couchbase/shedlock-provider-couchbase-javaclient3/src/main/java/net/javacrumbs/shedlock/provider/couchbase/javaclient3/CouchbaseLockProvider.java#L98

In my opinion, it would be very useful to add this functionality (maybe you should also upgrade the version of the couchbase sdk you are using).

How do you see it?

**Comment by lukas-krecan** [comment]
Hi, makes sense. Can you please provide a pull-request? If the new couchbase sdk is not backward compatible, please create a new module.
