### ISSUE TITLE
Hazelcast provider does not recover when the grid goes down and then recovers

### ISSUE THREAD

**Issue by spartanhooah** [lukas-krecan/ShedLock#1020]
**Describe the bug**
1. shedlock-spring 4.33.0
2. shedlock-provider-hazelcast4:4.33.0
3. ShedLock configuration
```
@Log4j2
@Configuration
@EnableScheduling
@EnableSchedulerLock(defaultLockAtMostFor = "10m")
public class ShedLockConfiguration {
    @Bean
    public HazelcastLockProvider lockProvider() {
        return new HazelcastLockProvider(
                // This is a class from our infrastructure team
                HazelcastClientConnector.getConnection(), "ConditionalReprocess");
    }
}
```
4. ShedLock logs
We don't currently have debug logging enabled in our production environment, but here is the stack trace we're seeing:
```
com.hazelcast.client.HazelcastClientNotActiveException: Client is not active.
	at com.hazelcast.client.impl.clientside.HazelcastClientProxy.getClient(HazelcastClientProxy.java:303)
	at com.hazelcast.client.impl.clientside.HazelcastClientProxy.getMap(HazelcastClientProxy.java:126)
	at net.javacrumbs.shedlock.provider.hazelcast4.HazelcastLockProvider.getStore(HazelcastLockProvider.java:150)
	at net.javacrumbs.shedlock.provider.hazelcast4.HazelcastLockProvider.lock(HazelcastLockProvider.java:110)
```

**Expected behavior**
When the Hazelcast grid is unavailable for some time, the application using Shedlock should be able to gracefully recover once the grid is back up.

**Actual behavior**
The application is not able to recover, and any time ShedLock attempts to interact with Hazelcast through the provider, it throws an exception.

**Comment by lukas-krecan** [comment]
Hi, sorry for late response. I would assume it's Hazelcast issue not a ShedLock issue. https://stackoverflow.com/questions/48055121/how-to-reconnect-a-hazelcastclient-to-hazelcastserver-after-server-restart
