### ISSUE TITLE
Unable to pass database name for the Shedlock-neo4j-provider

### ISSUE THREAD

**Issue by SergeyPlatonov** [lukas-krecan/ShedLock#1025]
1. shedlock-spring:4.33.0
2. shedlock-provider-neo4j:4.33.0 (same result with newest provider version)
3. ShedLock configuration

```java
@Bean
Neo4jLockProvider lockProvider(Driver driver) {
    return new Neo4jLockProvider(driver);
}
```

4. Shedlock-neo4j-provider works only with default database.
No way to pass the database name for this provider.

Implementation for getting Session in Neo4jStorageAccessor looks like:
```java
Session session = driver.session();
```

I propose to add an additional parameter to the constructor (databaseName)
```java
    public Neo4jStorageAccessor(@NonNull Driver driver, @NonNull String collectionName, @Nullable String databaseName) {
        this.collectionName = requireNonNull(collectionName, "collectioneName can not be null");
        this.driver = requireNonNull(driver, "driver can not be null");
        this.databaseName = databaseName;
        createLockNameUniqueConstraint(driver);
    }
```
and move to a separate method getting the session depending on the database name,
for example
```java
private Session getSession(Driver driver) {
        return StringUtils.isNotBlank(databaseName)
                ? driver.session(SessionConfig.forDatabase(databaseName))
                : driver.session();
}
```
**Expected behavior**
The provider can work with any database, and the database name can be specified to work with a non-default database.

**Actual behavior**
The provider works only with the default database and no other database can be provided.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Can you please provide a pull-request? Thanks
