### ISSUE TITLE
Locks are not locking as expected

### ISSUE THREAD

**Issue by henri-tremblay** [lukas-krecan/ShedLock#103]
It looks like a big bug in the code.

If I do the following code:

```java
        LockConfiguration configuration = new LockConfiguration("test", Instant.MAX);
        Optional<SimpleLock> lock = provider.lock(configuration);
        assertThat(lock).isPresent();

        provider.clearCache();

        try {
            Optional<SimpleLock> lockAgain = provider.lock(configuration);
            showDB();
            assertThat(lockAgain).isPresent();
        }
        finally {
            lock.get().unlock();
        }
```

It will perfectly work and make you will like two locks were taken. Note that I clear the cache in between. It simulates two different servers taking the lock.

However, there is a `DataIntegrityViolationException` under the hood. But it's ignored.

If I look at the code from `StorageBasedLockProvider`:

```java
protected boolean doLock(LockConfiguration lockConfiguration) {
        String name = lockConfiguration.getName();

        if (!lockRecordRegistry.lockRecordRecentlyCreated(name)) { // false
            // create document in case it does not exist yet
            if (storageAccessor.insertRecord(lockConfiguration)) { // false
                lockRecordRegistry.addLockRecord(name);
                return true;
            }
            lockRecordRegistry.addLockRecord(name); // but still put it in cache
        }

        return storageAccessor.updateRecord(lockConfiguration); // and then update which will perfectly work
    }
```
I've added comments to see how it goes. I'm pretty sure the code should be:

```java
protected boolean doLock(LockConfiguration lockConfiguration) {
        String name = lockConfiguration.getName();

        if (!lockRecordRegistry.lockRecordRecentlyCreated(name)) {
            // create document in case it does not exist yet
            if (storageAccessor.insertRecord(lockConfiguration)) {
                lockRecordRegistry.addLockRecord(name);
                return true;
            }
            return false;
        }

        return storageAccessor.updateRecord(lockConfiguration); 
    }
```

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I have replicated your test and it's working as expected https://github.com/lukas-krecan/ShedLock/commit/d6e1f13cf57542b0c3373f57435fbfe679ebe6eb#diff-2778f8a38de61a6ed46d65809917ab06R27. I suspect you are using incorrectly implemented StorageAccessor. If valid lock record exists, StorageAccessor.updateRecord has to return false end everything should work as expected. I have added documentation, so it should be more clear now. Moreover, if you want to simulate multiple servers, it makes more sense to create multiple lock providers.

**Comment by henri-tremblay** [comment]
Interesting. Let me see why I get different results.

**Comment by henri-tremblay** [comment]
That is surprising. I did a little project reproducing the issue. See [here](https://github.com/henri-tremblay/shedlock-test)/.

**Comment by henri-tremblay** [comment]
Ok. Got it. It's `Instant.MAX` that breaks everything. I don't know if it's because of the timestamp database precision or the conversion to timestamp but it must be one or the other. And it overflows which make the update works.

**Comment by lukas-krecan** [comment]
Cool
