### ISSUE TITLE
RedisLockProvider set lock key with ttl -1

### ISSUE THREAD

**Issue by lon-wolf** [lukas-krecan/ShedLock#105]
I am using version 0.18.2. Using RedisLockProvider for same.
Came to know that sometimes it make lock keys with TTL -1 that leads to permanent blockage of schedulers. And I also provided lockAtMostFor parameter. 

Should I upgrade to different version. If yes, please specify stable one.

**Comment by lon-wolf** [comment]
I can't change for some reason, is any other way around?

**Comment by lukas-krecan** [comment]
If you are using Jedis you can use this https://github.com/lukas-krecan/ShedLock#redis-using-jedis, otherwise no, spring-data-redis v1 does not have method we need for atomic locking

**Comment by frazer-jin** [comment]
yes, I encounter the same issue, but not figure out in which case it happened... waiting for the advise.

**Comment by rygh4775** [comment]
hi, @lukas-krecan 

I found a way to fix this issue.
https://github.com/rygh4775/ShedLock/pull/1/files

I know you don't support old version 0.18.x. But, I want to share my solution.
