### ISSUE TITLE
How to set schema dynamically to lockprovider

### ISSUE THREAD

**Issue by ddinde-mdsol** [lukas-krecan/ShedLock#1100]
Hello guys,

I am trying to implement scheduler for multi node cluster. I have configured shedlock using jdbcTemplate approach. https://github.com/lukas-krecan/ShedLock#jdbctemplate 

Scenario :
I have multiple schemas, all tables are identical inside each schemas. I want to update Table A from each schema. I have schema traversing logic in @scheduled method.

Question: Do I need to have shedlock table in each schema? If yes, how can I provide a schema to lockProvider dynamically?

Thank you for help. :)

**Comment by lukas-krecan** [comment]
Hi, the solution with one table would require having a different lock name for each lock. If it's not possible, you can choose schema dynamically like [this](https://github.com/lukas-krecan/ShedLock#Multi-tenancy).
