### ISSUE TITLE
@SchedulerLock does not seem to work with Spring Boot 2.1.1

### ISSUE THREAD

**Issue by tran302** [lukas-krecan/ShedLock#111]
I have upgraded my Spring Boot application from 2.0.6 to 2.1.1 and @SchedulerLock does not work on 1.1.0.
I have tried upgrading ShedLock to 2.1.0 but still no luck.
Could you please help?

**Comment by tran302** [comment]
It seems I didn't need @EnableSchedulerLock before, and resolved by including it.

**Comment by lukas-krecan** [comment]
`@EnableSchedulerLock` has been introduced in 2.0.0 together with simplified configuration. I am glad it helped.
