### ISSUE TITLE
JDBC reports duplicate entry for ShedLock scheduler name

### ISSUE THREAD

**Issue by rmvc-mirza** [lukas-krecan/ShedLock#1123]
**Describe the bug**
1. shedlock-spring 4.39.0
2. shedlock-provider-jdbc-template
3. ShedLock configuration
```
@Configuration
@EnableScheduling
@EnableSchedulerLock(defaultLockAtMostFor = "PT30S")
public class SchedulerConfiguration {
  @Bean
  public LockProvider lockProvider(DataSource dataSource) {
    return new JdbcTemplateLockProvider(dataSource);
  }
}
```
4. ShedLock logs
` WARN 23500 --- [   scheduling-1] o.m.jdbc.message.server.ErrorPacket      : Error: 1062-23000: Duplicate entry 'scheduler_name' for key 'PRIMARY'`

**Expected behavior**
While starting the application there shouldn't be a warning about a duplicate entry for the scheduler name 

**Actual behavior**
I get this warning about the duplicate entries for every scheduler that has a lock on it, There aren't duplicate scheduler names, and we've noticed this behavior change after updating from 4.23.0 to 4.39.0

EDIT : After some additional testing I've figured out that the issue is connected to the mariadb-java-client when it is updated to any 3.x.x version including 3.0.0-alpha

**Comment by lukas-krecan** [comment]
Hi, this is expected behavior. We need to get the lock in an atomic way. When ShedLock starts, it tries to insert a row, it usually fails as the row alrrady exists. ShedLock then stores the info to a cache and tries to update the row.

I actually checked the code, and I can add IGNORE modifier to hide the error https://dev.mysql.com/doc/refman/5.7/en/insert.html

**Comment by lukas-krecan** [comment]
Actually, IGNORE ignores more errors, introducing it might have unintended consequences.

**Comment by derTobsch** [comment]
We upgraded to Spring Boot 2.7.x with a `mariadb-java-client` 3.0.x and now we get this warnings in our log. This feels not good, because it says "WARNING: everything is ok" :) 

So if there would be any solution to get rid of these warnings, that would be great. Please let us know.

**Comment by lukas-krecan** [comment]
If you are able to upgrade to ShedLock 5.0.1 and you are `usingDbTime()`, the warning should go away.

**Comment by derTobsch** [comment]
Can you give me a hint with the `usingDbTime()` or a hint to the documentation? That would be nice. Btw thanks for library! We really appreciate your work!

**Comment by derTobsch** [comment]
https://github.com/lukas-krecan/ShedLock#jdbctemplate :)
