### ISSUE TITLE
Stale DB Lock Entry - DB Entry Not Updated Upon Next Run

### ISSUE THREAD

**Issue by glakshmeepathi** [lukas-krecan/ShedLock#1126]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

Update to the latest version.

**Describe the bug**
1. Which version do you use

```
shedlock-provider-mongo-4.39.0
shedlock-spring-4.39.0
shedlock-core-4.39.0
mongodb-driver-core-4.2.3
mongodb-driver-sync-4.2.3
spring-boot-data-mongodb-3.2.1
spring-boot-starter-data-mongodb-2.5.0
```

`Mongo DB 4.4.11`

2. Which Lock Provider
`MongoLockProvider`

3. ShedLock configuration
```
@Scheduled(fixedRate = 60 * 60 * 1000, initialDelay = 30000)
@SchedulerLock(name = "ArcLock", 
lockAtLeastForString="#{@configService.getProp(T(com.Constants).LOCK_ATLEAST) ?: 'PT50M'}"
lockAtMostForString="#{@configService.getProp(T(com.Constants).LOCK_ATMOST) ?: 'PT55M'}"
)
```

`@SchedulerLock` - shed.core deprecated package

**Expected behavior**
4) DB Lock Entry should NOT be inserted as the run does not correspond to `@Scheduled`
5) This run should NOT have happened as there was a lock entry
8) DB Lock Entry should have been updated by Instance 1 from second run.

**Actual behavior**

1) Method - `loadEveryHour()`. This method is annotated with `@Scheduled` and `@SchedulerLock`. It is also called by `@EventListener(ApplicationReadyEvent.class)` at application start up
2) I cleared all DB Lock entries
3) Start Instance 1
4) DB Lock Entry inserted at the time of application startup and this method is run
(Is this correct ? As this run does not correspond to the `@Scheduled`)
5) ~10 seconds later, this same method is run again by `@Scheduled`
(Is this correct ? Since a lock entry is made in the previous step, scheduler should not have run)
6) Start Instance 2 ~20 min later
7) This method is run at the time of application startup of Instance 2 once. It is not run by `@Scheduled` -
It is expected as it is locked by Instance 1.
8) After 1 hour (fixedRate), Instance 1's scheduler is run again but this time DB Lock Entry is not updated.
9) After 1 hour (fixedDate), Instance 2's scheduler is run again as DB Lock Entry was not updated by Instance 1 which had the old (previous run) time. So now 2 instances are running the same code.

**Other Observations :**

There are 10 other schedulers and schedulerlock which isn't called at application startup. When 2 instances are started/deployed at almost the same, sometimes one/some of these other schedulers's entry is not made by the first instance that started.

Both of the above does not seem to happen with `mongo-java-driver-3.12.8` `shedlock-provider-mongo-3.0.0` `mongodb-driver-3.12.8` `mongodb-driver-core-3.12.8`

**Comment by lukas-krecan** [comment]
Hi, thanks for exhaustive report. I am unfortunatelly not able to follow the scenario. So just a few notes
1. ShedLock v4 switched to [AOP](https://github.com/lukas-krecan/ShedLock#modes-of-spring-integration) by default whcih means that the lock is applied even if the method is called normally and not by a scheduler. if you do not want the lock to be applied, either switch the interceptMode or use a different method for scheuler and different one for the EventListener
2. What time is returned by "#{@configService.getProp(T(com.Constants).LOCK_ATLEAST)" ?

**Comment by glakshmeepathi** [comment]
Thanks for the reply Lukas. I tried to elaborate as much as possible and bear with some repititions.

Step (4)(Instance 1) was not so much an issue. I was just wondering why a lock entry was made when a method is called at application startup. (jfyi, calling this method at application startup is unnecessary as this method is going to be called by the @Scheduled almost immediately after startup but that is how it is)
`ArcLock lockedAt=14:00:00, lockUntil=14:50:00`

`configService` returns the same - `PT50M `and `PT55M` for atleast and atmost.

Step (5) (Instance 1) is an issue - `"ArcLock"` entry was made at Step (4) for 50Min during application startup. In this step (that is Step (5)), scheduler for the same method `loadEveryHour` which is annotated with `@Scheduled ArcLock` kicks in few seconds after Step (4). Expectation here is, since there is already a lock for ArcLock for 50Min, this method should not be executed. But it was executed ignoring the lock ! (It could have honored the existing lock or replaced the lock with its own timings although honoring the lock is what is expected. But neither happened !)
`Method Entry Logger Time - 14:00:15` which means the method is run again (due to `@Scheduled`) 15sec after lock entry is made in Step (4) and when the lock is still in force until `14:50:00` !

Step (6), Step (7) - Instance 2 starts at `14:30:00`. Runs the method `loadEveryHour` at application startup. Instance 2's `loadEveryHour` (due to @scheduled) did not run honoring the lock (lock is until 14:50:00) which is expected and correct.

Step (8) is an issue - When Instance 1's scheduler's turn comes again at `15:00:15`, it should replace/update the ArcLock with `lockedAt=15:00:15, lockUntil=15:50:15` but that did not happen ! Entry still remains at `ArcLock lockedAt=14:00:00, lockUntil=14:50:00`.

Step (9) is an issue - When Instance 2s' scheduler's turn comes again at `15:30:00`, it also did not update the lock entry.

So none of the instances are checking and/or updating the lock entry and so effectively there is no lock and 2 instances are running at the same time (i.e time overlap is there).

**Comment by lukas-krecan** [comment]
Hi, I really do not have capacity to dive into the report. I can recommend only:
1. Switch-on the [debug log](https://github.com/lukas-krecan/ShedLock#troubleshooting) and see what it says.
2. You can use [Lock assert](https://github.com/lukas-krecan/ShedLock#lock-assert) to ensure that the infrastructure is working as expected
3. I recommend to check if the clocks on both machines are approximatelly in sync.

**Comment by glakshmeepathi** [comment]
Please ignore the above report as it includes many other observations/factors as well.

The actual issue is, shedlock not locking (not inserting a lock entry in DB) when the method that is annotated with @Scheduled is in a class that implements an interface

**Comment by lukas-krecan** [comment]
In this case, please read some article about how Spring AOP works
