### ISSUE TITLE
Set lock_until of current lock to certain time

### ISSUE THREAD

**Issue by defia** [lukas-krecan/ShedLock#1132]
Hi Lukas,

I see there is a extend feature to manually extend the lock, but what we could do with the function is only to extend the lock for a certain period.

But in a case, for example, we want to extend to a certain time, 

```
for int i=0;i<1000;i++{
    //here we want to set the lock_until of current lock to current time +  1 minute, in order to prevent the lock is released before the loop is finished.
    //update table set current_lock = now()+ 1min where lock=current_lock

    //do some job
    ....
    // job finished, cost unknown time


}
```

Are there any existing ways to do this? Or do we have to manually update the database?

**Comment by lukas-krecan** [comment]
Hi, I do not understand the question. If you know the current time and the "certain time", you can get the period by subtracting the times, or not?
