### ISSUE TITLE
jackson-datatype-jsr310 dependency

### ISSUE THREAD

**Issue by gphilos** [lukas-krecan/ShedLock#1152]
Hello,

While looking at the required dependencies of shedlock-core i came across the dependency to jackson, which doesn't seem necessary to  shedlock-core. Please correct me if i am wrong.

https://github.com/lukas-krecan/ShedLock/blob/b602e990bcf2e97af163b98d1c097843a4d385f7/shedlock-core/pom.xml#L39

**Comment by lukas-krecan** [comment]
Thanks, you are right
