### ISSUE TITLE
Just want know if you've contacted Spring officials to adopt ShedLock?

### ISSUE THREAD

**Issue by acxlam** [lukas-krecan/ShedLock#117]
I believe this is an import piece missing. If yes, what's their answer? 

Tks for the great work.

**Comment by lukas-krecan** [comment]
Hi, thanks. I have not contacted them, it never occurred to me. What do you think would be the biggest advantage if it were adopted?

**Comment by acxlam** [comment]
@lukas-krecan Then developers would stop fussing with Quatz job store , or different profiles, or their own solutions if all they need is just a mutex for their tasks. 

I believe multi provider design, non intrution fits well with Spring paradigm. Besides, introdution to your work is ubiquitous in major java sites as well.  eg. https://www.baeldung.com/shedlock-spring. 

If I were new to Spring and someone told me that shedlock comes as part of Spring, I would have believed it.  Just my 2 cents.  Please feel free to close the ticket.

**Comment by MusikPolice** [comment]
FWIW, I concur - I've done a lot of work with Quartz in the past, and this project blows it out of the water for simple use cases. The combination of `@Scheduled` and `@SchedulerLock` is really powerful for microservices that need to trigger an idempotent cleanup or monitoring task on a regular basis, but don't want to waste resources or risk race conditions by running multiple instances of the task concurrently.

**Comment by benoit-campeau** [comment]
Your library do exactly what we need in our use case.  I have worked and looked at Quartz and it is far too complex/complete for what we really need!  We used Spring @Schedule because it was easy and straightforward to use.  Now i have to provide my tech leads and architects some arguments  (sustainability, stability) about this open-source lib.  Something i would not need to do if it was part or adopted or ref. by Spring.  Good job btw ;-)

**Comment by gerasimovv88** [comment]
**+1** to include **ShedLock** to **Spring** internals

**Comment by techmachin3** [comment]
+1 to include ShedLock to Spring internals

**Comment by kunjalshah** [comment]
I agree on the usefulness and simplicity of this library. If it had been part of Spring framework it would lend more credibility

**Comment by hades89** [comment]
agreed, at first glance i thought it was from Spring Framework itself.
