### ISSUE TITLE
Datasource missing in TestNG/H2

### ISSUE THREAD

**Issue by acxlam** [lukas-krecan/ShedLock#118]
We are using Shedlock 2.2 JDBCTemplate lock provider along with Spring boot 2/ testNG. It works fine in non test profiles with Mysql.

However when the QA collegue start testing with TestNG/embedded H2, the autowired DataSource used in our original testNG test to create tables before test becomes null.  The log doesn't show anything meaningful. But with @EnableSchedulerLock commented and it works again.  Strangely, debugging shows that JDBCTemplate receives the data source just fine.

I am not very good with Spring boot auto configuration details. So any clues how would the test datasource be affected? 

I will get the code later.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I have never seen this happening and I can not imagine any reason why the DataSource might be null.

**Comment by acxlam** [comment]
Greetings, would you be nice as to have a check at the following code snippet? Mybatis is being used for ORM so there is a MapperScan annotation, The other annotations belong to Spring or TestNG. The DataSource in AbstractOspGovTestCase  becomes null if EnableSchedulerLock is active.

Please feel free to close the case if no clue at a glance.



````java
@SpringBootTest(classes = {ServiceCenterApplication.class},
        webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@ActiveProfiles("test")
@WithCustomUserDetails
@TestExecutionListeners(listeners = {WithSecurityContextTestExecutionListener.class,
        /*ReactorContextTestExecutionListener.class*/})
public class AbstractOspGovTestCase extends AbstractTestNGSpringContextTests {

    protected MockMvc mockMvc;

    @Autowired
    private WebApplicationContext wac;

    @Autowired
    protected DataSource dataSource;

    @BeforeClass(alwaysRun = true)
    public void initDb() throws IOException, SQLException {
        LOGGER.info("Before executing SqlPreScript for class...");
        SqlPreScript sqlScript = this.getClass().getAnnotation(SqlPreScript.class);
        if (sqlScript != null) {
            runSqlScript(sqlScript.value());
        }
        domainService.updateDomainMemoryFromDB();
    }

    public void runSqlScript(String... sqlPaths) throws SQLException, IOException {
        Connection connection = dataSource.getConnection();
        ScriptRunner runner = new ScriptRunner(connection);
        runner.setEscapeProcessing(false);
        runner.setAutoCommit(false);
        runner.setSendFullScript(false);
        for (int i = 0; i < sqlPaths.length; i++) {
            logger.info("init database data, sql path : " + sqlPaths[i]);
            runner.runScript(Resources.getResourceAsReader(sqlPaths[i]));
        }
        connection.close();
    }
}
````

````
@SpringBootApplication
@EnableScheduling
@EnableSchedulerLock(defaultLockAtMostFor = "PT15M")
@MapperScan({"com.vipshop.osp.repository")
@ComponentScan(basePackages = {"com.vipshop.servicecenter")
public class ServiceCenterApplication {

	public static void main(String[] args) {
		SpringApplication.run(ServiceCenterApplication.class, args);
	}
}

````

**Comment by lukas-krecan** [comment]
Hi, sorry, but I really can not imagine how it could be possible. You can try to switch Spring DEBUG logging on and check if there is anything interesting.

**Comment by bertocast** [comment]
Hi,

I'm facing this problem right now with an embedded H2 database. If EnableSchedulerLock is enabled, some tests begin to fail due to a null DataSource.

Any clue on this?

**Comment by lukas-krecan** [comment]
Can you please provide a simple example?

**Comment by bertocast** [comment]
Sorry, I think I might found the real problem.

With my @Service annotated with @EnableSchedulerLock, my data.sql file is not loaded at the startup anymore. If I comment the annotation, my data is loaded as expected.

**Comment by acxlam** [comment]
@bertocast  may I ask where you place the EnableSchedulerLock annotation at last? As you can see, I put it along with the SpringBootApplication annotation and I face this problem.

**Comment by lukas-krecan** [comment]
Hi, I tried to reproduce it, but everything works as expected. Can you please try to break the test here?

https://github.com/lukas-krecan/ShedLock/pull/119/files

**Comment by acxlam** [comment]
@lukas-krecan Followed your test and it turns out our own problem. Colleagues recently added some @PostConstruct where they load cache from DB. However, the order between these init methods and "spring.datasource.schema" seems non-deterministic. Adding @EnableSchedulerLock happens to change the order.

I replace PostConstruct with ApplicationListener and no more problems. Regret to have taken your precious time and many thanks.
