### ISSUE TITLE
MongoClient is legacy. Support MongoClients.create()

### ISSUE THREAD

**Issue by bjornharvold** [lukas-krecan/ShedLock#120]
This would be VERY helpful. Having to create a separate instance of legacy MongoClient just for ShedLock.

**Comment by bjornharvold** [comment]
An extra ctor with com.mongodb.client.MongoClient support would be great

**Comment by lukas-krecan** [comment]
Sorry, I do not understand. Why is MongoClient legacy? What kind of constructor do you have in mind? Could you please provide an example?

**Comment by bjornharvold** [comment]
Since Java Mongo driver v3.8.x, 

`new com.mongodb.MongoClient()` 

is legacy. 

`com.mongodb.client.MongoClient = MongoClients.create()`

Is the new MongoClient in town.

**Comment by lukas-krecan** [comment]
Ah, I see, what a mess

**Comment by lukas-krecan** [comment]
Would this be sufficient? https://github.com/lukas-krecan/ShedLock/commit/8ccf4ee8106c34faa204d75d16011d5ae458f163 I am hesitant to depend on com.mongodb.client.MongoClient, I am not sure what it would do for people still using 3.6 driver

**Comment by bjornharvold** [comment]
That could work. Spring Data MongoDB supports both. Maybe see how they set it up.

**Comment by lukas-krecan** [comment]
Released as 2.2.1, currently I do not have time to test and research more comfortable solution.
