### ISSUE TITLE
ShedLock without @Scheduled annotation on Azure

### ISSUE THREAD

**Issue by Alois-Komenda** [lukas-krecan/ShedLock#1205]
Hi,

we implemented dynamic scheduling for our Spring Boot application, i.e. we don't use the @Scheduled annotation any longer.
We found the hint to register a LockableTaskScheduler to ScheduledTaskRegistrar in an issue (https://github.com/lukas-krecan/ShedLock/issues/245).

Everything worked fine ... until we deployed it in an Azure environment. (ShedLock was by-passed completely.)
After some analysis and research we found the hint that the PROXY_SCHEDULER approach does not work with libraries that Azure uses (e.g. opentelemetry). I guess, this also is the case when registering a custom scheduler with ScheduledTaskRegistrar.

Now we are creating a LockableRunnable to wrap our Runnable. This is then passed to ScheduledTaskRegistrar.addTriggerTask.
Seems to work fine with Azure on first glance!

Is this the same what happens in PROXY_METHOD mode?
Are there any drawbacks/caveats to this approach?

Best regards,

Alois Komenda

**Comment by lukas-krecan** [comment]
Hi, sorry, I do not understand what you are asking me. PROXY_METHOD uses Spring AOP to wrap the annotated method, it should IMO work in Azure.

**Comment by Alois-Komenda** [comment]
Hi, thanks for your answer.
It boils down to this question: How would you implement PROXY_METHOD mode without the @Scheduled  and @SchedulerLock annotations? (We don't use the annotations any more because we implemented our own dynamically configurable scheduling.)

**Comment by lukas-krecan** [comment]
`@SchedulerLock` annotation can be used without a scheduler. It just wraps the method in a locking mechanism
