### ISSUE TITLE
ShedLock gracefully shutdown

### ISSUE THREAD

**Issue by zdary** [lukas-krecan/ShedLock#1213]
**Is your feature request related to a problem? Please describe.**
We use multiple JVM's to run our project. When we deploy on AWS we spin up a new instance, change load balancer to the new JVM and then we destroy the old JVM.
We'd like to do this process gracefully which involves
* do not lock any more scheduled jobs once load balancer reports this JVM is no longer participating in traffic and will be shut down
* report back if any jobs are still running on this JVM. i.e. is it safe to start the shutdown.

**Describe the solution you'd like**
The first part was quire easy, extending the LockProvider.
```
    @Override
    @NonNull
    public Optional<SimpleLock> lock(@NonNull LockConfiguration lockConfiguration) {
        if (isDisposed) {
            return Optional.empty();
        }
        return super.lock(lockConfiguration);
    }
```

I'm not sure how to implement the second point `public boolean isAnyLockActive()`

**Describe alternatives you've considered**
For now we put a long enough time to let the old JVM live before we initiate shutdown.

**Comment by lukas-krecan** [comment]
Hi, two ways came to my mind:
1. If you are using Spring scheduling infrastructure, it might be possible to find it in the `ScheduledExecutorService` or its implementation. (I have not checked if it's possible)
2. You can query the underlying LockProvider store. For example, if you are using JDBC, you can query the shedlock table

**Comment by lukas-krecan** [comment]
Actually, there is a better solution, you can keep track of the locks your extended LockProvider. (Btw. I think that wrapping the LockProvider is cleaner than extending it.)
