### ISSUE TITLE
Whether to consider adding capability to wait to acquire lock 

### ISSUE THREAD

**Issue by Yannis-01** [lukas-krecan/ShedLock#1223]
now, if cant get lock , will do nothing. whether to consider adding capability to wait lock

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. The best way you can do it is to wrap `LockProvider` and do it yourself. You can create your own implementation of `LockProvider`, wrap the original one and if its `lock` method returns an empty Optional, you can sleep for a while and try again.

**Comment by KSH-code** [comment]
:+1:

**Comment by TheBestPessimist** [comment]
Do you have any code which does this already? I'd like to use this functionality too!
