### ISSUE TITLE
Optional throwing exception when process is locked

### ISSUE THREAD

**Issue by marcins89** [lukas-krecan/ShedLock#1230]
I need to catch situation when process is locked.

You can add optional flag to properties which enable throwing exception when process is locked.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I think you can achieve it by wrapping `LockProvider` and throwing the exception yourself. In other words, you can create your own `LockProvider` that wraps the original one and that throws an exception if the original one returns an empty optional.
