### ISSUE TITLE
The schedule runs, but the database not update the lock_until & locked_at time, is it Thread Safe?

### ISSUE THREAD

**Issue by gclsoft** [lukas-krecan/ShedLock#1241]
**Describe the bug**
1. Which version do you use: 4.36.0
2. Which Lock Provider: JdbcTemplateLockProvider
3. ShedLock configuration:
```
@Configuration
@EnableSchedulerLock(defaultLockAtLeastFor = "5s", defaultLockAtMostFor = "10s")
class ShedlockConfig {
    @Bean
    fun lockProvider(dataSource: DataSource): LockProvider = JdbcTemplateLockProvider(dataSource)
}
```
4. ShedLock logs

**Expected behavior**
I have many jobs run at `0 45 4 ? * *`, their shedLock name is different,
some jobs in the shedlock table, didn't update the lock_until & locked_at time,
but execute their jobs. Why? Is it because it's not thread safe, then execute many @Schedule at the same time ? 

We are running on two nodes, two nodes runs will run one job at the same time together, the reason I know is I set the defaultLockAtLeastFor & defaultLockAtMostFor too small: 5s & 10s, and the two nodes' system time may be too big difference, or because the database time & the system time is too big difference, it can be explained, and I will set the time to 5m to solve. But I really don't know why the schedule runs, some jobs are all good but some jobs in the database table not update the lock_until & locked_at time (it's two nodes' job schedule both had run and logged) ,  how to explain?
Thanks very much!

**Actual behavior**
What happened instead.

**Comment by lukas-krecan** [comment]
Hi, please follow the [troubleshooting section](https://github.com/lukas-krecan/ShedLock#troubleshooting)

**Comment by gclsoft** [comment]
> Hi, please follow the [troubleshooting section](https://github.com/lukas-krecan/ShedLock#troubleshooting)

if all the 15 schedules start at the same time, by default the tread pool of schedule is 1, all the schedules execute one by one, so we must set the lock time very long, right? Otherwise the other node wait, but the first node had done the job long time ago, it will do again. Right?
Thanks very much @lukas-krecan
