### ISSUE TITLE
KeepAliveLockProvider is documented as being being useful only in special cases

### ISSUE THREAD

**Issue by stanlick** [lukas-krecan/ShedLock#1242]
I am incorporating shedlock in an existing multi-node app that was managing @Scheduled locking by way of custom code.  The goal is to remove the custom code in lieu of shedlock.  My question is this: We have scheduled tasks that vary wildly in required time to complete, so it is therefore risky using lockAtMostFor.  I have modified my configuration to use KeepAliveLockProvider and it appears to be working flawlessly.

Why would KeepAliveLockProvider not be the preferred configuration?  It seems the lock should be maintained no more/less than actual time required to invoke the method.  I realize @EnableSchedulerLock(defaultLockAtMostFor = "60m") is useful as a global trap

Thanks for spending what had to be an enormous amount of time creating this library

Best,
Scott

**Comment by lukas-krecan** [comment]
Hi, the `lockAtMostFor` parameter is only a failsafe for cases when a node dies. If the task finishes, the lock is released regardless the lockAtMostFor. My assumption was that users can estimate the maximal time the tasks takes to run and that nodes die rarely. `KeepAliveLockProvider` brings lot of complexity and it's better not to introduce it if you do not need it. But if your use case reqires it, feel free to use it. I am glad you find the library useful.
