### ISSUE TITLE
Documentation misleading

### ISSUE THREAD

**Issue by julianzur** [lukas-krecan/ShedLock#126]
Hi @lukas-krecan,

we just upgraded from 1.3.0 to the latest version 2.3.0 and figured out that the database was not updated until we introduced the @EnableSchedulerLock annotation. In the documentation it says that you **can** use this annotation but it is not required.
Is this a bug in the library or the documentation? If we are required to set this annotation, why are we then also required to set the "defaultLockAtMostFor" property if we want to override it anyways? 

Thanks for clarification!

Btw. we also updated to the latest Spring Boot version 2.1.2. Maybe the breaking change came with the Spring Boot update? 

> Enable Scheduler Locking
> 
> Now we need to integrate the library into Spring. Since version 2.0.0 you can use @EnableSchedulerLock annotation

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. You are required to use the annotation, I will fix the documentation. "defaultLockAtMostFor" is a failsafe. We need to know when to release the lock in when the node executing the task fails in case you do not specify it in \@ScheduledLock annotation
