### ISSUE TITLE
Database transactions allowed?

### ISSUE THREAD

**Issue by lukasl66** [lukas-krecan/ShedLock#128]
I like the simplicity of the ShedLock a lot and am looking forward to use it in my project. There is just one sentence in the documentation that I do not understand:
> For example if the task is fetching records from a database, processing them and marking them as processed at the end **without using any transaction**. In such case ShedLock may be right for you.

Would it be a problem to perform a database transaction in the scheduled task? Why? Thanks for clarifying!

**Comment by lukas-krecan** [comment]
Hi, thanks for the question. DB transactions are allowed, but if your tasks are using transactions correctly so they can run in parallel, you might not need ShedLock. I will try to clarify the documentation

**Comment by lukasl66** [comment]
Got it! Thanks for the clarification!
