### ISSUE TITLE
Fail to mvn install with v5.x.x

### ISSUE THREAD

**Issue by aam2elm** [lukas-krecan/ShedLock#1289]
When using v5.x.x the app fails to mvn install/run with the follwoing error:

"java: cannot access net.javacrumbs.shedlock.spring.annotation.EnableSchedulerLock
  bad class file: /C:/Users/****/.m2/repository/net/javacrumbs/shedlock/shedlock-spring/5.0.0/shedlock-spring-5.0.0.jar!/net/javacrumbs/shedlock/spring/annotation/EnableSchedulerLock.class
    class file has wrong version 61.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.".

This does NOT occur with v4.x.x

**Expected behavior**
App mvn-installs/runs successfully

**Actual behavior**
App fails to mvn-install/run with above-mentioned error.

**Comment by lukas-krecan** [comment]
Version 5.x.x requires Java 17. If you are running on lower versions, please keep using 4.x.x
