### ISSUE TITLE
only single thread to run

### ISSUE THREAD

**Issue by inotgaoshou** [lukas-krecan/ShedLock#129]
@Scheduled(cron = "${match.group1.cron}")
@SchedulerLock(name = "gameMatchGroup1Task"

if many Scheduled and SchedulerLock; only single thread to run; cannot multi thread to run at the same time;

**Comment by inotgaoshou** [comment]
add the config :@Configuration
@EnableScheduling
public class ScheduleConfig implements SchedulingConfigurer , the lock is invalid; will not save date into the mysql db.

**Comment by lukas-krecan** [comment]
Hi, sorry I do not understand what the issue is, can you please reformulate it?
