### ISSUE TITLE
Does not work with overridden methods.

### ISSUE THREAD

**Issue by aam2elm** [lukas-krecan/ShedLock#1295]
I'm using v4.43.0 with TaskScheduler mode. Also using Java 8.

Shedlock does not seem to work -intercept desired method- when placing @SchedulerLock over overridden methods.
No Shedlock entry in Shedlock table.

i.e.

`@Override
    @SchedulerLock(name = "scheduledTask", lockAtLeastFor = "5m", lockAtMostFor = "5m")
     public void run() {
        myBusinessMethod(arg);
    }`

**Comment by lukas-krecan** [comment]
Hi, ShedLock uses Spring AOP underneath. Spring AOP does not work well under some circumstances, please read more [here](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#aop-understanding-aop-proxies).
