### ISSUE TITLE
HazelcastLockProvider deadlock

### ISSUE THREAD

**Issue by HubertTatar** [lukas-krecan/ShedLock#130]
HazelcastLockProvider is using IMap.lock(lockname) to lock map key entry and releases it in finally block.
But if something happens (i.e. instance that obtained lock dies) before it call IMap.unlock(lockname) then structure will stay locked and all other instances that will try obtain lock will wait for possibility to acquire lock.

Solution to this is could be using IMap.lock(lockName, leaseTime, timeUint) that allows to set TTL for the lock on map key entry.

In Hazelcast log it results with information like this: 

> java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: a408fed4-77c7-4552-9143-6220039c5e84, thread ID: 116#012#011at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:75)#012#011at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:64)#012#011at com.hazelcast.spi.Operation.call(Operation.java:170)#012#011at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:208)#012#011at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197)#012#011at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:413)#012#011at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)#012#011at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)#012#011at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)#012java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: a408fed4-77c7-4552-9143-6220039c5e84, thread ID: 116

And all workers using Shedlock are disabled with stacktrace:

> sun.misc.Unsafe . park (Unsafe.java) (Native)
java.util.concurrent.locks.LockSupport . park (LockSupport.java:304)
com.hazelcast.spi.impl.AbstractInvocationFuture . get (AbstractInvocationFuture.java:156)
com.hazelcast.client.spi.ClientProxy . invokeOnPartition (ClientProxy.java:153)
com.hazelcast.client.spi.ClientProxy . invoke (ClientProxy.java:147)
com.hazelcast.client.proxy.ClientMapProxy . lock (ClientMapProxy.java:571)
com.hazelcast.client.proxy.ClientMapProxy . lock (ClientMapProxy.java:562)
net.javacrumbs.shedlock.provider.hazelcast.HazelcastLockProvider . lock (HazelcastLockProvider.java:76)
net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor . executeWithLock (DefaultLockingTaskExecutor.java:38)
some.package.TaskProcessor . executeUnderLock (TaskProcessor.java:79)

I can open an PR to fix it.

**Comment by lukas-krecan** [comment]
Hi, thanks a lot. If you want to, please provide a pull request. If you do not want to, just let me know. Thanks again.

**Comment by lukas-krecan** [comment]
The question is, what the timeout on the lock should be. Maybe we can use only the Hazelcast lock and not use the map at all, what do you think @peyo

**Comment by HubertTatar** [comment]
If you decide to stick with IMap i would add additional class with parameter passed via constructor and allow user to configure it.
Using Hazelcast Lock have one big advantage in my opinion. It removes problems with disappearing members and there will be one parameter for lock timeout.

**Comment by lukas-krecan** [comment]
I have been thinking about it and it seems we can use existing `lockAtMostFor` from the configuration.

**Comment by peyo** [comment]
Sorry, I don't remember why I have used `IMap` instead `ILock`, but I am sure that I tested it. However, more I think about it, more I wonder why `IMap`... and furthermore why I haven't used `leaveTime` parameter...

For me, and according to the `Hazelcast` documentation, change `IMap` by `ILock` and use the `leaveTime` parameter seems a good solution (better than mine).

**Comment by lukas-krecan** [comment]
Ok, we can do it in two steps.

1. Fix the bug by setting `lockAtMostFor` to lock timeout. 
2. Try to refactor the locking mechanism

@HubertTatar Can you please provide PR for 1 or shall I do it?

**Comment by HubertTatar** [comment]
Sure.  I will provide PR in the evening.

**Comment by HubertTatar** [comment]
Method unlock also locks map key entry without TTL. I guess it also should be used with leaseTime, but for how long leastTime should be set?

**Comment by lukas-krecan** [comment]
Will have to think about it. Thanks for the pull request

**Comment by peyo** [comment]
I will attempt to make an other PR with `ILock` implementation rapidly instead of `IMap`.

**Comment by lukas-krecan** [comment]
As a quickfix I have decided to do this https://github.com/lukas-krecan/ShedLock/pull/134 as proposed here https://github.com/lukas-krecan/ShedLock/issues/130#issuecomment-471444620 Sorry for the changes, it feels better like this.

**Comment by lukas-krecan** [comment]
Released as 2.4.0
