### ISSUE TITLE
Error log at startup with @SchedulerLock

### ISSUE THREAD

**Issue by Epiliptik** [lukas-krecan/ShedLock#1317]
Hello, 

I have several spring applications using an Oracle database with shedlock 4.44.0 and JdbcTemplateLockProvider.

I have a task @Scheduled running with @SchedulerLock(name="Task_lock_name")

Everything is working fine until I restart the app, I have a few logs like that :

```
2023-01-18T18:48:00.106 ERROR [3-thread-1]                       jdbc.sqltiming                 1. PreparedStatement.executeUpdate() FAILED! INSERT INTO <SCHEMA>.shedlock(name, lock_until, locked_at, locked_by) VALUES('Task_lock_name',

to_timestamp('01/18/2023 18:58:00.019', 'mm/dd/yyyy hh24:mi:ss.ff3'), to_timestamp('01/18/2023

18:48:00.045', 'mm/dd/yyyy hh24:mi:ss.ff3'), 'CH001')

 {FAILED after 26 msec}

java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (<SCHEMA>.SYS_C0081639) violated
```

It tries to insert a line in the shedlock table with the scheduling lock name but there is already one and the name is the primary key.

After a bit of time everything start to work fine but the error logs at the startup are polluting the logs.

Is this a bug or is there a way to fix it?

As far as I remember it was working fine with 4.33.0, the problem appeared after.

Thanks.

**Comment by lukas-krecan** [comment]
Hi, I assume it's logged by the JDBC driver, is that correct? It's how ShedLock works and always had. See for example similar issue https://github.com/lukas-krecan/ShedLock/issues/1123. 

In DBs that have reliable UPSERT we already switched to that, for Oracle there does not seem to be a good way to fix that.

**Comment by Epiliptik** [comment]
Yes it comes from the jdbc audit. Looks like there is no easy way to do it with oracle. So not much I can do as the log comes from the audit and not from shedlock if I understand correctly? Appart from deactivating the jdbc logs but that would not be great either.

**Comment by lukas-krecan** [comment]
If you want to, you can try to use merge https://stackoverflow.com/a/2692441/277042 in [OracleServerTimeStatementsSource](https://github.com/lukas-krecan/ShedLock/blob/master/providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/OracleServerTimeStatementsSource.java) and if the tests pass, send a PR. Unfortunately, I do not have capacity to do it myself.
