### ISSUE TITLE
Concurrent run for jdbc provider and possibly all others

### ISSUE THREAD

**Issue by ggaborg** [lukas-krecan/ShedLock#132]
If you have two concurrent threads trying to acquire a lock there is a small chance that both will be able to.

Thread 1 - init now variable - value is 1 (for simplification)
Thread 2 - init now variable - value is 2 (for simplification)
Thread 2 executes the update and acquires lock, until value in db is set to 1
Thread 1 executes the update and acquires lock because 1 < 2, until value in db is set to 2

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I do not understand, we always set the value until to the future now + lockAtMostFor. Even if it were not the case, it seems that you switched the values in your example -Tread 2 is supposed to set value 2, isn't it? Am I missing something?

**Comment by ggaborg** [comment]
Hi, yes I have switched the values by mistake, but that is not important.
Let me improve the scenario. Let's say the task has a lock at most until of 5 units.
Thread 1 - now = 0
Thread 1 - until = 0 + 5 = 5
GC start
Thread 1 - suspended 6 secs because of GC stop the world
Thread 2 - suspended 6 secs because of GC stop the world
GC over
Thread 2 - now = 6 (because of stop the world)
Thread 2 - until = 6 + 5 = 11
Thread 1 - update until in db to 5
Thread 2 - update succeeds also because 5 (until in db) <= 6 (now of Thread 2)

Hope it is clearer now.

**Comment by lukas-krecan** [comment]
I would say that's expected behavior. You said that maximum time for the lock to be held is 5 units, 5 units have passed so the lock is released and can be acquired by Thread 2.

**Comment by ggaborg** [comment]
It's not like thread 1 had the lock for the last 5 units and executed the task. 
The issue is that both threads will execute the task in parallel at 6 units.

**Comment by ggaborg** [comment]
And then both threads will try to release the lock since they both hold it

**Comment by lukas-krecan** [comment]
By setting `lockAtMostFor` you as a user say that the task will finish in 5 units and if not, we should consider the task to be dead. If this is not true, the task will be executed twice.

The same will happen if you set the `lockAtMostFor` to 1 minute but the task takes 15 minutes. You will end-up with multiple running tasks. I will stress it in the documentation.
