### ISSUE TITLE
Release lock by name

### ISSUE THREAD

**Issue by mikarty** [lukas-krecan/ShedLock#1339]
Hello,
Thanks for your work with this library!
Just started learning it and have a question - I wasn't able to find mechanism how to unlock manually.
Is there available some functionality for releasing locks the same way there is for extending them?
Example what I mean:
`LockManager.releaseActiveLock();`
`// LockExtender.extendActiveLock(Duration.ofMinutes(5), ZERO); <- similar to this`
and

`@Autowired LockProvider lockProvider;`
`lockProvider.releaseLock(name);`

To be more clear why I need it:
I will listen to RabbitMQ message of type `ReleaseLock(String name)`, and process this event by releasing a lock with corresponding name.

Thank you in advance!

**Comment by lukas-krecan** [comment]
Hi, the SimpleLock has `unlock` method. It should not be complicated to store the lock in a Map with name as a key.

**Comment by mikarty** [comment]
Hi,
Thanks for response, but could you please provide some minimal example? I don't understand at which point and how I should store Map of SimpleLocks, and will I still be able to declare locks using @SchedulerLock annotation?

**Comment by lukas-krecan** [comment]
Hi, I do not understand why would you use the annotation and release the lock externally. Either the task is running and you should not release the lock, or it finished, and then you do not need to keep it.

But anyways, your use-case is not supported.

**Comment by mikarty** [comment]
Hi,

So my use case is pretty straight forward. I'm using "shedlock-provider-jdbc-template". My batch jobs are implemented in event driven model instead of regular batch processing model (some random internet reference for similar idea https://pismo.io/blog/from-batch-jobs-to-an-event-driven-model/). That's why "Either the task is running and you should not release the lock, or it finished, and then you do not need to keep it" doesn't work in my case and I need to externally release the lock afterwards.

In my application batch job entry point is either from rest API or through scheduler, where I just publish amqp events to evenly distribute load and allow application to process everything at its own pace, because I will have plenty of different heavy jobs.
I need to lock process for the time being until it is fully processed or lockAtMostFor expired, because I don't want to spam more events until current job is finished. So shedlock works perfectly fine for making sure that job is triggered only once in clustered environment and as batch process state as whole (in progress/finished). So in cases, when I finish processing earlier (or it was failed), I would like to release lock by listening to amqp Unlock(name: String) event.

Example (Kotlin and Spring):

@SchedulerLock(name = "import_large_dataset_for_provider_id123", lockAtLeastFor = "1H", lockAtMostFor = "1H")
fun startImport(request: ImportRequest) {
val message = ImportCommand(
    uuid = UUID.randomUUID(),
    provider = "id123",
    page = request.page,
    maxPage = request.maxPage,
    pageLimit = request.pageLimit
)
messagePublisher.publishMessage(message = message)
}

**So if someone encounters similar needs as I do, when you require to externally unlock shedlock, I have implemented this as workaround (as I understood I don't have to clear cache, because I don't add or delete any locks, just changing "lock_until" column):**

@Component
class LockManager(
    private val jdbcTemplate: JdbcTemplate
) {

    fun unlock(name: String) {
        val sql = "UPDATE shedlock SET lock_until=? WHERE name=?"
        val lockUntil = Date.from(Instant.now())
        val params = arrayOf<Any>(lockUntil, name)
        val types = intArrayOf(Types.TIMESTAMP, Types.VARCHAR)
        jdbcTemplate.update(sql, params, types)
    }

}

So if you decide to implement some kind out of the box solution for this, it would be really cool. Anyways, thanks for help and have a great day!

**Comment by niezuxue** [comment]
no follow-up?
