### ISSUE TITLE
Please Support XML spring configuration

### ISSUE THREAD

**Issue by solidatyoungdevdotnet** [lukas-krecan/ShedLock#1344]
problem: The current mechanism for enabling shedlock is @EnableSchedulerLock.  This assumes that the application is not already bootstrapped by XML.  I am not sure why but simply enabling this annotation and letting it get picked up in classpath scanning is resulting in the applicationContext.xml loading without properties.  This important because without honoring properties from the props files, we cannot allow the spring bootstrap to pick up environmental configs.

What I want: I would like a sample XML config I can use with shedlock 4 and spring 4.2 to enable shedlock on my @Scheduled methods.

Alternatives: I have tried a hybrid approach (predifine the component beans in my app context xml and only using the @EnableSchedulerLock to "turn on" the shedlock feature.  

Here is my test scheduled class:
``` java
@Service
@Slf4j
public class SchedulerLockDemo {
	@Scheduled(cron="* */5 * * * *")
	@SchedulerLock(name="testFakeTask", lockAtMostFor = "5M")
	public void doFakeTask() {
		log.debug("Excuting fake task on scheduler");
		try {
			long minutes =  (long)((Math.random() * (300 - 60)) + 60);
			log.info("Sleeping {} minutes", minutes);
			Thread.sleep( minutes * 1000L);
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
		log.debug("Completed executing fake task");
		
	}
}
```
Here is the spring XML I am using to create the shedlock lock provider
```xml
<bean class="net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateLockProvider"
		id="lockPovider">
                <!-- datasource is previously defined as a bean named dataSource earlier in the XML -->
		<constructor-arg index="0" ref="dataSource"/> 
</bean>
```

Here is the  java class to "turn on" the shedlock features:
```java
@Configuration
@EnableSchedulerLock(interceptMode = PROXY_SCHEDULER, defaultLockAtMostFor = "30m")
public class SchedulingConfiguration {

}
```

**Comment by lukas-krecan** [comment]
Hi, I do not see any reason why would properties loading break when you "enable the annotation". I would recommend to figure-out why it fails, mixing XML and Java config should work without any issue.

If you need XML config regardless, you can either use 2.6.0 ShedLock release or implement your own.

**Comment by solidatyoungdevdotnet** [comment]
Can you please link to the documentation for 2.6.0, I have downgraded to 2.6.0 but cannot find sample XML anywhere

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/ShedLock/tree/shedlock-parent-2.6.0#spring-xml-configuration
