### ISSUE TITLE
Document programmatic usage

### ISSUE THREAD

**Issue by tsmgodoi** [lukas-krecan/ShedLock#135]
I need to use the lock mecanism without the @SchedulerLock annotation. That's because I'm not using the @Scheduler annotation on a specific scenario. I'm having a hard time figuring out the best way to use it.
I'm directly calling the method:
`TaskScheduler.scheduleWithFixedDelay`
I know it will wrap it with a LockableRunnable, but I won't be able to control the name of the lock like when using annotations and that will be a problem.
Maybe I should override the DefaultLockManager?
Is this lib meant to be used on a programmatic way?

**Comment by lukas-krecan** [comment]
Hi, is this not sufficient https://github.com/lukas-krecan/ShedLock#running-without-spring ?

**Comment by tsmgodoi** [comment]
Well, actually I want to use it with spring but in a programmatic way. I guess I can wrap my Runnable to call that code. If so mayble I shouldn't configure the SpringLockableTaskSchedulerFactoryBean, since it would already wrap it. I'm studying some other options so I can keep using the spring TaskScheduler. (Suppose I want to use it in both programmatic and annotation way.)

**Comment by lukas-krecan** [comment]
You can use both if you wish. You can also take a look at LockableTaskScheduler for inspiration. Btw. SpringLockableTaskSchedulerFactoryBean is deprecated in favor of @ EnableSchedulerLock annotation

**Comment by oleksanderkorn** [comment]
This is the way how I use it programmatically in kotlin and spring boot. I also need to reschedule it dynamically through the api, and I store the cron expression in the database. The app also runs in a cluster, so I need to check if cron expression haven't changed by another instance, so before executing scheduled task I check that the cron expression is still the same (cronRepository is a Spring Data Repository instance cron expression is stored):
```kotlin
import net.javacrumbs.shedlock.core.DefaultLockManager
import net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor
import net.javacrumbs.shedlock.core.LockConfiguration
import net.javacrumbs.shedlock.core.LockProvider
import net.javacrumbs.shedlock.spring.LockableTaskScheduler
import org.slf4j.LoggerFactory
import org.springframework.scheduling.TaskScheduler
import org.springframework.scheduling.support.CronTrigger
import org.springframework.stereotype.Component
import java.time.Duration
import java.time.Instant
import java.time.LocalDateTime
import java.util.*
import java.util.concurrent.ScheduledFuture
import javax.annotation.PostConstruct

@Component
class Scheduler(
    private val lockProvider: LockProvider,
    private val taskScheduler: TaskScheduler,
    private val configRepository: ConfigRepository
) {
    private val logger = LoggerFactory.getLogger(this.javaClass)
    private var scheduledTaskState: ScheduledFuture<*>? = null
    private var cronTrigger: CronTrigger? = null

    private fun rescheduleTask() {
        logger.debug("Reschedule task [${LocalDateTime.now()}]")
        scheduleTask()
    }

    private fun cancelScheduledTask() {
        logger.debug("Cancel task [${LocalDateTime.now()}]")
        val cancel = scheduledTaskState?.cancel(false)
        logger.debug("Canceled task result [${cancel}]")
    }

    @PostConstruct
    private fun scheduleTask() {
        val executor = DefaultLockingTaskExecutor(lockProvider)
        val lockAtLeastFor = Duration.ofSeconds(0)
        val lockAtMostFor = Duration.ofMinutes(1)
        val lockConfiguration = LockConfiguration(
            Instant.now(),
            "LockScheduler_scheduleTask",
            lockAtMostFor,
            lockAtLeastFor
        )
        val lockManager = DefaultLockManager(executor) { Optional.of(lockConfiguration) }
        val lockableTaskScheduler = LockableTaskScheduler(taskScheduler, lockManager)
        val dbValue = configRepository.findAll().firstOrNull()?.cronExpression
        cronTrigger = CronTrigger(dbValue!!)
        scheduledTaskState = lockableTaskScheduler.schedule(runIfUnchanged(), cronTrigger!!)
    }

    private fun runIfUnchanged() = Runnable {
        val currentDbValue = configRepository.findAll().firstOrNull()?.cronExpression
        if (cronTrigger?.expression == currentDbValue) {
            logger.debug("Schedule task [${LocalDateTime.now()}]")
        } else {
            logger.debug("Cron Expression has been changed by some other process. Ignore the run, cancel and re-schedule job.")
            cancelScheduledTask()
            rescheduleTask()
        }
    }
}
```

And here is my SchedulerConfiguration:
```kotlin
@EnableScheduling
@EnableSchedulerLock(defaultLockAtMostFor = "PT30S")
@Configuration
class SchedulerConfiguration {
    @Bean
    fun lockProvider(dataSource: DataSource): LockProvider {
        return JdbcTemplateLockProvider(
            JdbcTemplateLockProvider.Configuration
                .builder()
                .usingDbTime()
                .withJdbcTemplate(JdbcTemplate(dataSource))
                .build()
        )
    }

}
```

**Comment by mrBungalow** [comment]
The programmatic way to schedule these has been deprecated. Is there a new way to do this in Spring Boot 4?

**Comment by lukas-krecan** [comment]
@mrBungalow Can you please describe what exactly are you trying to achieve and what exactly has been deprecated?
