### ISSUE TITLE
Configuration for upper- and lowercase table/column names for JDBC

### ISSUE THREAD

**Issue by Ragin-LundF** [lukas-krecan/ShedLock#1362]
**Problem**
Depending on the database (settings), it might be, that tables are uppercase and that the system reacts case-sensitive.
We have this "problem" at the moment with MariaDB, because we basically have all table names defined as upper case.

**Solution**
In such a case, it would be much easier to tell the JdbcProvider builder to use uppercase instead of redefining the table name and columns.

I prepared a PR, which solves the issue with a very small change.

**Comment by lukas-krecan** [comment]
Released as 5.2.0
