### ISSUE TITLE
Upgrade Shedlock with spring boot to 2.7.7

### ISSUE THREAD

**Issue by haljazara-innovationteam** [lukas-krecan/ShedLock#1369]
We were using the Shedlock 2.5 version using **shedlock-spring**, and **shedlock-provider-jdbc-template** artifacts with spring 1.5.10 and we are upgrading spring boot to 2.7.7, so what is the recommended version, and what are the possible side effects of this upgrade?

**Comment by haljazara-innovationteam** [comment]
@lukas-krecan can you please provide your feedback

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/ShedLock#versions
