### ISSUE TITLE
Invalid task in multi-threaded timing

### ISSUE THREAD

**Issue by IsResultXaL** [lukas-krecan/ShedLock#137]
![image](https://user-images.githubusercontent.com/10142184/55861391-dfddd000-5ba8-11e9-9995-3a4167dbf550.png)

When I set spring's timing task to be multi-threaded, ShedLock  invalid

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. In what way is ShedLock invalid?

**Comment by IsResultXaL** [comment]
![image](https://user-images.githubusercontent.com/10142184/55863574-61cff800-5bad-11e9-95bc-73a6b0827f04.png)
![image](https://user-images.githubusercontent.com/10142184/55863593-6f857d80-5bad-11e9-8d45-a59b94628a60.png)
![image](https://user-images.githubusercontent.com/10142184/55863619-7d3b0300-5bad-11e9-8bfd-d291e83260d1.png)

When I run two programs，Perform tasks simultaneously

**Comment by IsResultXaL** [comment]
![image](https://user-images.githubusercontent.com/10142184/55863750-be331780-5bad-11e9-9715-4629b36a6439.png)
![image](https://user-images.githubusercontent.com/10142184/55863894-018d8600-5bae-11e9-8d98-cdc07e66ec6c.png)

**Comment by IsResultXaL** [comment]
because spring's timed task is single thread, 
when i use single thread, ShedLock is OK

**Comment by lukas-krecan** [comment]
I see, be specifying your task scheduler directly in scheduled task registrar, you basically remove ShedLock. You can either specify TaskScheduler as a bean or use PROXY_METHOD mode (both options are described here https://github.com/lukas-krecan/ShedLock#modes-of-spring-integration)

**Comment by IsResultXaL** [comment]
Thank you, I try

**Comment by IsResultXaL** [comment]
@EnableSchedulerLock(mode = PROXY_METHOD, defaultLockAtMostFor = "PT30S")
Successful！
Thank you very much!
