### ISSUE TITLE
shedlock-test-support package as a jar

### ISSUE THREAD

**Issue by mmastika** [lukas-krecan/ShedLock#1383]
Hi Lucas,

Was wondering if you have any plan on publishing the shedlock-test-support as well? The reason is that it'll make it easier to experiment with a new provider, before hopefully contribute back to your project.

Cheers,

**Comment by mmastika** [comment]
Hi Lucas,
All good, apology for the late reply as well.

I was experimenting with a new provider in an environment where forking and custom jar/package is heavily discouraged. My only option at the time was to have the experiment within the codebase I was working on. Having my experiment passing the standard tests would give me some level of comfort before further testing in the live environment. There wasn't an easy way for me to have the standard tests since it's not packaged hence the question and the ticket.

On another note, I found the result of the experiment is encouraging, and would like to contribute a Google Datastore provider. How do I go on about it?

Regards,

**Comment by lukas-krecan** [comment]
Hi, just fork the repository and send a pull request. Use the `providers` directory and mimic the structure of other providers. Please, also provide a test, there is a test class you can extend. Thanks a lot

**Comment by mmastika** [comment]
Hi @lukas-krecan ,

Thanks for the response. 

Please have a look at the [pull request here](https://github.com/lukas-krecan/ShedLock/pull/1457) .
In any case, I still urge you to create the shedlock-test-support as an artefact, especially since you already have the maven BOM structure to make.
