### ISSUE TITLE
Ability to Wait on Lock to Expire

### ISSUE THREAD

**Issue by EarthCitizen** [lukas-krecan/ShedLock#1390]
I need to rate limit some outgoing requests. Therefore, I would like the ability for tasks to queue up to only go out at a metered rate. The way, I suppose, to do this would be to simply have a configuration option to wait for the lock to expire instead of just giving up.

Can this be achieved as the library is now, or would this require a new feature?

Basically, I want to do what the `StorageBasedLockProvider` does except that it waits and tries again to acquire the lock.

**Comment by lukas-krecan** [comment]
Hi, yes, you can do that. You can create a your LockProvider, wrapping the original one and do whatever you need there.
