### ISSUE TITLE
shedlock Duplicate ‘InstTask’ entry for key 'PRIMARY'

### ISSUE THREAD

**Issue by lingdiand** [lukas-krecan/ShedLock#1397]
I am using version 4.44.0 and the database is MySQL. As my project restarts regularly every day, I need to "insert ignore into"

> MySqlServerTimeStatementsSource

`
String getInsertStatement() {
        return "INSERT IGNORE INTO " + this.tableName() + "(" + this.name() + ", " + this.lockUntil() + ", " + this.lockedAt() + ", " + this.lockedBy() + ") VALUES(:name, " + "TIMESTAMPADD(MICROSECOND, :lockAtMostForMicros, UTC_TIMESTAMP(3))" + ", " + "UTC_TIMESTAMP(3)" + ", :lockedBy)";
    }
`

I found that only when `usingDbTime()` is used will `MySqlServerTimeStatementsSource` be matched, otherwise it is `SqlStatementsSource`, `SqlStatementsSource`uses "insert into"

The use of  `usingDbTime()` can lead to a problem: the time recorded in the data table is inconsistent with the server. For example, my scheduled task is executed at 7 o'clock, while the time recorded in the database is yesterday at 23 o'clock

**Comment by lukas-krecan** [comment]
Hi, I recommend ` usingDbTime`. It uses UTC, which explains the discrepancy. I really don't recommend using other timezones. Imagine what's going to happen to your locks when daylight savings change moves clock one hour to the past

**Comment by lingdiand** [comment]
Using standard UTC can cause time chaos, and my region uses UTC+8. In the end, I did not `usingDbTime`. When the scheduled task starts, an error `Duplicate ‘InstTask’ entry for key 'PRIMARY'` will be reported, but the scheduled task can run normally
