### ISSUE TITLE
ZookeeperCuratorLockProvider and lockAtLeastFor property

### ISSUE THREAD

**Issue by stefano-salmaso** [lukas-krecan/ShedLock#140]
Property `lockAtLeastFor` is not supported by `ZookeeperCuratorLockProvider`. This is not so clear and explicit in the documentation!
Could be useful to highlight this in the `README.md` file.

But.. is there any chance to have this feature available also for Zookeeper?
Is there any problem or technical reason why it is not implemented?

Thanks

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I have updated the documentation. I'd like to implement the feature, but I do not know how yet. Will  think about it.

**Comment by lukas-krecan** [comment]
This should do it https://github.com/lukas-krecan/ShedLock/pull/141

**Comment by lukas-krecan** [comment]
Released as 2.5.0
