### ISSUE TITLE
 "DuplicateKey" error being thrown when attempting to acquire a lock on a specific task or job

### ISSUE THREAD

**Issue by ahmadsab95** [lukas-krecan/ShedLock#1411]
Read the documentation
I have read the documentation, including the troubleshooting section, but did not find a solution to my issue.

I am using version 4.33.0 of the "shedLock" library with MongoDB.

Describe the bug

Version: 4.33.0 of the "shedLock" library
Lock Provider: MongoDB
ShedLock Configuration: I am using the "Scheduler" and "SchedulerLock" features to acquire locks on specific tasks or jobs.
ShedLock Logs: When attempting to acquire a lock on a specific task or job, I receive a "DuplicateKey" error with error code 11000 indicating that there was an attempt to insert a document with a value that already exists in the index. The index in question is named "id" and has a unique constraint on the "_id" field with a value of "WorkflowTriggersTask".
Expected behavior
I expected to be able to acquire a lock on the specified task or job without any errors.

Actual behavior
Instead, I received a "DuplicateKey" error with error code 11000 when attempting to acquire the lock. The error message indicated that there was an attempt to insert a document with a value that already exists in the index, suggesting an issue with the indexing or locking mechanism used by the "shedLock" library when used with MongoDB.

**Comment by lukas-krecan** [comment]
Hi, can you please attach the stack trace? What version of MongoDb driver do you use?

**Comment by ahmadsab95** [comment]
Sure , 
Mongo driver version  - 4.6.1

i don't have the full stack trace but i have the log from mongo server - 

`{"t":\{"$date":"2023-04-27T00:00:04.408-04:00"}

,"s":"W",  "c":"COMMAND",  "id":23802,   "ctx":"conn11878","msg":"Plan executor error during findAndModify","attr":{"error":{"code":11000,"codeName":"DuplicateKey","errmsg":"E11000 duplicate key error collection: halo.shedLock index: id dup key:

{ _id: \"WorkflowTriggersTask\" }

","keyPattern":{"_id":1},"keyValue":{"_id":"WorkflowTriggersTask"}},"stats":{"stage":"###","nReturned":"###","executionTimeMillisEstimate":"###","works":"###","advanced":"###","needTime":"###","needYield":"###","saveState":"###","restoreState":"###","failed":"###","isEOF":"###","nMatched":"###","nWouldModify":"###","nWouldUpsert":"###","inputStage":{"stage":"###","filter":{"lockUntil":{"$lte":"###"}},"nReturned":"###","executionTimeMillisEstimate":"###","works":"###","advanced":"###","needTime":"###","needYield":"###","saveState":"###","restoreState":"###","isEOF":"###","docsExamined":"###","alreadyHasObj":"###","inputStage":{"stage":"###","nReturned":"###","executionTimeMillisEstimate":"###","works":"###","advanced":"###","needTime":"###","needYield":"###","saveState":"###","restoreState":"###","isEOF":"###","keyPattern":

{"_id":"###"}

,"indexName":"###","isMultiKey":["###"](https://cedt-icg-jira.nam.nsroot.net/jira/browse/C175678Q-2702#%23%23%22),"multiKeyPaths":{"_id":[]},"isUnique":"###","isSparse":"###","isPartial":"###","indexVersion":"###","direction":"###","indexBounds":{"_id":"###"},"keysExamined":"###","seeks":"###","dupsTested":"###","dupsDropped":"###"}}},"cmd":{"findAndModify":"shedLock","query":{"$and":[

{"_id":"WorkflowTriggersTask"}

,{"lockUntil":{"$lte":

{"$date":"2023-04-27T04:00:04.399Z"}

}}]},"update":{"$set":{"lockUntil":

{"$date":"2023-04-27T04:00:34.399Z"}

,"lockedAt":{"$date":"2023-04-27T04:00:04.399Z"},"lockedBy":"halo-service-halo-bcs-uat-113-js9g6"}},"upsert":true,"new":false,"writeConcern":{"w":1}}}}`

**Comment by lukas-krecan** [comment]
Hi, you can check the code [here](https://github.com/lukas-krecan/ShedLock/blob/master/providers/mongo/shedlock-provider-mongo/src/main/java/net/javacrumbs/shedlock/provider/mongo/MongoLockProvider.java#L121). It seems there is a still valid lock.

**Comment by ahmadsab95** [comment]
Based on my understanding, the problem appears to be a race condition between multiple instances that are attempting to create a lock. Both instances attempt to create the lock, but only one succeeds while the second one fails due to a duplicate key.
Does this appear to be a typical behavior?

**Comment by lukas-krecan** [comment]
Yes. That's the purpose of ShedLock, to prevent concurrent execution.
