### ISSUE TITLE
【Question】problem of inconsistent clocks across multiple servers

### ISSUE THREAD

**Issue by trickMin** [lukas-krecan/ShedLock#1439]
My microservice is deployed on multiple servers, and in some cases, there are inconsistencies in the clocks of the servers. I want to know if ShedLock can handle this scenario.

If ShedLock does not have a direct solution for this issue, what are some general solutions or suggestions for this problem? 😃

**Comment by lukas-krecan** [comment]
Hi, it depends on the lock provider. If you use JdbcTemplateLockProvider, you can configure it to `useDbTime()` (see the docs)
