### ISSUE TITLE
@Transactional seems to be ignored with 'PROXY_SCHEDULER' mode.

### ISSUE THREAD

**Issue by jungrammer** [lukas-krecan/ShedLock#144]
I am using shedlock version 2.1.0.

As shown below
`
@EnableSchedulerLock(defaultLockAtMostFor = "PT5S")
`

If I throw an error in a method with @Transactional.
ex)
`
    @Transactional
    public void test() {
        testRepository.save(Test.builder()
                .test("test")
                .build());
        throw new RuntimeException();
    }
`

Rollback is not applied.

To make a few guesses
It seems to happen only in `PROXY_SCHEDULER` mode,
Using the latest version will roll back normally.

I wonder if this problem is completely resolved.

Thx.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I was not aware of such bug. It might have been fixed in 2.3.0, before Spring sometimes got confused by ShedLock config and initialized beens in unexpected order. Will try to write a test.
