### ISSUE TITLE
No visible error if lock name too long

### ISSUE THREAD

**Issue by jcharra** [lukas-krecan/ShedLock#145]
There seems to be no visible error if the lock name exceeds the length of the shedlock.name database column. 

In my case, the column length was 64 (as I just copied & pasted your CREATE TABLE statement from the docs), and unfortunately I picked a column name with length 65, resulting in the scheduler not being started at all. An exception in the logfile might have pointed me in the right direction earlier. 

I'd suggest throwing or at least logging an exception in case writing the lock to the database fails.

**Comment by lukas-krecan** [comment]
Thanks for feedback. It makes sense, will fix it in jdbc-template lock provider only.
