### ISSUE TITLE
lockAtLeastFor large values

### ISSUE THREAD

**Issue by fredericks** [lukas-krecan/ShedLock#1461]
Hello, I'm trying to use correctly ShedLock, but there's something I'm missing.

This is one of my tasks:

`@Scheduled(cron = "${maintenance_task.cron:-}")`
`@SchedulerLock(name = "Maintenance", lockAtLeastFor = "${maintenance_task.lock_duration:PT1M}")`
`public void runMaintenanceTask() {`
`            ...`
`}`

where properties are:

maintenance_task.lock_duration=PT1M
maintenance_task.cron=0 * * * * *

Now, the strange thing is that every time a lock is inserted in the table, the column "loack_until" is always 5 minutes later. Then the value is adjusted when the task actually ends.

I tried to change lockAtLeastFor  with different values: PT1M, PT2M, PT3M but when I try something larger than 5 minutes the task just doesn't start

Am I missing something?
Thanks

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/ShedLock#annotate-your-scheduled-tasks

**Comment by fredericks** [comment]
> https://github.com/lukas-krecan/ShedLock#annotate-your-scheduled-tasks

First of all, thanks for the answer.

I've read the docs,  it looks correct to me.

Why my task won't start when I use the confugration below?

`@Scheduled(cron = "0 * * * * *")`
`@SchedulerLock(name = "Maintenance", lockAtLeastFor = "PT10M")`
`public void runMaintenanceTask() {`
`}`
