### ISSUE TITLE
Lightweight transactions error on Cassandra with multi-region writes enabled

### ISSUE THREAD

**Issue by paul-gardiner** [lukas-krecan/ShedLock#1462]
- Version 5.5.0
- shedlock-provider-cassandra, 5.5.0 
- configured as example, with lock-at-least 30, lock-at-most 60.
[shedlock.log](https://github.com/lukas-krecan/ShedLock/files/11819678/shedlock.log)
- Using Cassandra on Azure Cosmosdb

**Expected behavior**
Able to schedule tasks. This works fine when multi-region writes is set to false.
**Actual behavior**
Get exception from datastax: com.datastax.oss.driver.api.core.servererrors.ServerError: Lightweight transactions are not implemented yet for multiple write locations 
This only happens when multi-region writes is set to true.

**Comment by lukas-krecan** [comment]
Hi, there is not much I can do to help you. Please check the [source](https://github.com/lukas-krecan/ShedLock/blob/master/providers/cassandra/shedlock-provider-cassandra/src/main/java/net/javacrumbs/shedlock/provider/cassandra/CassandraStorageAccessor.java) to see there is nothing special. I would recommend you to check the consistency level settings, it may in theory work with different settings. If you find out how to fix it, please let me know.

**Comment by paul-gardiner** [comment]
Thanks. Consistency levels don't change anything, and it looks like getting this to work with Cassandra across regions will be difficult. I think I'll implement a lock provider for CosmosDB with the SQL api, and drop Cassandra.

**Comment by paul-gardiner** [comment]
It's working fine with CosmosDB in multiple regions, so closing the issue.
