### ISSUE TITLE
Add the capability to select the Lock provider on SchedulerLock when we have multiple instances in context

### ISSUE THREAD

**Issue by zoubakan** [lukas-krecan/ShedLock#1463]
On the same application, there is no way to select which Lock to use from two or more instantiated LockProvider beans with different implementations/data sources.  I know that one alternative is to use a custom LockProvider implementation with a datasource selector like done in the multi-tenant sample, but in some use cases it's difficult to resolve a discriminant value from the execution context to do the selection.

A solution is to provide an option to select the lockProvider instance by adding a new optional parameter (lockProviderName for example) on @SchedulerLock annotation.

Thanks,
Zoubeir KANOUN
Java Engineer

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback.  I will not be willing to add lockProviderName to the annotation as it would increase coplexity for a litle gain. I see two solutions for your problem.
1. Encode the lockProvider to the lock name like `lockProviderA:lockName` and use the solution from multitenant sample.
2. Implement your own annotation using AOP and [this](https://github.com/lukas-krecan/ShedLock#locking-without-a-framework).

**Comment by zoubakan** [comment]
Thanks Lukas for the kick response, it was very helpful.
