### ISSUE TITLE
Feature: Support Reactive methods

### ISSUE THREAD

**Issue by Airidas36** [lukas-krecan/ShedLock#1470]
**Is your feature request related to a problem? Please describe.**
With the new Spring `6.1.0-M1` version, methods annotated with `@Scheduled` can now return `Publisher` types e.g (`Mono`, `Flux`, etc.) https://github.com/spring-projects/spring-framework/pull/29924

Currently Shedlock does not support this and the application startup fails with the following message:
`Caused by: java.lang.IllegalStateException: Could not create recurring task for @Scheduled method 'reportPendingReports': Cannot obtain a Publisher-convertible value from the @Scheduled reactive method`. 

You can trick Spring by configuring Shedlock `interceptMode` to `EnableSchedulerLock.InterceptMode.PROXY_SCHEDULER`, but then Shedlock autoconfiguration silently fails because `SpringLockConfigurationExtractor` only supports tasks of type `ScheduledMethodRunnable` and the task type is `org.springframework.scheduling.annotation.ScheduledAnnotationReactiveSupportSubscribingRunnable`. Therefore lock configuration is not acquired and `DefaultLockManager` executes the task without a lock.

**Comment by lukas-krecan** [comment]
Hi, I will look into that. In the meantime, can you please explain what's the use-case for reactive scheduled method. Thanks

**Comment by Airidas36** [comment]
> Hi, I will look into that. In the meantime, can you please explain what's the use-case for reactive scheduled method. Thanks

Hi, 

Previously, if code-base was reactive, it was up to the developer to actually bridge the reactive piece of code with the Spring Scheduler. You would need to explicitly subscribe to / block the reactive pipeline to start a scheduled task.  On top of that, `fixedDelay` was never working correctly since Spring was not actually aware of when the subscribed publisher emmited `onComplete/onError` and would schedule a new task even if the old one was still running.

This new feature also supports different types of `Publishers` - and not necessarily the ones from Project Reactor. RxJava, Reactor, Kotlin suspended functions - return types that that can be adapted to `Publisher` using `ReactiveRegistryAdapter` (`CompletableFuture`, `Mono`, `Flux`, `Flow`, `Flowable`, `Completable`) are now supported and handled by the `ScheduledAnnotationBeanProcessor`.

The developer does not need to worry about bridging the piece of reactive code with Springs' Scheduler, it is handled by the framework itself, including subscribing to the provided `Publisher`, tracking/cancelling/disposing of the subscription.

**Comment by lukas-krecan** [comment]
Thanks, I looked into that and it's going to be tricky. 
1. Ideally, we should reuse the [ScheduledAnnotationReactiveSupport](https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/scheduling/annotation/ScheduledAnnotationReactiveSupport.java#L82) class, but as it will only part of Spring 6.1, ShedLock would have to require Spring 6.1. Morover, the methods are package-protected.
2. It introduces unnecessary complexity. I try to stay clear of reactive code as it usually brings more problems then it solves.
3. It will become obsolete as soon as Loom will get out.

So, unless somebody will be able to contribute the code, this is not going to happen. 

For those thinking about contributing the code: 
1. Please make sure it's well tested for all cases from [here](https://github.com/spring-projects/spring-framework/pull/29924/files#diff-46dbc7120bed19924bc51399ee1ae5c9ba5e128b4e829376a319c245ae9e1317). 
2. Make sure the code is small, well isolated and understanable
3. Make sure it works will all currently supported versions of Spring
