### ISSUE TITLE
Oracle Fast Connection Failover trips up JDBC database detection

### ISSUE THREAD

**Issue by metron2** [lukas-krecan/ShedLock#1477]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

Update to the latest version.

**Describe the bug**
Shedlock 5.5.0, JdbcTemplateLockProvider with Oracle FCF and dbTime

Oracle supports a highly available database configuration if you use network storage (Oracle ZFS). It looks like some of these oracle classes don't implement `connection.getMetaData().getDatabaseProductName())` properly.

**Expected behavior**
Nothing exciting

**Actual behavior**
The Oracle connection returns "Unknown" for database type, causing an exception to be thrown. 
https://github.com/lukas-krecan/ShedLock/blob/master/providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/SqlStatementsSource.java#L80

**Comment by lukas-krecan** [comment]
Released in 5.6.0
