### ISSUE TITLE
a method and execute it again and again

### ISSUE THREAD

**Issue by younghulk** [lukas-krecan/ShedLock#148]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

**Describe the bug**
1. Which version do you use
2. Which Lock Provider
3. ShedLock configuration
4. ShedLock logs

**Expected behavior**

**Actual behavior**
What happened instead.

 两台主机在一个时间点同时执行， 如果一个机器的数据库连接未配置，此时两台主机的任务都会执行。

**Comment by lukas-krecan** [comment]
Sorry, I do not understand the question. Please read the troubleshooting section https://github.com/lukas-krecan/ShedLock#troubleshooting
