### ISSUE TITLE
shedlock-bom contains modules that no longer exist

### ISSUE THREAD

**Issue by rhys-saldanha** [lukas-krecan/ShedLock#1480]
Version: 5.5.0 (latest at time of writing)

Modules in BOM that no longer exist:

shedlock-provider-elasticsearch
shedlock-provider-couchbase-javaclient
shedlock-provider-redis-jedis
shedlock-provider-dynamodb

**Comment by lukas-krecan** [comment]
Thanks, we will remove them next week. Does it have any impact?

**Comment by rhys-saldanha** [comment]
The company I work for manages an internal Maven repository. I use the BOM to import shedlock and all its providers in one go. 

This is currently failing as the above modules cannot be found in Maven Central, which blocks me from using the latest version of shedlock.

**Comment by lukas-krecan** [comment]
Released in 5.6.0
