### ISSUE TITLE
Use shedlock for any method

### ISSUE THREAD

**Issue by Caozhitong** [lukas-krecan/ShedLock#149]
I am using shedlock version 2.5.0.

As shown below:
`
@SchedulerLock(name = "TransactionDocumenting", lockAtLeastForString = lockAtLeast, lockAtMostForString = lockAtMost)
public void documenting() {
    ... do something
}`

this method is not a non-scheduled method (without annotation `@Scheduled`)，distributed` locks need to be  added to it, but it is no work..
how to implemented by shedlock?

thanks!

**Comment by lukas-krecan** [comment]
You can try this https://github.com/lukas-krecan/ShedLock/blob/master/README.md#scheduled-method-proxy

**Comment by Caozhitong** [comment]
> You can try this https://github.com/lukas-krecan/ShedLock/blob/master/README.md#scheduled-method-proxy

Thank you for your reply
