### ISSUE TITLE
Add lock configuration to database 

### ISSUE THREAD

**Issue by wjudeh** [lukas-krecan/ShedLock#153]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wjudeh** [comment]
I'm looking for to add lock configuration to the oracle database, for instance, LOCK_AT_LEAST and LOCK_AT_MOST.
is there any way to extend Shedlock entity/service to add this feature?

**Comment by lukas-krecan** [comment]
Hi, you can wrap/extend/reimplement LockProvider to do so https://github.com/lukas-krecan/ShedLock/blob/master/shedlock-core/src/main/java/net/javacrumbs/shedlock/core/LockProvider.java
