### ISSUE TITLE
Scheduling cron jobs programatically

### ISSUE THREAD

**Issue by g-sahu** [lukas-krecan/ShedLock#154]
Hi,
I want to schedule my cron jobs and prevent them from running on multiple nodes simultaneously using Shedlock. But I want to do this programmatically i.e without using @SchedulerLock annotation.

I checked the post https://github.com/lukas-krecan/ShedLock#running-without-spring
 but 'LockingTaskExecutor' does not seem to provide a method to schedule a cron job.

Could you please let me know if this is achievable using ShedLock?

**Comment by lukas-krecan** [comment]
ShedLock only takes care about locking, scheduling had to be done by some other library.
