### ISSUE TITLE
The lock is NOT released as soon the tasks finishes

### ISSUE THREAD

**Issue by niezuxue** [lukas-krecan/ShedLock#1542]
> You can also set lockAtMostFor attribute which specifies how long the lock should be kept in case the executing node dies. This is just a fallback, under normal circumstances the lock is released as soon the tasks finishes. You have to set lockAtMostFor to a value which is much longer than normal execution time. If the task takes longer than lockAtMostFor the resulting behavior may be unpredictable (more than one process will effectively hold the lock).

This is a reference to the document. For the following sentence, if I set lockAtLeastFor attribute I found that the lock is NOT released as soon the tasks finishes. But if I don't set this attribute, I can't makes sure the scheduled tasks are executed at most once at the same time.
> under normal circumstances the lock is released as soon the tasks finishes

**Comment by lukas-krecan** [comment]
Can you please describe what you want from me. Do you. Want to make the documentation more clear?

**Comment by niezuxue** [comment]
I mean the document and the code is not match, as mentioned from the question title.
**The lock is NOT released as soon the tasks finishes**

**Comment by lukas-krecan** [comment]
The whole purpose of the lockAtLeastFor is to keep the lock longer than for the task duration

**Comment by niezuxue** [comment]
Ok
