### ISSUE TITLE
Trigger exeption if is locked ?!

### ISSUE THREAD

**Issue by ricardojlrufino** [lukas-krecan/ShedLock#1556]
Is it possible to configure to throw an exception if is locked?

**Comment by ricardojlrufino** [comment]
I implemented in this commit https://github.com/lukas-krecan/ShedLock/pull/1553/commits/33fe767f9002f7a38a387fb95df5b8e07f28bca3
But it was specific to quarkus/redis

**Comment by lukas-krecan** [comment]
You can use this https://github.com/lukas-krecan/ShedLock#customization

**Comment by ricardojlrufino** [comment]
I think it would be nice to update this example, with this exception case to make it clearer, mainly because it is a little counterintuitive, because it uses inverted logic.

**Comment by ricardojlrufino** [comment]
about the pull request, I would just like you to see the latest comments.
https://github.com/lukas-krecan/ShedLock/pull/1553
