### ISSUE TITLE
when using custom thread pool shedlock does not lock anything?

### ISSUE THREAD

**Issue by alfonz19** [lukas-krecan/ShedLock#156]
I'm not sure if I'm doing something wrong or not, but this come as a surprise to me. Please advice.

I'm having schedlock enable as:

`@EnableSchedulerLock(defaultLockAtMostFor = "PT30S")`

and I have this scheduled method, just to verify that lock is created:

```
 @Transactional
    @Scheduled(cron = "* * * * * *", zone = "")
    @SchedulerLock(name = "readingFromSchedlock",
            lockAtLeastForString = "PT1S",
            lockAtMostForString = "PT1S")
    public void printShedlockTableContent() {
        try {
            Thread.sleep(500);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        log.info(String.format("currently existing shedlocks: %s", shedlockRepository.findAll()));
    }
```

which produces logging:

```
SomeClass : currently existing shedlocks: [ShedlockEntity(name=readingFromSchedlock, lockedBy=utu, lockUntil=2019-08-05 10:44:49.0, lockedAt=2019-08-05 10:44:48.012)]
SomeClass : currently existing shedlocks: [ShedlockEntity(name=readingFromSchedlock, lockedBy=utu, lockUntil=2019-08-05 10:44:50.0, lockedAt=2019-08-05 10:44:49.013)]
SomeClass : currently existing shedlocks: [ShedlockEntity(name=readingFromSchedlock, lockedBy=utu, lockUntil=2019-08-05 10:44:51.0, lockedAt=2019-08-05 10:44:50.001)]
```

Now, I'd like to enable multiple jobs to be running at the same time on one node, thus I need to create custom ThreadPool(why? I wanted to see, that lock is generated for scheduled job. So I needed 2 scheduled jobs, where one just looks into lock table if something is created or not). So we add this:

    @Override
    public void configureTasks(ScheduledTaskRegistrar scheduledTaskRegistrar) {
        ThreadPoolTaskScheduler threadPoolTaskScheduler = new ThreadPoolTaskScheduler();

        threadPoolTaskScheduler.setPoolSize(10);
        threadPoolTaskScheduler.setThreadNamePrefix("my-scheduled-task-pool-");
        threadPoolTaskScheduler.initialize();

        scheduledTaskRegistrar.setTaskScheduler(threadPoolTaskScheduler);
    }

no other change. No we run the app again, and the very same untouched scheduled method now logs:

```
SomeClass : currently existing shedlocks: []
SomeClass : currently existing shedlocks: []
SomeClass : currently existing shedlocks: []
```

No locking.

Changing initial configuration to:

`@EnableSchedulerLock(defaultLockAtMostFor = "PT30S", mode = EnableSchedulerLock.InterceptMode.PROXY_METHOD)`

seems to resolve this issue, but I'm not sure if it shouldn't work even with PROXY_SCHEDULER.

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/ShedLock/blob/master/README.md#modes-of-spring-integration

**Comment by alfonz19** [comment]
Sure I read it, that's why I knew that I can change the mode or proxying. However I don't get how it answers my question. Can you elaborate?

**Comment by lukas-krecan** [comment]
If you inject the ThreadPoolTaskScheduler directly to the registrar, there is no way how to proxy it (it is not a Spring bean)

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/ShedLock/issues/137

**Comment by lukas-krecan** [comment]
Alternatively, you can create ThreadPoolTaskScheduler bean and it will get automatically used by the scheduling framework

**Comment by alfonz19** [comment]
Thanks!
