### ISSUE TITLE
Task not execute use jdbc template

### ISSUE THREAD

**Issue by niezuxue** [lukas-krecan/ShedLock#1574]
If start java server first, and then create the lock table, all task will never execute. Because the table record only insert at the first time, and then add the lock key to LockRecordRegistry.lockRecords attribute. So if don't add the lock key to LockRecordRegistry.lockRecords attribute when inserting the lock table fails? thank you.

**Comment by lukas-krecan** [comment]
Can you please follow the issue template? I am especially interested in 

- ShedLock version being used
- Lock provvider being used
- DB engine being used

**Comment by niezuxue** [comment]
Shedlock version: 4.23.0
Lock provider: JdbcTemplateLockProvider
DB engine: mysql innodb

In StorageBasedLockProvider's doLock function, I think if `this.storageAccessor.insertRecord(lockConfiguration)` returns false, could throw  a system level exception to let developers know the error.
`protected boolean doLock(LockConfiguration lockConfiguration) {
        String name = lockConfiguration.getName();
        if (!this.lockRecordRegistry.lockRecordRecentlyCreated(name)) {
            if (this.storageAccessor.insertRecord(lockConfiguration)) {
                this.lockRecordRegistry.addLockRecord(name);
                return true;
            }

            this.lockRecordRegistry.addLockRecord(name);
        }

        return this.storageAccessor.updateRecord(lockConfiguration);
    }`

**Comment by lukas-krecan** [comment]
There is actually a code handling this unusual situation https://github.com/lukas-krecan/ShedLock/commit/4137d10779a1342c42cb31c6e9e606e706056b8e I wonder why it doesn't work in your case

**Comment by lukas-krecan** [comment]
Ah, I see. Can you please try to upgrade before wasting my time? Thanks

**Comment by niezuxue** [comment]
OK, I will upgrade.  And please be more patient, thanks.
