### ISSUE TITLE
can the jdbc provider customize the table name used ? 

### ISSUE THREAD

**Issue by kymtwyf** [lukas-krecan/ShedLock#158]
I would like to customize the shedlock table name in my db for some reason. But I find not way to do that, 

Would it be acceptable to provide a customizable field like:

```
shedlock.table=THE_SHEDLOCK_NAME_I_WISH
```

FOR SURE, it would be a problem if the table name for the same environment is changed.

**Comment by lukas-krecan** [comment]
Yes, check the LockProvider constructor
