### ISSUE TITLE
Job name template and parameter interpolation for @SchedulerLock (Spring)

### ISSUE THREAD

**Issue by hadimansuri** [lukas-krecan/ShedLock#1584]
**Is your feature request related to a problem? Please describe.**
We can only have a single name for jobs, no mater what parameters are passed. It's good to have name template and interpolate parameters 

**Describe the solution you'd like**
```
  @SchedulerLock(name = "my-job-#{tenantId}-#{date}")
  public void job(UUID tenantId, LocalDate date) {

  }
```

**Describe alternatives you've considered**
https://stackoverflow.com/a/14077831/5275087

**Comment by lukas-krecan** [comment]
It should work due to this https://github.com/lukas-krecan/ShedLock/pull/1298

**Comment by hadimansuri** [comment]
Hi @lukas-krecan Thank you very much for the quick reply.
It works.
It may be a good idea to add a usage sample [here](https://github.com/lukas-krecan/ShedLock#annotate-your-scheduled-tasks)
