### ISSUE TITLE
Option to throw exception if task not executed

### ISSUE THREAD

**Issue by hadimansuri** [lukas-krecan/ShedLock#1588]
**Is your feature request related to a problem? Please describe.**
Currently if it fails to acquire lock, the task is **ignored**.

Add a configuration option to **throw exception**.

**Describe the solution you'd like**
```
  @SchedulerLock(name = "my-job", throwException=true)
  public void job() {

  }
```
In case it fails to acquire lock throw an exception like `CouldNotAcquireLockException` ,...

**Describe alternatives you've considered**
Introduce a new `@DistributedLock` annotation

Current workaround: Make return type of the method `Optional`, in case task is not executed, the result will be an empty optional. the caller should throw an exception

**Additional context**
Distributed lock for long running operations triggered by users

**Comment by lukas-krecan** [comment]
You can implement it using [this](https://github.com/lukas-krecan/ShedLock#customization)
