### ISSUE TITLE
Allow only one job instance to run at a time

### ISSUE THREAD

**Issue by dineshgyl** [lukas-krecan/ShedLock#1596]
**Is your feature request related to a problem? Please describe.**
Currently I use lockAtLeastFor as PT5M and lockAtMostFor as PT2H for a job which is running every 5 mins.
if due to environment issues he job doesnt complete in 2hours ,second instance of the job is triggered.I want if teh job is running,no other instance should get triggered.

**Describe the solution you'd like**
Some parameter like allow only once instance to be run.

**Describe alternatives you've considered**
NONE

**Additional context**
NONE

**Comment by lukas-krecan** [comment]
You can try https://github.com/lukas-krecan/ShedLock#keepalivelockprovider
