### ISSUE TITLE
Missing jooq provider in the bom

### ISSUE THREAD

**Issue by MelleD** [lukas-krecan/ShedLock#1599]
I saw that the dependency is missing on the bom. 

```
         <dependency>
            <groupId>net.javacrumbs.shedlock</groupId>
            <artifactId>shedlock-provider-jooq</artifactId>
         </dependency>
```

Is there a reason for that?

**Comment by lukas-krecan** [comment]
Thanks, most likely just an omission. Will fix it

**Comment by lukas-krecan** [comment]
Fixed in https://github.com/lukas-krecan/ShedLock/commit/d3b53be48f98edc3aea9d3507ff8e56a40ca18f8

**Comment by MelleD** [comment]
Cool thanks :)
