### ISSUE TITLE
java.lang.AbstractMethodError: org.springframework.boot.context.config.ConfigFileApplicationListener.supportsSourceType(Ljava/lang/Class;)Z on ShedLock  v2.5.0 and Spring-boot v2.1.1.RELEASE

### ISSUE THREAD

**Issue by gtludwig** [lukas-krecan/ShedLock#161]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

**Describe the bug**
1. Which version do you use
2.5.0
2. Which Lock Provider
        <dependency>
            <groupId>net.javacrumbs.shedlock</groupId>
            <artifactId>shedlock-spring</artifactId>
            <version>${shedlock.version}</version>
        </dependency>
        <dependency>
            <groupId>net.javacrumbs.shedlock</groupId>
            <artifactId>shedlock-provider-jdbc-template</artifactId>
            <version>${shedlock.version}</version>
        </dependency>
3. ShedLock configuration
4. ShedLock logs

**Expected behavior**
This application has 70+tests and 44 fail with the error:
java.lang.AbstractMethodError: org.springframework.boot.context.config.ConfigFileApplicationListener.supportsSourceType(Ljava/lang/Class;)Z

When using spring-boot v2.1.0+.RELEASE and ShedLock 2.4.0 or 2.5.0 most of the tests fail. If using any other version of ShedLock and spring-boot up to v2.0.9.RELEASE, all the test are green. Our microservices are built on spring-boot v2.1.1.RELEASE. And due to this error, we're keeping this microservice in a different spring-boot MINOR version.

Is there any compatibility table somewhere and/or a fix for this?

**Actual behavior**
What happened instead.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Can you please provide full stack trace?

**Comment by lukas-krecan** [comment]
It seems like some dependency conflict most likely unrelated to ShedLock. Here is a test of ShedLock with SpringBoot 2.1.2. I would recommend to check you dependency tree or this issue https://github.com/spring-projects/spring-boot/issues/15020

**Comment by lukas-krecan** [comment]
You can try 2.6.0 which has dependency on Spring 2.1.x. You will still have version clash in your Maven (oe Gradle) config, but maybe it will help

**Comment by sayantansinha** [comment]
@gtludwig were you able to get a solution for this?

**Comment by wangdadongGithub** [comment]
> 您可以尝试2.6.0，它依赖于Spring 2.1.x。您的 Maven (oe Gradle) 配置中仍然会存在版本冲突，但也许它会有所帮助

Spring 2.1.x 对应 2.6.0，测试正常
