### ISSUE TITLE
[bug] scheduler stopped after few times running

### ISSUE THREAD

**Issue by letrthang** [lukas-krecan/ShedLock#1611]
spring-boot 2.7.17
shedlock-spring 5.10.0
Java 17
DB: Redis

==== code ====

  ```
  @Scheduled(fixedRate = 2 * 60 * 1000, initialDelay = 1 * 60 * 1000)
    @SchedulerLock(name = "schedulerTestLock",
            lockAtMostFor = "PT60M", // max 60 minutes
            lockAtLeastFor = "PT1M" // min 1 minutes
    )
    public void testMethod() { }
```

========== config ========

```
@Configuration
@EnableSchedulerLock(defaultLockAtMostFor = "PT60M", defaultLockAtLeastFor = "PT1M")
public class ShedLockConfig {

    @Bean
    public LockProvider lockProvider(RedisConnectionFactory redisConnectionFactory) {
        return new RedisLockProvider(redisConnectionFactory);
    }
}
```

After 5-6 times running method **testMethod** , scheduler stopped. There is no exception or error message showed.

**Comment by lukas-krecan** [comment]
Have you checked the logs? Who do they say?

**Comment by letrthang** [comment]
the log not show anything. i put try catch but no exception happens.
```

public void testMethod() { 
try {
            LOG.debug("start notify ");

.....
  LOG.debug("end notify ");
catch (Exception e) {
            e.printStackTrace();
        }
```

log shows debug: "start notify" and "end notify " exactly 5 times each. And no more. 

the Redis lock data also was cleaned up after scheduler stopped. Below image is normal in redis DB:

<img width="910" alt="image" src="https://github.com/lukas-krecan/ShedLock/assets/13396193/354cf235-3d9a-474f-abc2-5ad95c5d04a8">

Not sure SchedulerLock issue or Spring boot issue.

**Comment by letrthang** [comment]
I tested with 

> spring-boot 2.7.15
> shedlock-spring 5.10.0

also not working

**Comment by letrthang** [comment]
this is not shedlock issue. i did wrong config for scheduling.

i need to set: **spring.task.scheduling.pool.size** > 1

i close this issue.

**Comment by tushar-meesho** [comment]
@letrthang  why will it stop even if the `spring.task.scheduling.pool.size = 1` which is the default value
