### ISSUE TITLE
Version compatibility matrix for Shedlock (shedlock-spring) and Spring

### ISSUE THREAD

**Issue by eldarj** [lukas-krecan/ShedLock#1619]
**Is your feature request related to a problem? Please describe.**
There is no clear way to understand what Shedlock version is best suited for a given Spring version. Specifically `shedlock-spring`

**Describe the solution you'd like**
Document a version compatibility matrix

**Describe alternatives you've considered**
Going through each Shedlock version and checking compile dependencies for anything Spring e.g. `spring-context`

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/ShedLock#versions

**Comment by eldarj** [comment]
I am aware of that guidline, however it rather seems quite broad. Is there anything more specific? Or that's it - use 5.X.X if you are on JDK>17 and Spring 6, otherwise 4.x.x? 

I'd be willing to contribute if there is no documented matrix right now.

**Comment by lukas-krecan** [comment]
Feel free to send a PR. But basically it's as you said.
