### ISSUE TITLE
JDBCTemplate lockprovider will insert on existing row everytime when application start

### ISSUE THREAD

**Issue by Lynnes001** [lukas-krecan/ShedLock#1631]
I am using shedlock 5.10.0 on a jdbctemplate lockprovider. The config is pretty much default.

```java
@Bean
    public LockProvider lockProvider(DataSource dataSource) {
        return new JdbcTemplateLockProvider(
                JdbcTemplateLockProvider.Configuration.builder()
                        .withTableName("SB_SAC_SCHEMA_SHEDLOCK")
                        .withJdbcTemplate(new JdbcTemplate(dataSource))
                        .build()
        );
    }
```

I use it in a *Locking without a framework* way because I need to switch datasource everytime before running the job.`lockProvider` in the following code is autowired.

```java
LockingTaskExecutor executor = new DefaultLockingTaskExecutor(lockProvider);
            executor.executeWithLock((Runnable) () -> {
                // Real tenant-specific job content
                LockAssert.assertLocked();
// real job
            }, new LockConfiguration(Instant.now(), "JOB-"+tenantId, Duration.ofSeconds(LOCK_DURATION), Duration.ofSeconds(LOCK_DURATION)));
```

**Describe the bug**

I see logs like
```
Caused by: com.sap.db.jdbc.exceptions.SQLIntegrityConstraintViolationExceptionSapDB: [301]: unique constraint violated: Table(SHEDLOCK), Index(_SYS_TREE_CS_#200580_#0_#P0) with error: unique constraint violation on pos=0 for table H00::C4A1D03AE912425890071A2D25E6286F:SB_SAC_SCHEMA_SHEDLOCK$delta_1$en, key: NAME=JOB-b8016adb-35c4-42ad-99bd-2cc06f3309b9 already exists as udiv=70; indexname=_SYS_TREE_CS_#200580_#0_#P0
```

I realize it's because the existing row, and jdbctemplate is using `insert` and `update` (please correct me if I'm wrong). 
And I did notice there are some issues related to this. I am wondering if there is a way to avoid having such error logs. Or there is a way to let it use upsert? maybe?

Thanks.

**Comment by lukas-krecan** [comment]
We are catching the exception, but some DB drivers decide to log it anyway. For standard DBs we are using upsert when you have `useDbTime` on. But for SAP we definitely do not have anything like this. If you want, you can add SAP to `SqlStatementsSource` and send a PR.
