### ISSUE TITLE
Shedlock doesn't automatically create the table

### ISSUE THREAD

**Issue by eldarj** [lukas-krecan/ShedLock#1642]
Not a bug report, but rather just a question - because there is some confusion about this. 

Many resources state that Shedlock runs without having to manually create a table, but they also state that if for some reason it does not, then you should debug, check what user is used, check privileges, roles, etc. - otherwise just create it manually.

So, can it run without a pre-created table?

I am aware that the docs state that you should indeed create a table, but was it ever the case that shedlock was creating tables on its own, in previous versions?

If not, would this be viable? It already has everything needed, it also knows what the underlying db is, it would just need to run a create if not exists.

Versions used: latest
`shedlock-spring` and `shedlock-provider-jdbc-template`

**Comment by lukas-krecan** [comment]
In JDBC it always required you to create the table (it is different in other providers like Mongo or Jedis).

In rational databases it's more complicated
1. People usually are creating the schema using Liqubase or Flyway
2. DDL differs between different databases. It's solvable, but quite a lot of complexity for little gain
3. Sometimes the user used in DB connection does not have permissions to create tables.

So while it's feasible, I never thought it was worth the hassle.

**Comment by matzschmanski** [comment]
sorry for commenting in this old thread, i was hesitating to create a new issue…

is there a warning thrown when the table does not exist?
As far as i have seen (in my rather quick and not in depth check), it is only checked for tableName not Null in AbstractJdbcStorageAccessor ?
