### ISSUE TITLE
ShedLock not lock when Sleuth is present

### ISSUE THREAD

**Issue by nekperu15739** [lukas-krecan/ShedLock#168]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

We have an application that use ShedLock, and in same app have config spring-cloud-sleuth, however, by default lock doesnt work because on class SpringLockConfigurationExtractor expect an instance of ScheduledMethodRunnable. I add the question to  stackoverflow  here:

[https://stackoverflow.com/questions/58973889/shedlock-not-lock-when-sleuth-is-present/58978881#58978881](url)

For now we set the intercept to proxy-method and its working, however, we dont know if this change will have side effects.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Proxy-method will indeed fix the issue for you (it's described at the end of the documentation, there should not be any unintended side effects) In fact, I will most likely make it the default option, to prevent issues like the one you have encountered.

**Comment by lukas-krecan** [comment]
Version 4.0.0 uses PROXY_METHOD by default. Unfortunately, there is no other way I can work around Sleuth.
