### ISSUE TITLE
Hibernate jpamodelgen doesn't work on SpringBoot 2 if Shedlock version greater 2.x version

### ISSUE THREAD

**Issue by eg-sibirev** [lukas-krecan/ShedLock#1686]
SpringBoot version 2.7.17
Java version 17
Hibernate version 5.6.15 final
Maven compile plugin 3.8.1

While compiling project hibernate meta models doesn't generated. There is an error "cannot find symbol".
If I use shedlock 2.x, all ok.

**Comment by lukas-krecan** [comment]
Hi, there is not much I can help you with. I guess ShedLock includes some dependency that trips Hibernate generator. You can list the dependencies before and after the upgrade and check the difference.

**Comment by eg-sibirev** [comment]
Sorry. Problem is solved.  There is no problem, only my inattention while increasing shedlock version from 2.x to 4.x
