### ISSUE TITLE
Enable similar tasks with different parameter to run parallel

### ISSUE THREAD

**Issue by truj** [lukas-krecan/ShedLock#1726]
**I have the following scenario:**

Different applications send requests to my service. My service broadcasts these requests to different target servers.

That's what my service should do:

**Step 1**:
The request is saved to a DB table - one record for each target server (see the table below).

| Request    | Target Server |
| -------- | ------- |
| Create User 'James' | ldap://target1.example.com |
| Create User 'James' | ldap://target2.example.com |
| Delete User 'Joe' | ldap://target1.example.com |
| Delete User 'Joe' | ldap://target2.example.com |

**Step 2**:
A background process reads all records for one target server, sends them to the server and then deletes the records from the DB.

**Important**:
There should be only one background process per target server.
But different target servers should be addressed in parallel.

Normally this could be done like this:
```
@Scheduled(...)
@SchedulerLock(name = "target1")
public void myTask1() {
    process("target1");
}

@Scheduled(...)
@SchedulerLock(name = "target2")
public void myTask2() {
    process("target2");
}
```

**Problem:**
The target servers should be configurable (with an array of server names in Spring's **application.properties**).
So there could be 2, 4 or 100 target servers.
But @SchedulerLock(name = "...") can only have one task name.

**Solution:**
Maybe with additional parameters.
However I'm not sure if this is possible...
```
@Value("...")
private List<String> targetServers;  // injected from configuration (e.g. application.properties)

@SchedulerLock(name = "target", onceForEach = targetServers)
public void myTask(String targetServer) {
    process(targetServer);
}
```

**Comment by lukas-krecan** [comment]
Hi, all annotations support SpEL so it should work

**Comment by lukas-krecan** [comment]
Hi, there are two parts of your problem. How to schedule 100 parallel tasks. This is not related to ShedLock, I think you can schedule the tasks using Spring or JVM scheduler. The locking can be either done using ShedLock SpEL support, or [this](https://github.com/lukas-krecan/ShedLock#locking-without-a-framework)

**Comment by truj** [comment]
Yes, the main problem is scheduling.
I don't think that SpEL would help me in this use case. But it should be solvable with your [other solution](https://github.com/lukas-krecan/ShedLock#locking-without-a-framework).
Thank you for the suggestion.
