### ISSUE TITLE
Some way to reset locks in tests

### ISSUE THREAD

**Issue by waschmittel** [lukas-krecan/ShedLock#174]
We'd like to use the (sane) default of PROXY_METHOD instead of PROXY_SCHEDULER.
This is currently not possible because we have some acceptance tests that execute scheduled tasks by directly calling the @Scheduled methods.

The tests basically look like this

```gherkin
@Given some precondition
@When some nightly scheduled job runs
@Then something should have happened
```

These tests will fail for us if we set lockAtLeastFor to (for example) 10 minutes.

They fail because the second step will do nothing if
* PROXY_METHOD is used
* that second step is used in multiple scenarios or tests are run in <10min intervals (in our example)

**The solution we'd like**
It would be nice if there was a way to programmatically reset the scheduler locking in tests (so we can effectively use this in a precondition). 

**Alternatives we've considered**
We can
* stay with PROXY_SCHEDULER
* delegate what the @Scheduled method does to another method

But it feels nicer to just drop in @SchedulerLock and stick to the defaults.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. 

The best option is to configure lockAtLeastForString using Spring properties (you can use SPEL expression in lockAtLeastForString annotation attribute like [this](https://github.com/lukas-krecan/ShedLock/blob/master/spring/shedlock-springboot-test/src/main/java/net/javacrumbs/shedlock/test/boot/ScheduledTasks.java#L29)) and set it to 0 for tests.
