### ISSUE TITLE
ScheduleLock doesn't support SPEL with Spring references from v5.1.0

### ISSUE THREAD

**Issue by davidmestr** [lukas-krecan/ShedLock#1753]
With this PR #1298, a SPEL that works before, now is not working:

The next configuration:
```java
@SchedulerLock(name = "#{shedlockCouchbaseDataSource.getAvailabilityShedlockName()}", lockAtMostFor = "120m", lockAtLeastFor = "1m")
```
where `shedlockCouchbaseDataSource` is a Spring bean with a public method: `getAvailabilityShedlockName()`

was working with version 4.43.0 (until 5.0.1),
but from 5.1.0 doesn't work any more.

Until v5.0.1, [SpringLockConfigurationExtractor.getName()](https://github.com/lukas-krecan/ShedLock/blob/66ea116a352f31d250d986bc3dbdfb0cea18a944/spring/shedlock-spring/src/main/java/net/javacrumbs/shedlock/spring/aop/SpringLockConfigurationExtractor.java#L95) was resolved by `org.springframework.util.StringValueResolver` implemented by `org.springframework.beans.factory.config.EmbeddedValueResolver` that uses `org.springframework.context.expression.StandardBeanExpressionResolver`. It is work fine.

But, from v5.1.0, the [SPEL implementation](https://github.com/lukas-krecan/ShedLock/blob/66ea116a352f31d250d986bc3dbdfb0cea18a944/spring/shedlock-spring/src/main/java/net/javacrumbs/shedlock/spring/aop/SpringLockConfigurationExtractor.java#L115) delegates into `org.springframework.expression.spel.support.SimpleEvaluationContext`, that doesn't support beans references.

In **SimpleEvaluationContext javadoc**:

> 
> A basic implementation of EvaluationContext that focuses on a subset of essential SpEL features and customization options, targeting simple condition evaluation and in particular data binding scenarios.
> In many cases, the full extent of the SpEL language is not required and should be meaningfully restricted. Examples include but are not limited to data binding expressions, property-based filters, and others. To that effect, **SimpleEvaluationContext is tailored to support only a subset of the SpEL language syntax, e.g. excluding references to Java types, constructors, and bean references.**
> 

**Expected behavior**
A schedulerlock must be created with name returned by shedlockCouchbaseDataSource.getAvailabilityShedlockName()

**Actual behavior**
An exception is launched:
```
2024-02-05 17:01:45,983 [availability-scheduler1] ERROR com.xxx.yyy.config.ShedlockConfiguration - Scheduled task threw an exception: EL1007E: Property or field 'shedlockCouchbaseDataSource' cannot be found on null
org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'shedlockCouchbaseDataSource' cannot be found on null
```

**Comment by lukas-krecan** [comment]
Hi, I have added a test for it [here](https://github.com/lukas-krecan/ShedLock/pull/1757/files#diff-5cc19a2bbc0937d65d396674e9ff39d805689b194d81713a55ee6a03e4ca8ca4R26) and it works as expected. What am I missing?

**Comment by lukas-krecan** [comment]
Btw. the `embeddedValueResolver` is still used [here](https://github.com/lukas-krecan/ShedLock/blob/66ea116a352f31d250d986bc3dbdfb0cea18a944/spring/shedlock-spring/src/main/java/net/javacrumbs/shedlock/spring/aop/SpringLockConfigurationExtractor.java#L98).

**Comment by davidmestr** [comment]
> Hi, I have added a test for it [here](https://github.com/lukas-krecan/ShedLock/pull/1757/files#diff-5cc19a2bbc0937d65d396674e9ff39d805689b194d81713a55ee6a03e4ca8ca4R26) and it works as expected. What am I missing?

I don't understand. I am checking this test.

**Comment by davidmestr** [comment]
> Hi, I have added a test for it [here](https://github.com/lukas-krecan/ShedLock/pull/1757/files#diff-5cc19a2bbc0937d65d396674e9ff39d805689b194d81713a55ee6a03e4ca8ca4R26) and it works as expected. What am I missing?

In our case, we don't use @Schedule (the task is scheduled by code) and we have parameters in the method.

```java
@SchedulerLock(name = "#{shedlockCouchbaseDataSource.getAvailabilityShedlockName()}", lockAtMostFor = "120m", lockAtLeastFor = "1m")
public void execute(final String param1) {
...
}
```

Then `embeddedValueResolver` is not executed because it fails before in parseSpel (getEvaluationContext doesn't return an optional empty)

**Comment by lukas-krecan** [comment]
Cool, I will look into that. Thanks

**Comment by lukas-krecan** [comment]
Fixed in 5.11.0

**Comment by davidmestr** [comment]
Thank you @lukas-krecan

**Comment by uyw4687** [comment]
@lukas-krecan I'm using Spring Boot 2 thus it seems I need to use 4.x.x but I need this feature of using parameter to lock name. Will it be supported in 4.x.x?

**Comment by lukas-krecan** [comment]
If I am not mistaken, it works in older versions of ShedLock. This ticket is about the fact that it was broken in 5.0.1
