### ISSUE TITLE
Two invocations instead of one: Lock failure within a split-second

### ISSUE THREAD

**Issue by saimonsez** [lukas-krecan/ShedLock#177]
**Describe the bug**
1. Which version do you use: 3.0.0
2. Which Lock Provider: Hazelcast
3. ShedLock configuration:
`@Scheduled(cron = "0 */5 * * * *")`
`@SchedulerLock(name = "some-unique-lock-name", lockAtLeastFor = 1_000, lockAtMostFor = 30_000)`
4. ShedLock logs: unfortunately none, just business logs.

**Expected behavior**
Only one Scheduler should run at every 5th minute as configured by cron.

**Actual behavior**
Running 3 Spring Boot nodes with enabled schedulers (see above) and 3 Hazelcast nodes I do see two invocations of a particular scheduler with these timestamps:

11.12.19 03:00:00,472
11.12.19 03:00:00,433

So far, this happened only once. But I am a bit uneasy regarding this issue. I am perfectly aware that this might be a issue of Hazelcast and distributed locking is super-hard to do. However, it looks like a bug. Is there any of workaround for this?

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I understand your concern, but I am afraid I can not do much about it without more information (like Shedlock debug logs). You can check HazelcastLockProvider source code, it looks correct and without some further clue about the issue, I do not know where to start looking.

**Comment by saimonsez** [comment]
Thank you! I will report back with debug logs, as soon as possible. This might take some time. 

Your Hazelcast implementation looks fine to me. Just wondering if I could do some sort of double checked locking. Is this possible?
