### ISSUE TITLE
Question: any way to minimize the log OR increase the 1sec period for acquiring the lock?

### ISSUE THREAD

**Issue by icougil** [lukas-krecan/ShedLock#1791]
Hi!

We're using the latest version (5.11.0) with SpringBoot and we'd like to minimize the amount of "noise" ShedLock is introducing in our logs. 

If we understood correctly, ShedLock tries to acquire the lock every second (1 sec), and therefore, even if we schedule our task to be executed any minutes later, for example, 10 minutes, it will start "wasting" time, trying to acquire a lock that won't happen after a lot of executions (60 seconds * 9 minutes at most?).

So the question is, is there any way to customize/setup how often ShedLock tries to acquire the lock? For example, in our case, we don't need to execute "the next try" until at least 1 minute (in fact, it should depend on the _"atLeast"_ annotation, isn't it?).

If not, is there any way to minimize the amount of logs ShedLock produces? (we're relying on the JdbcTemplate, and therefore we're using it to write all our queries into the log, but we don't want to see there the ShedLock ones).

1. Version: 5.11.0
2. Provider: JdbcTemplate + DbTime
3. Logs
 
```
10:40:19.015 DEBUG [pool-thread-2] n.j.s.c.DefaultLockingTaskExecutor - Not executing 'ourTask'. It's locked.
10:40:20.006 DEBUG [pool-thread-2] o.s.jdbc.core.JdbcTemplate - Executing prepared SQL update
10:40:20.006 DEBUG [pool-thread-2] o.s.jdbc.core.JdbcTemplate - Executing prepared SQL statement [UPDATE shedlock SET lock_until = timezone('utc', CURRENT_TIMESTAMP) + cast(? as interval), locked_at = timezone('utc', CURRENT_TIMESTAMP), locked_by = ? WHERE shedlock.name = ? AND shedlock.lock_until <= timezone('utc', CURRENT_TIMESTAMP)]
10:40:20.006 TRACE [pool-thread-2] o.s.jdbc.core.StatementCreatorUtils - Setting SQL statement parameter value: column index 1, parameter value [540000 milliseconds], value class [java.lang.String], SQL type unknown
10:40:20.006 TRACE [pool-thread-2] o.s.jdbc.core.StatementCreatorUtils - Setting SQL statement parameter value: column index 2, parameter value [our-machine], value class [java.lang.String], SQL type unknown
10:40:20.006 TRACE [pool-thread-2] o.s.jdbc.core.StatementCreatorUtils - Setting SQL statement parameter value: column index 3, parameter value [ourTask], value class [java.lang.String], SQL type unknown
10:40:20.008 TRACE [pool-thread-2] o.s.jdbc.core.JdbcTemplate - SQL update affected 0 rows
10:40:20.015 DEBUG [pool-thread-2] n.j.s.c.DefaultLockingTaskExecutor - Not executing 'ourTask'. It's locked.
10:40:21.007 DEBUG [pool-thread-2] o.s.jdbc.core.JdbcTemplate - Executing prepared SQL update
10:40:21.007 DEBUG [pool-thread-2] o.s.jdbc.core.JdbcTemplate - Executing prepared SQL statement [UPDATE shedlock SET lock_until = timezone('utc', CURRENT_TIMESTAMP) + cast(? as interval), locked_at = timezone('utc', CURRENT_TIMESTAMP), locked_by = ? WHERE shedlock.name = ? AND shedlock.lock_until <= timezone('utc', CURRENT_TIMESTAMP)]
10:40:21.007 TRACE [pool-thread-2] o.s.jdbc.core.StatementCreatorUtils - Setting SQL statement parameter value: column index 1, parameter value [540000 milliseconds], value class [java.lang.String], SQL type unknown
10:40:21.007 TRACE [pool-thread-2] o.s.jdbc.core.StatementCreatorUtils - Setting SQL statement parameter value: column index 2, parameter value [our-machine], value class [java.lang.String], SQL type unknown
10:40:21.007 TRACE [pool-thread-2] o.s.jdbc.core.StatementCreatorUtils - Setting SQL statement parameter value: column index 3, parameter value [ourTask], value class [java.lang.String], SQL type unknown
10:40:21.013 TRACE [pool-thread-2] o.s.jdbc.core.JdbcTemplate - SQL update affected 0 rows
10:40:21.020 DEBUG [pool-thread-2] n.j.s.c.DefaultLockingTaskExecutor - Not executing 'ourTask'. It's locked.
```

**Expected behavior**
We'd like to either customize how often ShedLock tries to acquire the lock and/or exclude writing the execution of each query from ShedLock via JdbcTemplate

**Actual behavior**
ShedLock is trying to acquire a lock that will not happen until a huge amount of time (depending on the _"atMost"_ and the _"atLeast"_ values)

**Comment by lukas-krecan** [comment]
Hi,

1. ShedLock only tries to lock when a task is supposed to be executed. So if your tasks is supposed to run every second, shedlock will check the lock every second.
2. You can hide the logs by configuring your logging library.

**Comment by lukas-krecan** [comment]
1. Honestly, I do not know. Unless you are using KeepAliveLockProvider, ShedLock only tries to aquire the lock when a task is supposed to be executed. There is no scheduling, no threads, nothing, just an AOP wrapper around your method trying to aquire/release the lock.
2. You are right

**Comment by icougil** [comment]
ouchhh! 
I think we found the issue: it was related to the `cron` expression we put in our scheduled task. Notice the `0` for identifying instead of every second `*`:

`@Scheduled(cron = "0 */3 * * * *")`
(the good one)

vs

`@Scheduled(cron = "* */3 * * * *")`
(the bad one)

😅
