### ISSUE TITLE
Enable lower case for database type when using usingDbTime()

### ISSUE THREAD

**Issue by yuagu1** [lukas-krecan/ShedLock#1800]
**Is your feature request related to a problem? Please describe.**
We have a very special use case where the database metadata are override with lower case. 
E.X `ORACLE` becomes `oracle`, `MySQL` becomes `mysql`
That leads `net.javacrumbs.shedlock.provider.jdbctemplate.SqlStatementsSource.java.create()` always return 

> UnsupportedOperationException "DB time is not supported for 'oracle'"

We are on jdk1.8 so we are using 4.44

**Describe the solution you'd like**
We would like to have a patch on 4.44.0 where 
`String databaseProductName = getDatabaseProductName(configuration);`
is updated to 
`String databaseProductName = getDatabaseProductName(configuration).toLowerCase();`
and in all the switch-case block, all Database type to be changed into lower case;
For example:
`case "MySQL":` turns to case `"mysql":`
Thanks.

**Comment by lukas-krecan** [comment]
Something like [this](https://github.com/lukas-krecan/ShedLock/pull/1806/)?

**Comment by yuagu1** [comment]
Hello @lukas-krecan , thank you so much! This is exactly what we are looking for? To use this latest update aginst 4.44, would you please suggest how should we update our maven pom file?

**Comment by lukas-krecan** [comment]
Can you please send a PR to the `v4` branch?

**Comment by yuagu1** [comment]
Hello @lukas-krecan , please let me know when it's get released. Thanks

**Comment by lukas-krecan** [comment]
Released as 4.47.0, may take some time until it's visible in Maven central
