### ISSUE TITLE
Startup error with Neo4j 5.17.0

### ISSUE THREAD

**Issue by ilgrosso** [lukas-krecan/ShedLock#1804]
**Describe the bug**
1. Which version do you use: 5.11.0
2. Which Lock Provider: Neo4j

With Spring bean definition as from the docs:

```java
@Bean
Neo4jLockProvider lockProvider(org.neo4j.driver.Driver driver) {
    return new Neo4jLockProvider(driver);
}
```

we get the following startup error:

```
Error creating bean with name 'lockProvider' defined in org.apache.syncope.core.persistence.neo4j.PersistenceContext: Failed to instantiate [net.javacrumbs.shedlock.provider.neo4j.Neo4jLockProvider]: Factory method 'lockProvider' threw exception with message: Invalid constraint syntax, ON and ASSERT should not be used. Replace ON with FOR and ASSERT with REQUIRE. (line 1, column 1 (offset: 0))
"CREATE CONSTRAINT UNIQUE_shedlock_name IF NOT EXISTS ON (lock:shedlock) ASSERT lock.name IS UNIQUE"
```

The fix should go onto `net.javacrumbs.shedlock.provider.neo4j.Neo4jStorageAccessor.createLockNameUniqueConstraint()` but that method is unfortunately private.

**Comment by lukas-krecan** [comment]
Hi, thanks for reporting. If you send a PR, I will be happy to merge it and release it. Is it due to a new version of Neo4j or what's the cause of the issue?

**Comment by ilgrosso** [comment]
>  Is it due to a new version of Neo4j?

@lukas-krecan exactly: the current syntax used to work with Neo4j 4.4, some small adjustments are needed to work with Neo4j 5 - see for example https://towardsdatascience.com/how-cypher-changed-in-neo4j-v5-d0f10cbb60bf#943a

**Comment by lukas-krecan** [comment]
Cool, I actually have the PR ready so no need to do anything from your side. Thanks

**Comment by ilgrosso** [comment]
Ah even better, thank you!

Question: are SNAPSHOTs published somewhere?

**Comment by lukas-krecan** [comment]
No, but I usually release a new version every time there is a significant change
