### ISSUE TITLE
Any chance to open up StorageBasedLockProvider?

### ISSUE THREAD

**Issue by ilgrosso** [lukas-krecan/ShedLock#1821]
In `StorageBasedLockProvider` the method `doLock()` is `protected`, which suggests that the method could have override in subclasses; yet, `storageAccessor` and `lockRecordRegistry` are set as `private`.

Any chance to make those two fields as `protected` as well?

**Comment by ilgrosso** [comment]
Rationale: I have a use case where it is needed to manually (e.g. without annotations) check if lock can be obtained, to determine whether the task with given name is actually running or not.
In such scenario, time-based conditions as `lockAtMostFor` / `lockAtLeastFor` do not have much sense.

**Comment by lukas-krecan** [comment]
Hi, can you please explain how would you acive it if we were to open `storageAccessor` and `lockRecordRegistry`? I do not see how it would help.

**Comment by ilgrosso** [comment]
The idea would to override `StorageBasedLockProvider#doLock` as follows:

```java
            @Override
            protected boolean doLock(final LockConfiguration lockConfiguration) {
                storageAccessor.insertRecord(lockConfiguration);
            }
```

in order to obtain the desired behavior.

I have realized, however, that, because of the scenario above, ShedLock is probably overkill, so I am going to build something simpler.

Thank you anyway for your attention.
