### ISSUE TITLE
Running multiple tasks on different instances using JDBC lock provider

### ISSUE THREAD

**Issue by Harshit-Shrivastava** [lukas-krecan/ShedLock#183]
Hi @lukas-krecan ,

What is `[locked_by] [varchar](255) NOT NULL` field in the table for the JDBC implementation? Is it possible to set this to an `instance name` or `node name` from the application, or make it a composite key (alongside `[name] [varchar](64) NOT NULL` field)?

I guess I am exploring to see the option where 2-3 tasks are using ShedLock (different lock name for each task) in a 4+ node environment and making sure that not all tasks are running on the same node (CPU/memory/load consideration)

**Comment by lukas-krecan** [comment]
Hi, this is not a feature that ShedLock supports out of the box.

If you are able to figure out naming scheme that would satisfy you requirements, you can generate task names dynamically using Spring Expression language in the annotation. In other words, you can add instance name to the name of the task in the runtime.

If you need something more complex, you can always implement your own lock provider.

**Comment by Harshit-Shrivastava** [comment]
Hi,
Thanks for your response. Just a follow up question around the same:-
Is it possible know if this node acquiring lock for task A does not already have a lock for tasks B or C, etc. is all the locks for tasks A, B, C, etc. are via ShedLock?
Appreciate your response :)

**Comment by lukas-krecan** [comment]
For that you would have to implement a custom LockProvider. But I think it would be better to use some job scheduler like Quartz
