### ISSUE TITLE
Seeing "JdbcTemplateLockProvider cannot be resolved to a type" for version 5.12.0

### ISSUE THREAD

**Issue by agravell047** [lukas-krecan/ShedLock#1831]
Using version 5.12.0, there is no "provider" package that allows me to import JdbcTemplateLockProvider. The documentation says to import like this: `import net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateLockProvider;`, but when I try this, it says it can't be resolved. All I've done so far is add the package to my project and try to set up a new bean for it.

**Comment by lukas-krecan** [comment]
Have you included the dependency? The provider is here https://github.com/lukas-krecan/ShedLock/blob/master/providers%2Fjdbc%2Fshedlock-provider-jdbc-template%2Fsrc%2Fmain%2Fjava%2Fnet%2Fjavacrumbs%2Fshedlock%2Fprovider%2Fjdbctemplate%2FJdbcTemplateLockProvider.java

**Comment by agravell047** [comment]
Yes, I've included:
```
<dependency>
    <groupId>net.javacrumbs.shedlock</groupId>
    <artifactId>shedlock-spring</artifactId>
    <version>5.12.0</version>
</dependency>
```

**Comment by lukas-krecan** [comment]
Ok, in that case, please read the documentation once more.

**Comment by agravell047** [comment]
@lukas-krecan I don't think its an issue with readings the directions as I've done that. Is there anything I could have missed that would add that package here? It just seems to be missing in version 5.12.0.
![Screenshot 2024-03-11 at 4 02 40 PM](https://github.com/lukas-krecan/ShedLock/assets/146013972/14239f8c-b7c3-4cf5-8e70-8e8160e9ef3e)

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/ShedLock?tab=readme-ov-file#jdbctemplate
