### ISSUE TITLE
Knowledge of locks acquired by node

### ISSUE THREAD

**Issue by Harshit-Shrivastava** [lukas-krecan/ShedLock#184]
Hi @lukas-krecan 

I have been going thorough ShedLock and found it to be an excellent library for mutual exclusion of tasks across nodes. I had some questions which I could not find in the documentation:-

1. Is there a way or an API in ShedLock that lets application running on a node have the knowledge of what all locks are acquired on this node via ShedLock?
2. Is there a way to configure ShedLock such that if a node has one lock (lockA), it does not request for another lock (lockB)?
3. Is there an option/configuration to disable the in-memory cache feature of ShedLock?
4. Is there also an option in ShedLock to share taskload across nodes via lock? (Example: an application has 3 tasks, A, B, C locked via ShedLock, locknames lockA, lockB, lockC - Is there a way to make sure that one node does not acquire more than one lock out of above 3?)
5. Does ShedLock provide an admin API feature to release all locks in case if required?

Would really appreciate your answers to above questions. Looking forward to hearing from you soon. Thanks in advance.

-Harshit

**Comment by lukas-krecan** [comment]
Hi, ShedLock does not support any of those features. You can implement all of the above yourself. If you are using JdbcTemplateLockProvider, it should be quite easy. As a side note, the in-memory cache caches only the fact that lock with such name already exists, if you do not delete rows in the ShedLock table but just update them, you do not have to clear or bypass the cache.

**Comment by Harshit-Shrivastava** [comment]
Thanks @lukas-krecan for your response.
How is the `locked_by` field populated in JdbcTemplateLockProvider? Where does ShedLock get that value from?

**Comment by lukas-krecan** [comment]
`locked_by` is a hostname. Just check the source code of `JdbcTemplateStorageAccessor`.
