### ISSUE TITLE
Support UTC values for date columns

### ISSUE THREAD

**Issue by gerasimovv88** [lukas-krecan/ShedLock#185]
Hi! 
That would be great if you can save data for locked_at, lock_until as a UTC date instead of local date. Can i do it now? I think, now it's impossible without reimplementing the LockProvider.
Thank you!

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Please check the implementation https://github.com/lukas-krecan/ShedLock/blob/master/providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/JdbcTemplateStorageAccessor.java By default it uses UTC time, but if you have some strange configuration, you can set Timezone using Configuration parameter

**Comment by gerasimovv88** [comment]
You are right! I missed this property. 
Thank you!
Can be closed
