### ISSUE TITLE
How to modify the contents of ' locked_by ' param when i use Mysql provider?

### ISSUE THREAD

**Issue by PeppaLittlePig** [lukas-krecan/ShedLock#186]
Currently, the users on the 3 servers are all call “Ubuntu“, which results in the “ locked_by “ field in the Mysql table being the same. Is there a way to distinguish between different servers and the same user?

**Comment by PeppaLittlePig** [comment]
em ..  
` String sql = "INSERT INTO " + this.tableName + "(name, lock_until, locked_at, locked_by) VALUES(?, ?, ?, ?)";
        return (Boolean)this.transactionTemplate.execute((status) -> {
            try {
                int insertedRows = this.jdbcTemplate.update(sql, (preparedStatement) -> {
                    preparedStatement.setString(1, lockConfiguration.getName());
                    this.setTimestamp(preparedStatement, 2, lockConfiguration.getLockAtMostUntil());
                    this.setTimestamp(preparedStatement, 3, Instant.now());
                    preparedStatement.setString(4, this.getHostname());
                });
                return insertedRows > 0;
            } `

I see the source code，'locked_by' field only get from hostname ?

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Just out of curiosity, why do you need to change `locked_by`? ShedLock does not use it and it's there just for debugging purposes.

**Comment by PeppaLittlePig** [comment]
Hello, thanks for the reply. When Shedlock uses the Jdbctemplate provider, it should use 'locked_by' field(mysql table field) to distinguish which instance is currently executing the scheduled task, right? I currently have 3 servers, and the hostname of each server is the same, so ca n’t I tell which server the current task was performed on, right? Can I only change the hostname on each server?

**Comment by PeppaLittlePig** [comment]
Thanks for your changes

**Comment by lukas-krecan** [comment]
Released as 4.1.0
