### ISSUE TITLE
Running @Scheduled Tasks in a Custom Thread Pool does not creates lock

### ISSUE THREAD

**Issue by rdurgesh** [lukas-krecan/ShedLock#187]
Hi, I am using Custom Thread Pool where I am maintaining pool size of 10 threads by implementing SchedulingConfigurer class of Spring. In this case it does not create lock entry in DB and both the instances run the scheduled task on given time.

**Comment by lukas-krecan** [comment]
Can you please specify, which version do you use. I think updating to newest version or using PROXY_METHOD mode should help
