### ISSUE TITLE
Triggering code when lock can't be acquired

### ISSUE THREAD

**Issue by SprdNils** [lukas-krecan/ShedLock#190]
Hi,

Shedlock executes a method only when the lock gets acquired. But there is no possibility to point to a method which is called when the lock can't be acquired. I could image that the method

`net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor#executeWithLock(net.javacrumbs.shedlock.core.LockingTaskExecutor.Task, net.javacrumbs.shedlock.core.LockConfiguration)` 

could get a new parameter that points to a `Task` which is executed whenever the lock can't be acquired.

Makes this sense?

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I think it would be easier for you to use directly LockProvider. Something like

```java
Optional<SimpleLock> lock = lockProvider.lock(lockConfig);

if (lock.isPresent()) {
  try {
      task.call();
  } finally {
      lock.get().unlock();
  }
} else {
    // do something else
}

```

**Comment by SprdNils** [comment]
Ah, cool :-). Many thanks. That was easy :-).
