### ISSUE TITLE
Hazelcast/Spring: Unlock on context destroy

### ISSUE THREAD

**Issue by OmarHawk** [lukas-krecan/ShedLock#1920]
**Is your feature request related to a problem? Please describe.**
Hi!

We are using ShedLock together with Hazelcast in a Spring Boot project to keep certain locks in a distributed way. At the moment, we have our lock(s)/job(s) configured like this, as we have a task that can finish within a few seconds (like 5s), but also can run up to 1 hour.
```
    @Scheduled(cron = "0/10 * * * * ?", zone = "Europe/Berlin")
    @SchedulerLock(name = "MyScheduledStuff", lockAtMostFor = "PT1H")
```

When one instance of the application that currently runs that scheduled job is being shutdown (gracefully actually), while the scheduled task is still running, the lock is not being released from the Hazelcast, leading to not having the Scheduler run for an hour until the lock actually expires. This is not really desired...

**Describe the solution you'd like**
Ideally, the lock would be automatically cleared when the Spring context is being destroyed, as this also stops any Scheduled tasks anyway, and a new instance that is being spawned automatically should be able to run the job kind of immediately again and shouldn't wait for the lock to expire.

**Describe alternatives you've considered**
I've tried to implement something like described above by myself, but the unlock method of the (Hazelcast)LockProvider is not part of the public API.

**Additional context**
-

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. This is actually pretty hard to achieve.

First of all, if a thread is executing a task, it may get interrupted, but your code [has to support it](https://docs.oracle.com/javase/tutorial/essential/concurrency/interrupt.html). 

But even if the thread gets interupted, usually Spring takes down the infrastructure beans too and it's not possible to call Hazelcast as the Hazlecast related beans may be already destroyed.

Using the[ lock extension](https://github.com/lukas-krecan/ShedLock?tab=readme-ov-file#extending-the-lock)  may be the solution in your case.

**Comment by lukas-krecan** [comment]
Alternatively, you can [wrap the LockProvider](https://github.com/lukas-krecan/ShedLock?tab=readme-ov-file#customization), keep track of tha active locks yourself and when the application is preparing for shutdown, you can relelase the locks. Just keep in mind that for some short time, between the lock release and the JVM shutdown, the original task may keep running and since the lock is released, another instance of the task may get executed.

**Comment by OmarHawk** [comment]
> Alternatively, you can [wrap the LockProvider](https://github.com/lukas-krecan/ShedLock?tab=readme-ov-file#customization), keep track of the active locks yourself and when the application is preparing for shutdown, you can relelase the locks. Just keep in mind that for some short time, between the lock release and the JVM shutdown, the original task may keep running and since the lock is released, another instance of the task may get executed.

The HazelcastLockProvider won't allow to release locks from a wrapping class, as the API it exposes is package protected (no protected modifier present at the respective methods), so I would require to use some sort of reflection, which I would really like to not do...

> Using the[ lock extension](https://github.com/lukas-krecan/ShedLock?tab=readme-ov-file#extending-the-lock) may be the solution in your case.

Unfortunately, we are doing some parallel processing in there, so according to your JavaDoc, it may not work properly:
https://github.com/lukas-krecan/ShedLock/blob/cdce1a6c8d01c1e522da8bea1fe092957483af70/shedlock-core/src/main/java/net/javacrumbs/shedlock/core/LockExtender.java#L17-L18

---

I am now looking into the KeepAliveLockProvider.

**Comment by OmarHawk** [comment]
> I am now looking into the KeepAliveLockProvider.

Unfortunately, that one requires a `ScheduledExecutorService` in the constructor, which I don't have and actually don't want to provide, as we are using Spring and that one provides something kind of equal, but with a different implemented interface `org.springframework.scheduling.TaskScheduler`

---
Any other ideas?

**Comment by OmarHawk** [comment]
OK, maybe I finally see. Extending the LockProvider (HazelcastLockProvider) allows me to override the lock method, which in turn allows me to register the locks by myself. These locks are of SimpleLock type, which exposes the unlock method.

**Comment by OmarHawk** [comment]
Ok, just to wrap it up, what I did and it seemingly helped resolving this issue to me:

- a separate lock registry keeping the currently requested locks in a local Map (LockName => Lock) and the allows to find and unlock a lock by the name `unlockByName`
- a wrapped HazelcastLockProvider that passes the requested locks into the mentioned separate registry
- the class that contains the Scheduled job `implements ApplicationContextAware, BeanNameAware, DisposableBean` and storing arguments for the to be implemented methods into fields
- implemented a method `removePendingLocks()` in the Scheduler class that does two things:
-- first cancels the currently running scheduled task using `this.bean.postProcessBeforeDestruction(this, this.beanName);`
-- unlocks the lock via separate registry `unlockByName`
- put a `@PreDestroy` on the destroy method in the class with the Scheduler
- registered a LifecycleListener like this in the Scheduler class:
```
hazelcastInstance
            .getLifecycleService()
            .addLifecycleListener(listener -> {
                if (listener.getState() == LifecycleState.SHUTTING_DOWN) {
                    removePendingLocks();
                }
            });
```

Apart from a few exceptions in the Log when shutting down (which I am fine with for now), the lock gets cleaned up properly while the Scheduled job is running.
