### ISSUE TITLE
Does shedlock support redis cluster with jedisLockProvider?

### ISSUE THREAD

**Issue by rygh4775** [lukas-krecan/ShedLock#193]
Hi, @lukas-krecan 

I see jedisLockProvider can only accept jedisPool, no jedisCluster.
I have version issue to use Spring RedisConnectionFactory.

Thank you.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. JedisCluster is currently not supported. If you want, you can provide a PR, otherwise I will look at it next week.

**Comment by lukas-krecan** [comment]
Released in 4.3.0. I have also upgraded Jedis to 3.2.0
