### ISSUE TITLE
Getting unwanted error logs when trying to insert lock

### ISSUE THREAD

**Issue by logeshbabueee** [lukas-krecan/ShedLock#1947]
We are getting exception whenever shedlock tries to insert a record to shedlock table - this creates unnecessary alert in our monitoring which we are ignoring as of now.

Can we make this as a single line warning message instead of having logged as error.
Also, anyway we do a update if insert fails and so I suppose logging a single line warning when insert fails would be fine.

We use MS SQL in our application.

Please let me know your thoughts.
Thanks.

**Comment by lukas-krecan** [comment]
Hi, `useDbTime()` should help. If not please share the exception and which DB do you use.

**Comment by lukas-krecan** [comment]
What ShedLock version do you use?

**Comment by logeshbabueee** [comment]
It is 4.37

**Comment by lukas-krecan** [comment]
The bug report template says "upgrade to the latest version" . Can you please do that instead of wasting our time?

**Comment by logeshbabueee** [comment]
Yeah that's ok - I now understood the real issue... We use spring 6.0.3 which reports Duplicate key exception as Data Integrity exception... So it was logged as error... For now we will do a workaround in our app itself... We will soon upgrade to Spring latest one which shld solve this...

**Comment by lukas-krecan** [comment]
ShedLock 5.0.1 has a workaround for this issue
