### ISSUE TITLE
Sharing data source with spring boot

### ISSUE THREAD

**Issue by xiaoshuw** [lukas-krecan/ShedLock#195]
I have a strange issue. I have a datasource that I use springboot / spring-data to access. I added the table in the database (an Oracle one) and then constructed the LockProvider as follows

@Bean
public LockProvider lockProvider(@Qualifier("my.datasource") DataSource dataSource) {
       JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("ALTER SESSION SET CURRENT_SCHEMA=RIGHT_SCHEMA");
        return new JdbcTemplateLockProvider(dataSource);
 }

I have to change the schema.

However, sometimes it works without problem but sometimes I got error saying 

Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

And if there is an error, the scheduled task won't run at all.

So, I have two questions. 1) why the inconsistent result. 2) Is there a property it can set, e.g., so the task will run even when there is an error from ShedLock?

**Comment by lukas-krecan** [comment]
Which ShedLock version do you use?

**Comment by xiaoshuw** [comment]
4.2.0. What I think is that the issue depends on the order of bean initialized.

The data source is specified by spring boot (customized namespace, i.e., not spring.datasource) and is used by Spring Data. The default schema is set via spring.jpa.properties.hibernate.default_schema. (As this is an Oracle database, the username is set not to be the same as the schema).

Because  JdbcTemplateLockProvider — I guess -- doesn’t understand the spring.jpa.properties.hibernate.default_schema, so I have to do set it during LockProvider’s bean initialization.

But it works inconsistently.

Xiaoshu

**Comment by lukas-krecan** [comment]
There is not much I can do to help you. You can try to add @Lazy annotation on the `DataSource dataSource` parameter or the `lockProvider` method. The `ALTER SESSION` command does not look helpful since it's executed only on one connection of the connection pool.

**Comment by lukas-krecan** [comment]
Actually, I think that the ALTER SESSION command may be the reason for the inconsistencies. Current schema should be set by correctly configuring the datasource.

**Comment by xiaoshuw** [comment]
But without that alter session, it gets table not found error always. That
is the reason I put there.

The schema was set via jpa's hibernate properties,but seemed not picked up
by schedlock

Xiaoshu

**Comment by lukas-krecan** [comment]
I think you can specify the schema in tablename  `new JdbcTemplate(dataSource, "RIGHT_SCHEMA.shedlock")`
