### ISSUE TITLE
High Concurrency Issue with MySQL Lock Provider in ShedLock 5.13.0

### ISSUE THREAD

**Issue by rkhanipour** [lukas-krecan/ShedLock#1968]
I am currently using ShedLock version 5.13.0 with the MySQL lock provider. I've encountered a significant issue related to high concurrency.

**Issue:**
When the update query on the ShedLock table executes in less than 1 millisecond, it can fail to prevent two instances from acquiring the lock simultaneously under high concurrency conditions. This results in two instances obtaining the lock at the same time, which defeats the purpose of using ShedLock for ensuring only one instance performs a scheduled task at any given time.

**Details:**
The problem seems to arise because the precision of the lock timestamp is insufficient (millisecond), causing the locking mechanism to fail under high concurrency scenarios. This leads to multiple instances being able to obtain the lock simultaneously, which is critical for applications relying on ShedLock to manage task scheduling.

**Proposed Solution:**
To mitigate this issue, I suggest implementing microsecond precision for the timestamp used in the lock table. This enhancement should reduce the likelihood of concurrent locks being acquired, thus ensuring the reliability of the lock mechanism even under high traffic conditions.

**Comment by lukas-krecan** [comment]
Hi, I checked the code and the only case when it can behave as you describe is if your task takes longer than the `lockAtMostFor` value. What's your `lockAtMostFor` setting?

But if you think you need more precission anyway, it's up to you. If you set `useDbTime` config parameter then it only depends on the the precisision of the `lock_until` DB column. But I do not think it's going to help.

**Comment by rkhanipour** [comment]
Hi Lukas, I checked again and you were right our problem was related to take longer than the `lockAtMostFor`. Thank you for your quick response
