### ISSUE TITLE
Difference between defaultLockAtMostFor, lockAtMostFor and lockAtLeastFor?

### ISSUE THREAD

**Issue by jyk88** [lukas-krecan/ShedLock#198]
Hi, thank you for building and maintaining this project! I was just curious if you could shed light on the different lock timing fields I need to fill in. 

For example, I have a job I'd like to run. It should take no more than 10 seconds, and I'd like to run it once per day, every day. I have my annotations like this but not sure if this is 100% correct for my use case. 

`@Scheduled(cron = "0 0 2 * * ?") // run at 2:00am, every day`
`@SchedulerLock(name = "expirePayments", lockAtMostFor = "PT30S", lockAtLeastFor = "PT30S")`

and in my ApiService spring boot main class...
`@EnableSchedulerLock(defaultLockAtMostFor = "PT1M")` (is PT1M correct for my use case?)

one more question -- just wondering where my `public LockProvider lockProvider(Datasource datasource)` method should go. I put it in the service class where i have the SchedulerLock annotation, but is that the most correct place for it?

Thank you again!

**Comment by lukas-krecan** [comment]
Hi, lock times are described here https://github.com/lukas-krecan/ShedLock#annotate-your-scheduled-tasks. If the explanation is not clear, please specify what is not clear so I can fix it. `public LockProvider lockProvider(Datasource datasource)` goes with the rest of your bean definitions like for example here https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-application-exit

**Comment by jyk88** [comment]
1. lock definitions -- i've read that portion, but that portion only talks about `lockAtMostFor` and `lockAtLeastFor`, but not `defaultLockAtMostFor`. so i wasn't sure what the difference was, and how to set `defaultLockAtMostFor` relative to the first two. 

2. thanks for the doc, that's perfect.

**Comment by lukas-krecan** [comment]
Cool, I will enhance the documentation. `defaultLockAtMostFor` is the default value for `lockAtMostFor` for cases when you do not specify in the `@SchedulerLock` annotation.
