### ISSUE TITLE
Cassandra support

### ISSUE THREAD

**Issue by javix** [lukas-krecan/ShedLock#2]
Hi,
we need support for cassandra.
How expensive it is?
Can we implement it self?
Thanks

**Comment by lukas-krecan-lt** [comment]
Hi, you can implement it yourself (I wilcome pull-requests) Should be quite easy, just implement LockProvider interface like for example here https://github.com/lukas-krecan/ShedLock/blob/master/shedlock-provider-zookeeper-curator/src/main/java/net/javacrumbs/shedlock/provider/zookeeper/curator/ZookeeperCuratorLockProvider.java or here https://github.com/lukas-krecan/ShedLock/blob/master/shedlock-provider-mongo/src/main/java/net/javacrumbs/shedlock/provider/mongo/MongoLockProvider.java

**Comment by lukas-krecan** [comment]
Released in 4.2.0
