### ISSUE TITLE
Possible Transaction Issue

### ISSUE THREAD

**Issue by tntim96** [lukas-krecan/ShedLock#20]
I haven't verified this, but have noticed when running two jobs at the same time on Postgres I'm getting the following error:
`Caused by: org.postgresql.util.PSQLException: ERROR: out of shared memory
  Hint: You might need to increase max_locks_per_transaction.`

The code is shown below

```Java
  @Scheduled(cron = "*/30 * * * * *") //every 30 secs
  @SchedulerLock(name = "update1", lockAtLeastFor = 15 * 1000)
  @Transactional(isolation = Isolation.READ_UNCOMMITTED)
  public void update1() {
    log.debug("Running update1: " + new Date());
    myDAO.update1();
    log.debug("Finished Running update1: " + new Date());
  }

  @Scheduled(cron = "*/30 * * * * *") //every 30 secs
  @SchedulerLock(name = "update2", lockAtLeastFor = 15 * 1000)
  @Transactional(isolation = Isolation.READ_UNCOMMITTED)
  public void update2() {
```

I'll try to confirm tomorrow, but thought I'd raise this in case you get a chance to test. We're using version `0.11.0`.

**Comment by lukas-krecan-lt** [comment]
Hi, thanks for feedback. I doubt the exception is caused by ShedLock, it just updates one row in autocommit mode. But if you have any information proving me wrong, please do not hesitate to report it here.

**Comment by clamey** [comment]
That's most likely a Postgres memory config issue:

https://www.postgresql.org/docs/9.1/static/runtime-config-locks.html

https://www.postgresql.org/docs/9.1/static/kernel-resources.html#SYSVIPC

**Comment by tntim96** [comment]
It seems to be a problem with one of our queries inside the scheduled job.
