### ISSUE TITLE
Support for non-void returning methods when PROXY_METHOD interception is used

### ISSUE THREAD

**Issue by pzapasni** [lukas-krecan/ShedLock#200]
Quote from readme:

>Since version 4.0.0, the default mode of Spring integration is an AOP proxy around the annotated method.
>The main advantage of this mode, is that it plays well with other frameworks that want to somehow alter the default Spring scheduling mechanism. The disadvantage is that the lock is applied even if you call the method directly. **Be also aware that only void-returning methods are currently supported, an exception is thrown if you annotate and schedule a method with non-void return type.**

Have you considered introducing support for non-void returning methods? If the issue is with the return value of a locked method (as mentioned in the exception message [here](https://github.com/lukas-krecan/ShedLock/blob/6635068c93a148f950fb4c2ae4af750d61d6ce77/spring/shedlock-spring/src/main/java/net/javacrumbs/shedlock/spring/aop/LockingNotSupportedException.java#L22)), then maybe using a default value based on the return type of the locked method would be a feasible solution?

**Comment by lukas-krecan** [comment]
Yes, the reason is that I do not know what to return when the lock is held by someone else. I think I can easily support Optional return type, would it be enough for you?

Or you can use Task Scheduler proxy https://github.com/lukas-krecan/ShedLock/blob/master/README.md#taskscheduler-proxy

**Comment by pzapasni** [comment]
Unfortunately, the task scheduler proxy isn't an option for me, as in my use-case the locked method can be called directly as well as via the scheduler. Also, my project is in Kotlin, which uses nullable types in favor of Java's Optional. So for me, there are two ways that the "locked method scenario" could be handled:

1. Return a default value based on the locked method's return type - e.g. ``null`` for all reference types
2. Throw an exception. This could be added in a backwards-compatible manner by adding a new parameter to the ``@SchedulerLock`` annotation, e.g. ``@SchedulerLock(throwAnExceptionIfLocked = true)``

**Comment by lukas-krecan** [comment]
Released as 4.4.0

**Comment by pzapasni** [comment]
Works like a charm, thanks!
