### ISSUE TITLE
MongoClient since 3.7 version support

### ISSUE THREAD

**Issue by tuus-amicus** [lukas-krecan/ShedLock#202]
Hi, there! 

Since **Mongo-java-driver** [3.7](https://mongodb.github.io/mongo-java-driver/3.7/whats-new/#new-entry-point) `com.mongodb.MongoClient` using in your [MongoLockProvider](https://github.com/lukas-krecan/ShedLock/blob/f6c49d1d86f635f5c8a5241b9d7b28d971ef6c8e/providers/mongo/shedlock-provider-mongo/src/main/java/net/javacrumbs/shedlock/provider/mongo/MongoLockProvider.java#L87), is deprecated, alternative to use is `com.mongodb.client.MongoClient`.

Are you suppose to add this in feature releases or what solutions will you recommend?
Thanks.

**Comment by lukas-krecan** [comment]
I guess, I can support both MongoClients. In the meantime you can use `MongoLockProvider(@NotNull MongoCollection<Document> collection)`

**Comment by tuus-amicus** [comment]
So, will wait for new update, until will be using proposed solution. Thank you!

**Comment by tuus-amicus** [comment]
Can you close the issue when release be ready?

**Comment by lukas-krecan** [comment]
Ok. I plan only to add one constructor to the provider like this https://github.com/lukas-krecan/ShedLock/commit/fae66a1ec336cf430964cae5c14c110583b8636e

**Comment by tuus-amicus** [comment]
> Ok. I plan only to add one constructor to the provider like this [fae66a1](https://github.com/lukas-krecan/ShedLock/commit/fae66a1ec336cf430964cae5c14c110583b8636e)

It's quite enough! Big thanks.

**Comment by lukas-krecan** [comment]
Released as 4.5.0
