### ISSUE TITLE
QA: DefaultLockingTaskExecutor executeWithLock

### ISSUE THREAD

**Issue by lengcz** [lukas-krecan/ShedLock#2034]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

Update to the latest version.

**Describe the bug**
1. Which version do you use  <kbd>4.46.0</kbd>
2. Which Lock Provider  <kbd>DefaultLockingTaskExecutor</kbd>
3. ShedLock configuration   <kbd>NA</kbd>
4. ShedLock logs <kbd>NA</kbd>

net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.java
~~~java
 @Override
    public void executeWithLock(Runnable task, LockConfiguration lockConfig) {
        try {
            executeWithLock((Task) task::run, lockConfig);
        } catch (RuntimeException | Error e) {
            throw e;
        } catch (Throwable throwable) {
            // Should not happen
            throw new IllegalStateException(throwable);
        }
    }

    @Override
    public void executeWithLock(Task task, LockConfiguration lockConfig) throws Throwable {
        executeWithLock(
                () -> {
                    task.call();
                    return null;
                },
                lockConfig);
    }
~~~
Both methods return void,and are synchronous methods （they will all block the main thread）.
In actuality , there is no difference in usage.
Could u help me? or these methods are meaningless?

**Comment by lukas-krecan** [comment]
Hi, sorry, I don't understad what you are asking about. The methods have a different signature.
