### ISSUE TITLE
Remove lock on shutdown

### ISSUE THREAD

**Issue by uyw4687** [lukas-krecan/ShedLock#2047]
**Is your feature request related to a problem? Please describe.**
I think it's good to provide feature to remove locks on shutdown

**Describe the solution you'd like**
On shutdown all the locks are unlocked if a flag is enabled.

**Describe alternatives you've considered**

**Additional context**
I think it's not okay to have an active lock though it's not processed due to a shutdown in a server in some cases.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. It may lead to unpredictable results. Imagine you unlock a lock, another note will obtain the lock but before Spring container finishes the shutdown, the orignal tasks finishes. Unlock will be called for the second time and the lock from antoher node will be released prematurely. 

You can use a LockProvider wrapper like this [one](https://github.com/lukas-krecan/ShedLock/pull/2050/files) but it's a footgun I don't want to include into the project.

**Comment by lukas-krecan** [comment]
Actually, the clean solution is to abort the tasks when Spring is shutting down. Locks will be released automatically when the tasks finish.

**Comment by uyw4687** [comment]
I understood your point. Thanks!
