### ISSUE TITLE
What if i want to use Combination of annotation in Spring？

### ISSUE THREAD

**Issue by Kk1905** [lukas-krecan/ShedLock#208]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Kk1905** [comment]
for example ，i worote an custom annotation `MyScheduled`：
@Target({ElementType.METHOD, ElementType.ANNOTATION_TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Scheduled
@Async
@SchedulerLock
public @interface MyScheduled {
  @AliasFor(
      annotation = Scheduled.class
  )
  String cron();

  @AliasFor(
      annotation = SchedulerLock.class,attribute = "name"
  )
  String name();

  @AliasFor(
      annotation = SchedulerLock.class,attribute = "lockAtMostFor"
  )
  String lockAtMostFor() default "";

  @AliasFor(
      annotation = SchedulerLock.class,attribute = "lockAtLeastFor"
  )
  String lockAtLeastFor() default "";
}

I tested，`SchedulerLock` does not work.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback, I will take a look at it.

**Comment by lukas-krecan** [comment]
Released as 5.6.0
