### ISSUE TITLE
没有办法优雅停机

### ISSUE THREAD

**Issue by shyding** [lukas-krecan/ShedLock#211]
最新版
 强制停机的时候,仍旧去获取数据库连接,导致报错

**Comment by shyding** [comment]
测试发现 <version>2.3.0</version> 没有问题,
但是 <version>4.5.2</version> 有问题

**Comment by shyding** [comment]
4.6.0 也有问题
2.3.0更有问题,根本没有读取到数据库

**Comment by lukas-krecan** [comment]
Sorry, I do not understand.
