### ISSUE TITLE
同一主机不同端口的应用&& 统一应用相同shedLock  name 都可以在同一时间启动

### ISSUE THREAD

**Issue by shyding** [lukas-krecan/ShedLock#213]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

**Describe the bug**
1. Which version do you use
2. Which Lock Provider
3. ShedLock configuration
4. ShedLock logs

**Expected behavior**

**Actual behavior**
What happened instead.

**Comment by lukas-krecan** [comment]
Sorry, I do not understand.

**Comment by shyding** [comment]
It means the shedlock doesn't work right when I start two or more apps withc dfiffrent port  in a same PC or host .
