### ISSUE TITLE
Use the time 0f the executeing methond  as the default lock time

### ISSUE THREAD

**Issue by shyding** [lukas-krecan/ShedLock#215]
**Is your feature request related to a problem? Please describe.**
now use lockAtLeastForString and lockAtMostForString to controle the lock thie ,which I'think is useless to actural work
**Describe the solution you'd like**
Use the time 0f the methond execution which annotatied @ShedlockSchedule

**Describe alternatives you've considered**
Use the methond execution time as the lock  time

**Additional context**

**Comment by lukas-krecan** [comment]
Sorry, I really do not understand.
