### ISSUE TITLE
Use the execution time of method as the default lock time of shedlock

### ISSUE THREAD

**Issue by shyding** [lukas-krecan/ShedLock#217]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

**Describe the bug**
1. Which version do you use
4.6.0
2. Which Lock Provider
jdbc
3. ShedLock configuration
	@Bean
    public LockProvider lockProvider( DataSource dataSource ){
        return new JdbcTemplateLockProvider(JdbcTemplateLockProvider.Configuration.builder()
        		.withJdbcTemplate(new JdbcTemplate(dataSource))
                .withTimeZone(TIME_ZONE)
        		.build()
        		);
    }

4. ShedLock logs

**Expected behavior**
Use the execution time of the method as the time of the shedlock lock

**Actual behavior**
Use lockatmostfor and lockatleastfor of @ schedulerlock annotation to control Shedlock Lock time

**Comment by shyding** [comment]
a good feature

**Comment by lukas-krecan** [comment]
Sorry, I can not implement something that completely lacks any description. The issue has a template for a reason, especially the sections Expected behavior and Expected behavior

**Comment by shyding** [comment]
Issues updated

**Comment by lukas-krecan** [comment]
I am sorry, I still do not understand, can you please provide an example.

**Comment by shyding** [comment]
When the @ schedulerlock annotation is marked on a method, lock the method until the method is completed

**Comment by lukas-krecan** [comment]
Yes, that's exactly what ShedLock does
