### ISSUE TITLE
The time used by the debug log is still UTC time zone,. the confiiguration of JdbcTemplateLockProvider Withtimezone ("GMT+08") is invalid

### ISSUE THREAD

**Issue by shyding** [lukas-krecan/ShedLock#218]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

**Describe the bug**
the class name is  JdbcTemplateStorageAccessor
    logger.debug("Extending lock={} until={}", lockConfiguration.getName(), lockConfiguration.getLockAtMostUntil());

1. Which version do you use
4.6.0
2. Which Lock Provider
JdbcTemplateLockProvider
3. ShedLock configuration

4. ShedLock logs
    logger.debug("Extending lock={} until={}", lockConfiguration.getName(), 

**Expected behavior**
The debug log should use the configured time zone instead of the UTC time zone at all times

**Actual behavior**
What happened instead.
Always use UTC time zone to print logs

**Comment by lukas-krecan** [comment]
Can you please provide example of the log?

**Comment by shyding** [comment]
n.j.s.c.DefaultLockingTaskExecutor -72- Locked 'myOrderTask', lock will be held at most until 2020-04-07T07:04:19.522Z

**Comment by shyding** [comment]
Line 72 of the Defaultlockingtaskexecutor 
is "                logger.debug("Locked '{}', lock will be held at most until {}", lockName, lockConfig.getLockAtMostUntil());" which there is UTC tinezone
