### ISSUE TITLE
Compatibility with Hazelcast version 4.0

### ISSUE THREAD

**Issue by cedricSarre** [lukas-krecan/ShedLock#219]
**Is your feature request related to a problem? Please describe.**
The ShedLock Hazelcast provider is not compatible with Hazelcast v4 (Hazelcast has moved some classes). So I cannot use the new evolution "CPSubsystem" of Hazelcast and ShedLock together.

**Describe the solution you'd like**
Be compatible with Hazelcast from 4.0 version

**Describe alternatives you've considered**
I have to take a choice. 
Either I use Shedlock and my own leader election system with Hazelcast v3.6 or I no longer use Shedlock and I simply use the leader election in order to perform my scheduled tasks on a single node.
Clearly I would prefer to keep both libraries.
Thanks

**Comment by lukas-krecan** [comment]
Thanks for reporting, will take a look at it.

**Comment by lukas-krecan** [comment]
I had to create a new lock provider module since the changes in Hazelcast are not backward-compatible. Will release it over the weekend

**Comment by cedricSarre** [comment]
Many thanks :)

**Comment by lukas-krecan** [comment]
Released as 4.7.0
