### ISSUE TITLE
Clarification on lockAtMostFor Behavior in ShedLock

### ISSUE THREAD

**Issue by barankaplan** [lukas-krecan/ShedLock#2223]
I’m reaching out for clarification regarding the lockAtMostFor parameter’s behavior. Based on the documentation, it’s understood that lockAtMostFor sets the maximum duration a lock should be held, even if the task doesn’t complete within this time. This would imply that if a task runs longer than the specified lockAtMostFor duration, the lock would be released, allowing the task to potentially be re-executed on another node.

In practice, however, we’ve observed that ShedLock retains the lock until the task completes, regardless of whether lockAtMostFor has expired. This appears to be a divergence from the documented behavior and suggests that ShedLock might be designed to prioritize task completion and data consistency by holding the lock for the entire task duration.

Could you kindly confirm if this is the intended behavior? Additionally, any insights into best practices for setting lockAtMostFor in scenarios where task duration might occasionally exceed expectations would be very helpful. We aim to balance task consistency with the need to prevent task duplication across nodes.

Thank you very much for your time and assistance. Ich share my codes and logs below : 

    @Scheduled(fixedRate = 120000) 
    @SchedulerLock(name = "MyScheduledTask_testTask", lockAtMostFor = "PT1M30S", lockAtLeastFor = "PT1M")
    public void testTask() {
        logger.info("Task started: " + System.currentTimeMillis());

        try {
            Thread.sleep(120000); // it is 2 Min
        } catch (InterruptedException e) {
            logger.error("Task interrupted", e);
            Thread.currentThread().interrupt();
        }

        logger.info("Task ended: " + System.currentTimeMillis());
    } 
2024-11-03T12:07:31.288+01:00 DEBUG 11046 --- [   scheduling-1] n.j.s.core.DefaultLockingTaskExecutor    : Locked 'MyScheduledTask_testTask', lock will be held at most until 2024-11-03T11:09:01.277Z
2024-11-03T12:07:31.288+01:00  INFO 11046 --- [   scheduling-1] de.kaplan.shedlock.MyScheduledTasks      : Task started: 1730632051288
2024-11-03T12:09:31.289+01:00  INFO 11046 --- [   scheduling-1] de.kaplan.shedlock.MyScheduledTasks      : Task ended: 1730632171289
2024-11-03T12:09:31.301+01:00 DEBUG 11046 --- [   scheduling-1] n.j.s.core.DefaultLockingTaskExecutor    : Task finished, lock 'MyScheduledTask_testTask' released

**Comment by lukas-krecan** [comment]
Hi, as the README says:

> You have to set lockAtMostFor to a value which is much longer than normal execution time. If the task takes longer than lockAtMostFor the resulting behavior may be unpredictable (more than one process will effectively hold the lock).


If your execution times are indeed unpredictable, you can either [extend the lock](https://github.com/lukas-krecan/ShedLock?tab=readme-ov-file#extending-the-lock) or use some other library
