### ISSUE TITLE
 What does this mean in READEME If you need to specify a schema, you can set it in the table name using the usual dot notation new JdbcTemplateLockProvider(datasource, "my_schema.shedlock")

### ISSUE THREAD

**Issue by engineerping** [lukas-krecan/ShedLock#2225]
Could you please give an example like :
@Bean
public LockProvider lockProvider(DataSource dataSource) {
            return new JdbcTemplateLockProvider(
                JdbcTemplateLockProvider.Configuration.builder()
                .withJdbcTemplate(new JdbcTemplate(dataSource))
                .usingDbTime() // Works on Postgres, MySQL, MariaDb, MS SQL, Oracle, DB2, HSQL and H2
                .build()
            );
}

**Comment by lukas-krecan** [comment]
Hi, please ask questions on StackOverflow. Thanks for understanding
