### ISSUE TITLE
Migrate to AWS SDK2 for DynamoDB Provider

### ISSUE THREAD

**Issue by xmrk** [lukas-krecan/ShedLock#224]
**Feature Request - Support AWS SDK2 Client for DynamoDB**
Many new projects prefer Amazon's Java SDK v2.  The current DynamoDB provider is backed by v1.  

**Proposed Solution**
A clone of that DynamoDB module, naming to identify it as SDK v2 backed and refractoring against that SDK v2 would allow projects to avoid pulling SDK v1 into their dependencies.

**Current Workaround**
As a work around I implemented a LockProvider based on the v1 client but backed by the v2 client.

**Comment by lukas-krecan** [comment]
Thanks for reporting, I will take a look at it

**Comment by lukas-krecan** [comment]
Hi, could you please provide a pull request? I can't figure out how old API maps to the new one. The pull request does not have to be perfect, I just do not have the capacity to learn new API

**Comment by xmrk** [comment]
Yes, I’ll submit a pull request in a couple days.
