### ISSUE TITLE
ReactiveLockProvider

### ISSUE THREAD

**Issue by Exceptionflug** [lukas-krecan/ShedLock#2307]
**Is your feature request related to a problem? Please describe.**
I am brave enough to use your R2DBC lock provider, but as it seems, it is not really reactive at all 😅.
![Unbenannt](https://github.com/user-attachments/assets/601c51f7-548c-4353-a99d-e1b1667e70a3)

**Describe the solution you'd like**
I would like to have a ReactiveLockProvider interface which makes use of the reactive operations in AbstractR2dbcStorageAccessor by returning some reactor publishers to be used within a reactive chain. An extra bonus would be, if it is coupled somehow with the reactive context to automatically unlock when the chain is completed, like spring does with reactive transactions.

**Describe alternatives you've considered**
I also considered implementing this for my project on my own, but I see that this could be a useful contribution then.

**Additional context**
If there is already a other way on how to properly use this, then please tell me 

Kind regards

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback, unfortunatelly reactive support would require major refactoring of the whole library. Given the fect that the main purpose of the librariy is locking of scheduled jobs, where using reactive does not make much sense, and given the fact that for most use-cases virtual threads provide better alternative to reactive code, I don't think it's worth the effort.

The purpose of R2BC lock provider is to allow users to use ShedLock without having to introduce JDBC dependencies. That use-case is covered by the current implementation.
