### ISSUE TITLE
Node time is not synchronized, Jdbc lock will fail

### ISSUE THREAD

**Issue by ssslinppp** [lukas-krecan/ShedLock#231]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

**Describe the bug**
1. Version 4.6.0
2. Which Lock Provider： JDBCTemplate

**Expected behavior**
Consider the following scenario：

- tx1 running on node 1
- tx2 running on node 2
- node1 time: 20200413 12:00:00
- node2 time: 20200413 12:03:00

That is, the difference between the two nodes is 3 minutes；
if last lockUntil is 11:59:00 , now is 12:00:00, both  tx1 and tx2 try to acquire lock, and the atLeast is set to 2min, **if tx1 acquire lock and set lockUntil 12:02:00, then tx2 can also acquire this lock，because this sql**  
```
 String sql = "UPDATE " + tableName()
            + " SET " + lockUntil() + " = ?, " + lockedAt() + " = ?, " + lockedBy() + " = ? WHERE " + name() + " = ? AND " + lockUntil() + " <= ?";       
```
Want to determine if this is the case?

**Comment by lukas-krecan** [comment]
Yes, it's indeed the case. I will clarify it in the documentation. In theory, it's possible to use database time, but the syntax is different for each DB type so it's not so easy.
