### ISSUE TITLE
Support for composed annotations

### ISSUE THREAD

**Issue by flash1293** [lukas-krecan/ShedLock#24]
It would be cool for the `@SchedulerLock`-annotation to be allowed for other annotations to make custom composed annotations possible:
https://sdqali.in/blog/2015/12/06/implementing-custom-annotations-for-spring-mvc/
The `@Scheduled`-annotation already allows this: https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/scheduling/annotation/Scheduled.html

I would like to do something like this:
```java
@Target(METHOD)
@Retention(RUNTIME)
@Documented
@Scheduled
@SchedulerLock
public @interface ScheduledLocked {
  @AliasFor(annotation = Scheduled.class, attribute = "cron")
  String cron() default "";

  @AliasFor(annotation = SchedulerLock.class, attribute = "lockAtMostFor")
  long lockAtMostFor() default 20L;

  @AliasFor(annotation = SchedulerLock.class, attribute = "name")
  String name() default "";
}

// usage:

@ScheduledLocked(cron="* * * * * *", name="batchrun")
public void runBatch() {
  // ...
}
```

**Comment by lukas-krecan** [comment]
Thanks for feedback. Should be in version 0.12.0 that I have just released.

**Comment by flash1293** [comment]
Awesome, thanks a lot! 👍
