### ISSUE TITLE
Documentation not explaining how to obtain the CqlSession object (for Cassandra integration)

### ISSUE THREAD

**Issue by Dobiasd** [lukas-krecan/ShedLock#241]
Thanks for this great project. I'm successfully using it with PostgreSQL already. :+1:

However, I don't get it to work with Cassandra, because I can not obtain the needed `CqlSession` object.

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.datastax.oss.driver.api.core.CqlSession' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

The minimal example in the [docs](https://github.com/lukas-krecan/ShedLock/blob/master/README.md#cassandra) does not state how to get it.

```java
@Bean
public CassandraLockProvider lockProvider(CqlSession cqlSession) {
    return new CassandraLockProvider(cqlSession);
}
```

Here is a full minimal example (using Kotlin) to reproduce the issue: https://gist.github.com/Dobiasd/ac1429ad403c5480ea05fb11f9a53959

It would be cool if we documentation could be extended such that it explains how to get the `CqlSession`.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. The documentation assumes that you are already using Cassandra and that you know how to use it and configure it. I am afraid that I am not able to cover all possible options how people are configuring their projects so the documentation does not specify how to obtain JDBC data source, Mongo client or any other such class.

**Comment by Dobiasd** [comment]
Thanks for the quick reply.

I just naively (and wrongly) assumed, that the Cassandra version would also work out-of-the-box like the JDBC version, i.e., without needing to manually generate/obtain the argument for instantiating the `LockProvider`.

In the JDBC version (using `spring-boot-starter-data-jpa`) `DataSource` is available automaticaklly:

```
@Configuration
public class SchedulerConfiguration {
    @Bean
    public LockProvider lockProvider(DataSource dataSource) {
        return new JdbcTemplateLockProvider(dataSource);
    }
}
```

Before posting here regarding `CassandraLockProvider` and `CqlSession`, I already [asked on StackOverflow](https://stackoverflow.com/questions/61570651/how-to-dependency-inject-cqlsession), and there it was recommended to me to report this to you as a documentation issue. :grimacing:

**Comment by snicoll** [comment]
> Hi, thanks for feedback. The documentation assumes that you are already using Cassandra and that you know how to use it and configure it

I think that's fair. Perhaps a note that states that would help? That code snippet does not say anything about where that `CqlSession` bean comes from.

**Comment by Dobiasd** [comment]
Such a note might be OK, however, it would not help me solve my problem at hand. Obtaining the `CqlSession` in a project using `spring-boot-starter-data-cassandra` seems to be non-trivial. At least, up to now, everybody only told me "You should know how to do it." instead of actually explaining how. :grin:

I guess I'll try it with setting a bounty to my StackOverflow question as soon as it is eligible for one. :man_shrugging:

Thanks for the quick responses nonetheless. :+1:

**Comment by snicoll** [comment]
> Obtaining the CqlSession in a project using spring-boot-starter-data-cassandra seems to be non-trivial

If you're using the right Spring Boot version, it should be. I've commented your SO question.

**Comment by Dobiasd** [comment]
@snicoll Thanks a lot. It's working fine now. :slightly_smiling_face:

For future readers of this issue: You can find the solution [here](https://stackoverflow.com/questions/61570651/how-to-dependency-inject-cqlsession#comment108955507_61570792).

@lukas-krecan Do you think it would make sense to add a remark to the [docs](https://github.com/lukas-krecan/ShedLock/blob/master/README.md#cassandra) that at least version `2.3.0` of Spring Boot is needed for a `CqlSession` to exist?

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/ShedLock/commit/fb54200583fbba76c79398577201428de521edce

**Comment by Dobiasd** [comment]
Thanks, [that](https://github.com/lukas-krecan/ShedLock/commit/00fa959793acc6b32fabd4f88ca49f4fccaf9890) should suffice to save some time for future users like me. :+1:
