### ISSUE TITLE
Support multitenancy

### ISSUE THREAD

**Issue by siarhei-skavarodkin** [lukas-krecan/ShedLock#242]
**Support multitenancy**

I work on Spring-boot+Postgre application which works in multitenant-mode. Namely, we implemented [AbstractRoutingDataSource](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/jdbc/datasource/lookup/AbstractRoutingDataSource.html) and our solution is based on using ThreadLocal:
```
public class MyRoutingSource extends AbstractRoutingDataSource {
    @Override
    protected Object determineCurrentLookupKey() {
        return getNameOfTenantFromThreadLocal();
    }
    // ....
}
```
Ultimately I would like Shedlock to support the following:
- single `LockProvider` bean (as it is now)
- database for each tenant having own `shedlock` table
- cache `LockRecordRegistry` be tenant-dependant (i.e. `private final Set<String> lockRecords` transform to `private final Map<Object, Set<String>> lockRecords` where `Object` is tenant identifier (same as in `AbstractRoutingDataSource`).

When I tried to supply instance of `AbstractRoutingDataSource` to `JdbcTemplateLockProvider(myRoutingSource)` then I've got runtime exception because initialization of new Bean isn't bound to any tenant-context and `SqlStatementsSource#getDatabaseProductName` is trying to query DB during initialization.

**Suggested improvement**
- Give option to configuration to rather directly specify database-used OR lazy initialize DB provider name.
Example:
```
private static String getDatabaseProductName(Configuration configuration) {
        if (configuration.getPredifnedDatabaseProductName() != null) {
                return configuration.getPredifnedDatabaseProductName();
        }
        return configuration.getJdbcTemplate().execute((ConnectionCallback<String>) connection -> connection.getMetaData().getDatabaseProductName());
    }
```
- Make cache tenant-configurable.

**How to use multitenancy right now**
Workaround solution I came with:
- single `LockProvider` bean
- separate database for shedlock which is shared by all tenants
- wrapper util on top of shedlock where I add tenant-name as prefix to lock name

**Extra**
I would like to say thank you for such a nice library!

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Would something like this https://github.com/lukas-krecan/ShedLock/commit/75a89035e386ee26394d1bbc89965e93a989a9b7 help?

**Comment by lukas-krecan** [comment]
I will maybe also add support for specifying the product type name explicitly.

**Comment by lukas-krecan** [comment]
I have been thinking about it and probably the best way it to create a delegating `LockProvider` that has pool of other LockProviders which can in turn be created with normal DataSource. This approach would work-around the shared `LockRecordRegistry` as well as the issue with product name.

**Comment by lukas-krecan** [comment]
The fix 75a8903 is  released in 4.9.2, but I think that you should create your LockProvider wrapper anyway.

**Comment by siarhei-skavarodkin** [comment]
I guess having delegating `LockProvider` + 75a8903  should do the trick.
For sure, as lib-author you feel what's the most appropriated way to implement it (if implement at all - since it adds some complication).
Extra thought - in generic case of multitenancy (not my concrete case) database engines might be different (1 tenant - postgre, 2 tenant - mysql, 3 - oracle,....). From these perspective delegating lock provider which keeps a collection of normal LockProviders sounds good.

**Comment by lukas-krecan** [comment]
Yes, that's why I hesitate to add DB provider to the configuration.

**Comment by lukas-krecan** [comment]
Documented here https://github.com/lukas-krecan/ShedLock#Multi-tenancy
