### ISSUE TITLE
Getting org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar

### ISSUE THREAD

**Issue by suchitgupta01** [lukas-krecan/ShedLock#251]
**Environment:**
1. Postgres: 9.4
2. Spring: 4.2.1

**Issue:**
Postgres 9.4 doesn't support "On Conflict" thus I am getting the following exception:

`org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [INSERT INTO shedlock(name, lock_until, locked_at, locked_by) VALUES(?, ?, ?, ?) ON CONFLICT (name) DO UPDATE SET lock_until = ?, locked_at = ?, locked_by = ? WHERE r2d2.shedlock.lock_until <= ?]; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near "ON"
  Position: 90
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:235)`

**Expected Outcome:**
I am looking for a way by which the library can support PostgreSQL 9.4

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. For now please use ShedLock 4.7.1, in next few days I will provide fix.

**Comment by lukas-krecan** [comment]
I have tested it, and ti works in Postgres 9.6 but not in 9.4. Since 9.6 has been released 4 years ago I do not see much value in providing support for 9.4. You can either use ShedLock 4.7.1 or update Postgres.
