### ISSUE TITLE
Change the scheduler time while scheduling a cron job

### ISSUE THREAD

**Issue by sajetshah** [lukas-krecan/ShedLock#254]
I ran into an issue, when while testing ShedLock, we were testing different intervals (cron expression), some of them being every day, every hour and so on. Since, we were testing with the same SchedulerLock name, we saw that even after we set the new interval, the cron job was still fired at previous and new interval. 
 I know ideally, we should have used a new name for each interval, but my question is, how does ShedLock know which interval to run, if we have changed multiple intervals. It definitely doesn't pick up the latest interval. 
I see Shedlock doesn't store the cron expression in the db, so where is the interval time registered?  

Example: 
We ran the scheduler to trigger every midnight, then we override that to run every hour. 
And then change it to run every week. 
We see that scheduler is invoked on second update (every hour), but then switches back to triggering every midnight. Wanted to know how this works?

**Comment by lukas-krecan** [comment]
Hi. ShedLock does not do any scheduling, it only provides lock. I assume that scheduling itself is done by Spring or some other library.
