### ISSUE TITLE
How to use shedlock without annotation and on a dynamic scheduling

### ISSUE THREAD

**Issue by malabananharold** [lukas-krecan/ShedLock#257]
Which version do you use  4.8.0
    Which Lock Provider JDBCTemplate (postgresql)

Hi, I created a dynamic scheduling with a setup based on this [article](https://thebackendguy.com/spring-schedule-tasks-or-cron-jobs-dynamically/) and  I am trying to use shedlock with this approach.

I saw the suggestion on [ #245](https://github.com/lukas-krecan/ShedLock/issues/245) but I am confused on setting up the `LockableTaskScheduler`. Do I need to configure a bean up to the `SpringLockConfigurationExtractor`?

**Comment by lukas-krecan** [comment]
ShedLock needs to get the configuration somewhere. So it's up to you how you will implement the `LockConfigurationExtractor`. You can use thread locals, your tasks can have methods returning  the config, ... . Or you can use this directly https://github.com/lukas-krecan/ShedLock#locking-without-a-framework.

**Comment by malabananharold** [comment]
Thank you. I used the https://github.com/lukas-krecan/ShedLock#locking-without-a-framework and currently not having issues.  Closing this issue. Thanks again.
