### ISSUE TITLE
JdbcTemplateLockProvider cannot be instantiated when useDbTime=true and database is not accessible

### ISSUE THREAD

**Issue by zholub** [lukas-krecan/ShedLock#258]
Sometimes database is not accessible when application starts. In a Spring Boot app, HikariCP can handle this and can postpone it's initialization until the database come up.
This behavior is very useful in dynamic environments (eg Kubernetes) or when the application has specific functions which does not depend on database.

ShedLock selects SQL dialect on the basis of DB connection metadata at startup. With 'useDbTime' is set to true, this prevents application startup as LockProvider cannot be instantiated. 
If 'useDbTime' is set to false and product name couldn't be determined, it falls back to generic SqlStatementsSource. This could cause different behavior with PostgreSQL as it has specific SqlStatementSource also for dbtime-less mode.

One solution can be to allow explict set of databaseProductName to JdbcTemplateLockProvider.Configuration.Builder
Another is to make SqlStatementsSource selection lazy.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Will make SqlStatementsSource lazy.

**Comment by lukas-krecan** [comment]
Released as 4.12.0
