### ISSUE TITLE
@Scope(proxyMode = ScopedProxyMode.TARGET_CLASS) required on one component to make shedlock to work

### ISSUE THREAD

**Issue by oliverlj** [lukas-krecan/ShedLock#261]
Spring boot 2.3.0
shedlock 4.12.0

Hi i have 4 public methods scheduled in services.
3 methods works well, but one is not locked because the service is not a proxy so aop won't work.

I used a workaround 
```
@Scope(proxyMode = ScopedProxyMode.TARGET_CLASS)
```

but i don't know rellay why.

Other Services in dedug show $$enhancedByCglib$$

Maybe add in shedlock documentation Scope annotation ?
Thanks

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. ShedLock uses standard Spring AOP and assumes basic knowledge of how AOP in Spring works. See for example Spring [reference](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#aop-introduction-proxies).
