### ISSUE TITLE
Is it possible to name a lock based on configuration item only available at runtime?

### ISSUE THREAD

**Issue by hirowla** [lukas-krecan/ShedLock#262]
I have a problem with my current system and I have one idea about solving it - maybe you have another.

 I have two different software installations in different locations. They share the same (Mongo) database but each connects to a different replicas - at most, syncing takes 5 minutes guaranteed. The shedlock collection is one of the shared collections.

Now what I think is happening is when a job starts, both installations claim the same lock - neither knows about the other because of the replication delay. In itself that’s ok (each job has a regionId parameter when deciding what work to do). However at some point conflicting updates will occur, which causes some issues.

One resolution I thought of is to have the lock name based on the regionId - then different locks will be created, hence no issue. However the lock name is part of the annotation, which means it can’t be calculated based on this regionId. 

What would be the best way to do this, assuming I can’t change the database configuration? Am I missing something regarding specifying the lock name at runtime?

Thanks,

Ian

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. In Spring you can use SpEL in the annotations so the lock name can be configured or even generated in the runtime.

**Comment by hirowla** [comment]
SpEL looks like it will solve my problem - thanks for the suggestion.
