### ISSUE TITLE
Shedlock nodes synchronization

### ISSUE THREAD

**Issue by mohd-hamdallah** [lukas-krecan/ShedLock#263]
as you mention in the Shedlock documentation:
"locks are time-based and ShedLock assumes that clocks on the nodes are synchronized."

I have a case where i cannot synchronize the clock between different nodes.

so according to my understanding for your documentation, in order to handle this situation:

I have to configure the Shedlock with usingDbTime(), so Shedlock will use database time and do not depend on the nodes clock.

I think this will solve the issue. correct? or i'm missing something?

**Comment by lukas-krecan** [comment]
Yes, that's correct.

**Comment by aaiezza** [comment]
This is great information. However, is there an option to do this with other Lock Providers?
For instance, DynamoDB?
