### ISSUE TITLE
vertx support

### ISSUE THREAD

**Issue by zhengfc** [lukas-krecan/ShedLock#277]
Is it possible vert.x support?

**Describe the solution you'd like**
For example, in vert.x with mysql, we can create ```AsyncSQLClient``` with ```MySQLClient.createShared(vertx, config);```

**Comment by lukas-krecan** [comment]
No, it's not suported unless you are able to extract DataSource from the client

**Comment by zhengfc** [comment]
> No, it's not suported unless you are able to extract DataSource from the client

I see the vertx doc again, it also can create client from datasource
[vert.x jdbc client doc](https://vertx.io/docs/vertx-jdbc-client/java/#_specifying_a_data_source)
```
SQLClient client = JDBCClient.create(vertx, dataSource);
```
