### ISSUE TITLE
Shedlock jdbc-template provider wont update existing locks created by other hosts

### ISSUE THREAD

**Issue by avallen** [lukas-krecan/ShedLock#28]
It fails with an exception when inserting lock due to existing entry by other host (which is not reflected in its in-memory set of locks it knows about), then fails to retry with update. 

This prevents acquiring locks where another host left a stale lock entry - even if expired the other host wont be able to acquire the lock.

**Comment by lukas-krecan-lt** [comment]
Hi thanks for feedback. It's not likely, if the insert fails, it's followed by an update and if lock_until < now the lock is obtained.
