### ISSUE TITLE
Issue with locking multiple tasks 

### ISSUE THREAD

**Issue by sureshpeela83** [lukas-krecan/ShedLock#296]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

**Describe the bug**
1. Which version do you use: 4.9.0
2. Which Lock Provider: jdbc
3. ShedLock configuration 
4. ShedLock logs

**Expected behavior**
We coded multiple scheduled tasks in a single config class but with different task names.
We expect that task1 gets locked and released based on its own locking window and task 2 gets locked and released based 
on its own locking window. But all tasks are getting held using the single locking window. 

**Actual behavior**
When we configure multiple tasks in the configuration class, all tasks are getting locked at once and released at once. We would expect that the every task follows its own lock duration since they have different schedules.

**Comment by lukas-krecan** [comment]
Sorry, I do not understand. What is a locking window? How do you know that all tasks are locked at once,?

**Comment by sureshpeela83** [comment]
Sorry, please see the screen shot of the tasks. How is that they all are getting locked between the same time stamp while they run at different times.
![image](https://user-images.githubusercontent.com/67975434/86940282-99ab4f80-c110-11ea-984b-a8eca25f75bb.png)

**Comment by sureshpeela83** [comment]
processDocumentTask and processDeliveryTask are two separate batch jobs running at their own schedules. But if you see the lockated at and locked until, they are all getting updated with the same locking window 3:31:21 to 3:31:06  .. cant each job have its own locked at and locked until?

**Comment by lukas-krecan** [comment]
I see, the was a bug in 4.9.0, please use the newest version.
