### ISSUE TITLE
Looking for XML based configuration for the same.

### ISSUE THREAD

**Issue by IMaulinPatel** [lukas-krecan/ShedLock#299]
Hi,
Do we have an XML based configuration to implement ShadLock over my scheduler? I am not using core spring. My application is built on Liferay and I am using Liferay spring portlet.

**Comment by lukas-krecan** [comment]
There used to be support for XML config up to ShedLock 2.6.0. So you can either use old version or use this https://github.com/lukas-krecan/ShedLock#locking-without-a-framework
