### ISSUE TITLE
Lock information is not getting created in postgresql

### ISSUE THREAD

**Issue by Amansingh28** [lukas-krecan/ShedLock#315]
Hi,

I am trying to learn Shedlock and it's locking mechanism. I tried creating a lock using "Locking without framework" feature using below code - 

	@Scheduled(cron = "0 */5 * * * ?")
	public void run() {
		LockingTaskExecutor executor = new DefaultLockingTaskExecutor(lockProvider);
		Runnable command = () -> {
			Instant lockAtMostUntil = Instant.now().plusSeconds(14);
			LockConfiguration lockConfiguration = new LockConfiguration("my_lock", lockAtMostUntil);
			executor.executeWithLock((Runnable) () -> doUpdate(), lockConfiguration);

		};
		System.out.println("Running Scheduler");
	}

	private void doUpdate() {
		try{
			System.out.println("Before sleep");
			Thread.sleep(120000);
			System.out.println("After sleep");
		} catch (InterruptedException ie){
			ie.printStackTrace();
		}
	}

My spring boot application is getting started successfully without any error but somehow no lock record is getting created in the shedlock table present in my postgresql database. Also the print statements present in doUpdate() is not getting executed.

Vesrions used:
Spring Boot - 2.2.6.RELEASE
Shedlock - 4.12.0
Postgresql - 42.2.14

Please suggest if I am missing something.

Thanks in advance!

**Comment by lukas-krecan** [comment]
I do not see where is `command.run()` executed.
