### ISSUE TITLE
Update to couchbase java-client 3.0.5

### ISSUE THREAD

**Issue by blitzenzzz** [lukas-krecan/ShedLock#316]
**Is your feature request related to a problem? Please describe.**
I'm using spring boot and recently updated to the latest version, which includes an update from couchbase sdk 2.7 to 3.0.

**Describe the solution you'd like**
Either update to java-client 3.0.5 or start using spring boot and let that dependency handle itself.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I have been already looking at it, but I was not sure if anyone is using ShedLock with Couchbase. Couchbase SDK 3 is not backward compatible and the changes are quite big, so the migration is not as easy as it sounds. If you (or anybody else reading this) want to send a pull-request, I would recommend to do it in the following way.

1. Copy current couchbase provider module under different name ideally `shedlock-provider-couchbase-javaclient3` (this will allow to do it in backward compatible way)
2. Upgrade the code so it works with couchbase 3
3. Make sure the tests pass
4. Send the PR
5. Prosper

**Comment by blitzenzzz** [comment]
I'm migrating my own app and trust me, I understand just how "easy" it is. Let me talk to the powers that be about my time and priorities.

**Comment by blitzenzzz** [comment]
https://github.com/lukas-krecan/ShedLock/pull/323
