### ISSUE TITLE
Include pid in lockedBy to support multiple instances on the same host

### ISSUE THREAD

**Issue by candrews** [lukas-krecan/ShedLock#317]
**Is your feature request related to a problem? Please describe.**
Currently, `lockedBy` defaults to the host name. For example, see https://github.com/lukas-krecan/ShedLock/blob/5a4dc62c76b66a7bb94b2f3d476989c37c833aa1/providers/jdbc/shedlock-provider-jdbc/src/main/java/net/javacrumbs/shedlock/provider/jdbc/JdbcStorageAccessor.java#L54

If two instances of the same application are running on the same host, then both instances will use the same `lockedBy` resulting in incorrect behavior.

**Describe the solution you'd like**
It would be nice if `lockedBy` could include information uniquely identifying the instance of the JVM, for example, the PID.
On Java 9, you can get the pid using [ProcessHandle](https://docs.oracle.com/javase/9/docs/api/java/lang/ProcessHandle.html#pid--):
```java
java.lang.ProcessHandle.current().pid()
```
Spring Boot gets the pid in a different way, from https://github.com/spring-projects/spring-boot/blob/v2.3.2.RELEASE/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/system/ApplicationPid.java#L54 :
```java
private String getPid() {
	try {
		String jvmName = ManagementFactory.getRuntimeMXBean().getName();
		return jvmName.split("@")[0];
	}
	catch (Throwable ex) {
		return null;
	}
}
```

**Describe alternatives you've considered**
When constructing the lock provider, the `lockBy` value can be provided, for example:
```java
new JdbcTemplateLockProvider(
		JdbcTemplateLockProvider
		.Configuration
		.builder()
		.withLockedByValue(java.lang.ProcessHandle.current().pid() + "@" + net.javacrumbs.shedlock.support.Utils.getHostname())
		.build());
```

However, I think this behavior should be in place by default.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. The use-cases for ShedLock vary and it's hard to say what behavior should be the default one. Some people are deploying JVM using Kubernetes and in Docker the PID is usually useless information. So, if the configuration you have described in the alternative section is working for you, I would keep the default as is.

Out of curiosity, what are you using `lockedBy` column for?

**Comment by candrews** [comment]
> Some people are deploying JVM using Kubernetes and in Docker the PID is usually useless information.

Hostname alone is not unique. If I run 2 instances of my application on my system right now, both will show the same hostname.

PID alone is also not unique. If I run my application in docker or k8s two times, both instances will report the same pid: `1`.

But, hostname+pid is (I believe) always unique. On docker and k8s, each running container has a uniquely generated hostname, so hostname+pid is unique there. And on more traditional systems, pid is always unique, so hostname+pid is unique.

Therefore, if the default value of `lockedBy` is changed to be pid+hostname, it will always be unique no matter which mechanism is used to run the application, which is how it should be.



> Out of curiosity, what are you using `lockedBy` column for?

I'm running the same application on my system twice. I expected one instance of the application to get the lock - but instead, both instances are able to get the lock (which is clearly bad :) ). I tracked the cause down to both instances having the same `lockedBy` value.

**Comment by lukas-krecan** [comment]
> both instances are able to get the lock (which is clearly bad :) ).

If this is true, it's a bug. You should not be able to get lock if `lockUntil` is in the future regardless the `lockedBy` value. Are you sure about it? Which lock provider and version are you using?

**Comment by lukas-krecan** [comment]
In other words `lockedBy` is used only for debugging purposes (except a special case of extending a lock in some lock providers)

**Comment by candrews** [comment]
> except a special case of extending a lock in some lock providers

That's the exact scenario I'm dealing with. I'm extend JDBC locks, and `lockedBy` is used in that case.

**Comment by lukas-krecan** [comment]
I still do not understand. How are you able to extend a lock that was obtained in different process?
