### ISSUE TITLE
Unexpected LockConfiguration state

### ISSUE THREAD

**Issue by candrews** [lukas-krecan/ShedLock#318]
The current, non-deprecated `LockConfiguration` constructor uses only Duration arguments: https://github.com/lukas-krecan/ShedLock/blob/shedlock-parent-4.12.0/shedlock-core/src/main/java/net/javacrumbs/shedlock/core/LockConfiguration.java#L45

This implies that it isn't tied to the current time. Yet, it is. This constructor calls `ClockProvider.now()` and saves that result: https://github.com/lukas-krecan/ShedLock/blob/shedlock-parent-4.12.0/shedlock-core/src/main/java/net/javacrumbs/shedlock/core/LockConfiguration.java#L56

This unexpected internal state means that a `LockConfiguration` cannot be reused and cannot be static initialized which I found to be unexpected.

I believe that the fix is to remove the `LockConfiguration.createdAt` field and change the `LockConfiguration.getLockAtMostUntil` and `LockConfiguration.getLockAtLeastUntil` methods to calculate based on `ClockProvider.now()` instead of `createdAt`.

**Describe the bug**
I'm using shedlock `4.12.0` with the `JdbcTemplateLockProvider`

Using this Spring configuration:
```java
import java.time.Duration;

import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.scheduling.annotation.Scheduled;

import lombok.NonNull;
import lombok.extern.slf4j.Slf4j;
import net.javacrumbs.shedlock.core.LockConfiguration;
import net.javacrumbs.shedlock.core.LockProvider;
import net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateLockProvider;
import net.javacrumbs.shedlock.spring.annotation.EnableSchedulerLock;

@Configuration
@EnableScheduling
@EnableSchedulerLock(defaultLockAtMostFor = "PT10M")
@Slf4j
public class TestSchedulingConfiguration {
	@Bean("alphaLockProvider")
	public LockProvider alphaLockProvider(final @NonNull DataSource dataSource) {
		return new JdbcTemplateLockProvider(JdbcTemplateLockProvider.Configuration.builder()
				.withJdbcTemplate(new JdbcTemplate(dataSource))
				.withLockedByValue("ALPHA")
				.build());
	}

	@Bean("betaLockProvider")
	public LockProvider betaLockProvider(final @NonNull DataSource dataSource) {
		return new JdbcTemplateLockProvider(JdbcTemplateLockProvider.Configuration.builder()
				.withJdbcTemplate(new JdbcTemplate(dataSource))
				.withLockedByValue("BETA")
				.build());
	}

	private static final LockConfiguration LOCK_CONFIGURATION = new LockConfiguration(
		"lock",
		Duration.ofSeconds(10),
		Duration.ofSeconds(10));

	@Autowired
	@Qualifier("alphaLockProvider")
	private LockProvider alphaLockProvider;

	@Autowired
	@Qualifier("betaLockProvider")
	private LockProvider betaLockProvider;

	@Scheduled(fixedRateString = "PT5S")
	public void doLocking() {
		alphaLockProvider.lock(LOCK_CONFIGURATION)
			.ifPresentOrElse(lock -> {
				log.info("ALPHA got the lock");
			},
			() -> {
				log.info("ALPHA nope the lock");
			});

		betaLockProvider.lock(LOCK_CONFIGURATION)
			.ifPresentOrElse(lock -> {
				log.info("BETA got the lock - THIS SHOULD NEVER HAPPEN");
			},
			() -> {
				log.info("BETA nope the lock");
			});
	}
}
```

**Expected behavior**
The log output is expected to be:
```
ALPHA got the lock
BETA nope the lock
```
repeating endlessly.

**Actual behavior**
What happened instead:

The actual log output is:
```
ALPHA got the lock
BETA got the lock - THIS SHOULD NEVER HAPPEN
```
repeating endlessly.

**Comment by lukas-krecan** [comment]
This is interesting. The trouble is that `LockConfiguration` is in a common module which is used by multiple lock providers. `JdbcTemplateLockProvider` supports using database time, for which I need the durations (so the code above would actually work). The other lock providers do not support server time (since it is not possible to implement in most of the technologies) so they need the absolute time. 

I did not realize how it may be confusing. Will certainly document that you are not suppose to hold one instance of LockConfiguration. And most likely, I will hide the confusing constructor and create a static factory method which will make it clear in its name. Thanks for reporting it.

**Comment by candrews** [comment]
Is there a way to throw an exception if an attempt is made to use an invalid `LockConfiguration` because it's too old?

It would be ideal for the user to be alerted if they made the same mistake I did :)

**Comment by lukas-krecan** [comment]
I have committed this change https://github.com/lukas-krecan/ShedLock/commit/1e097dd3aa05dd1a4e185a489ea4815b0ac900ee#diff-2dbe9afc7003adf7fa04589d99466f90R65 so it will be much harder to make the same mistake. (Will have to enhance the JavaDoc though)

Throwing an exception may lead to other issues (like in cases where lockAtMosFor is too short)
