### ISSUE TITLE
Error handling in the scenario when associated POD goes down in K8s/ job run fails

### ISSUE THREAD

**Issue by abhishekjoy1** [lukas-krecan/ShedLock#322]
**Is your feature request related to a problem? Please describe.**
I am working on setting up a CRON in multi-pod deployment situation. Here I am using Spring Scheduler with Shedlock. But the problem I am facing here is as follows:

Say, I have to run a CRON job once per day. Now I have three PODs. If one pod crashes while running the job, following issues occur:
  1. the associated lock is not released. 
  2. There is no way other than checking log/monitor to find if any given run is successful.
  2. The job will only again run the following day by one of the available PODs.

**Describe the solution you'd like**
I have been thinking of the following solutions:

 1. to implement some kind of heartbeat mechanism to release the lock when associated instance is not UP.
 2. to capture the status of last  job run: if it is a SUCCESS/FAILURE with minimum status information
3. To retry a given job run in case of failure up to certain times.

**Describe alternatives you've considered**
As of now due to this limitation, we have made the CRON expression to run this job 3 times per day, so that all three PODs get the opportunity to run the job. In that case, the probability of eventual success is more, given underlying operation is idempotent.

**Additional context**

**Comment by lukas-krecan** [comment]
Hi, it seems you need a full-fledged scheduler, ShedLock is just a simple lock so I have to recommend you to use some other library.
