### ISSUE TITLE
significance of LockAssert 

### ISSUE THREAD

**Issue by abhishekjoy1** [lukas-krecan/ShedLock#329]
**Is your feature request related to a problem? Please describe.**

I am raising this issue for one clarification, being a newbie. In the scheduler code mentioned in the example, the first line is as below:

     `LockAssert.assertLocked();`

According to my understanding, the job can be scheduled on any of the given pod at a given time, when the lock is held by the pod itself. 

So, the above line will get executed only if the associated POD has the lock. With this logic, I think the `LockAssert` line is redundant.

Please correct me, if I am wrong. Also, it would be great if you give one small example when things will break if I don't add this line.

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/ShedLock#lock-assert

**Comment by abhishekjoy1** [comment]
Hi @lukas-krecan , yeah I saw this. To prevent misconfiguration errors, we can assert that the lock works by using LockAssert.

But I don't quite understand what is meant by **misconfiguration error**. Is it possible to give one very small example?
