### ISSUE TITLE
Warning log using ElasticSearch plugin

### ISSUE THREAD

**Issue by jrevol** [lukas-krecan/ShedLock#331]
version: 4.14.0
provider: shedlock-provider-elasticsearch
config: @EnableSchedulerLock(defaultLockAtMostFor = "1m")

Shedlock work properly but in the next release, Elasticsearch 8.X, Elastic will no longer support the "type" of document in their databases so the in the path /shedlock/lock/, the 'lock' should be remove (because you will not be able to put different document type in the same index)

for now we have this warning message on each use: 
`2020-09-15 12:55:03.041  WARN 56140 --- [   scheduling-1] org.elasticsearch.client.RestClient      : request [POST http://localhost:9200/shedlock/lock/testTask/_update?timeout=1m] returned 1 warnings: [299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 "[types removal] Specifying types in document update requests is deprecated, use the endpoint /{index}/_update/{id} instead."]
`
this part could be removed now to avoid problems in next release

**Comment by lukas-krecan** [comment]
Hi, thanks a lot for reporting. Currently I am busy. Can you please provide a PR? Or maybe the original committer @florian-perrotti?

**Comment by jrevol** [comment]
for now, to make the warning disapear, you can instantiate the provider with index type "_doc" which is the current default for elastic for compatibility:
`    @Bean
    public ElasticsearchLockProvider lockProvider(RestHighLevelClient restHighLevelClient) {
        return new ElasticsearchLockProvider(restHighLevelClient,"_doc");
    }`

**Comment by lukas-krecan** [comment]
It's not clear how to clenly migrate:

1. I can change the default type - but this will create a multi-type index
2. I can make the constructor with the type deprecated - this would prevent users to apply the workaround mentioned above

The best approach most likely is to remove the constructor with type and stop using the type altogether, but I am not sure what would be the consequece, if there is already a lock in the index with the old type.

**Comment by lukas-krecan** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html
