### ISSUE TITLE
Shouldn't there be a write concern in MongoLockPrivider ?

### ISSUE THREAD

**Issue by dortelecan** [lukas-krecan/ShedLock#333]
https://github.com/lukas-krecan/ShedLock/blob/42c745554fd9bc8cf2042b912a6f8179ec035204/providers/mongo/shedlock-provider-mongo/src/main/java/net/javacrumbs/shedlock/provider/mongo/MongoLockProvider.java#L73

Probably a stupid question:

If we have multiple mongo db nodes (multiple replicas/sharded nodes), does the MongoLockProvider work correctly ? I cannot see a write concern in there, I was expecting a w: majority ?!

**Comment by lukas-krecan** [comment]
It's up to you to decide what write concern you prefer. You can set in for the `MongoCollection` you pass in to the LockProvider
