### ISSUE TITLE
Consul Provider does not destroy the session when locking was unsuccessful

### ISSUE THREAD

**Issue by haraldpusch** [lukas-krecan/ShedLock#340]
**Describe the bug**
Using ConsulLocking Provider Version 4.15.0 with Spring.
Configuration:
Using `@EnableSchedulerLock(defaultLockAtMostFor = "PT1h")` on config class and `@SchedulerLock(name = CONSUL_SYNCHRONIZATION_LOCK)` on Scheduled Method

ShedLock logs (lock name redacted):
```
DEBUG n.j.s.p.consul.ConsulLockProvider - Destroying session 87270cbf-844b-c169-c991-b0fa3b53ef1a 
DEBUG n.j.s.c.DefaultLockingTaskExecutor - Task finished, lock '****/Lock' released 
DEBUG n.j.s.p.consul.ConsulLockProvider - Acquired session fefe792b-7766-c07b-5b35-ec41fa701f45 for 3600 seconds 
DEBUG n.j.s.c.DefaultLockingTaskExecutor - Not executing '****/Lock'. It's locked.
```

**Expected behavior**
When the lock could not be acquired, the consul session should be destroyed.

**Actual behavior**
Trying to acquire a Lock opens a new session, when the resources is already locked, the session is never closed by the LockProvider.
Session destruction works fine when the lock could be akquired - the session is destroyed correcty when the lock is being released by the LockProvider.
This causes a huge amount of unnecessary (and - as far as I can see - unobtainable) sessions to be created. These Sessions are also not released on application shutdown either.

**Comment by haraldpusch** [comment]
I should be able to write a fix for this tomorrow and open a PR here. Are there any specific contribution guidelines I should follow?

**Comment by lukas-krecan** [comment]
Thanks a lot. There are no guidelines, just send to PR.
