### ISSUE TITLE
Extend Lock multiple times

### ISSUE THREAD

**Issue by arturtech97** [lukas-krecan/ShedLock#344]
**Is your feature request related to a problem? Please describe.**
My Usecase: If a thread successfully acquires a lock, he looks for jobs, if jobs are available he processes a batch of them, if not he sleeps. If the batch processing time was too short he sleeps after processing the batch. After processing or sleeping if the lock is still valid (now()<lock_until) the thread extends his lock. The thread keeps the lock either until something bad happens (e.g. server instance crashes) or if the batch processing took longer than expected.

Currently I get: 
java.lang.IllegalStateException: Lock is not valid, it has already been unlocked or extended
	at net.javacrumbs.shedlock.core.AbstractSimpleLock.checkValidity(AbstractSimpleLock.java:63) ~[shedlock-core-4.15.1.jar:na]
	at net.javacrumbs.shedlock.core.AbstractSimpleLock.extend(AbstractSimpleLock.java:51) ~[shedlock-core-4.15.1.jar:na]
	at net.javacrumbs.shedlock.core.AbstractSimpleLock.extend(AbstractSimpleLock.java:46) ~[shedlock-core-4.15.1.jar:na]

**Describe the solution you'd like**
Possibility to extend lock multiple times. So if a lock was extended after some time extend the lock again, such that now()<lock_until

Is this possible? Thank you :)

**Comment by lukas-krecan** [comment]
Hi, as the [documentation](https://github.com/lukas-krecan/ShedLock/blob/70b5ade08cb9e2e6954600b748f42359d3fe757a/shedlock-core/src/main/java/net/javacrumbs/shedlock/core/SimpleLock.java#L49) says, once you extend the lock, new one will be returned and the old one can not be used again. So just use the lock that is returned from the `extend` method for further extensions.
