### ISSUE TITLE
Warning vs error trying to create a lock

### ISSUE THREAD

**Issue by ae-govau** [lukas-krecan/ShedLock#345]
We were caught out last week with tasks failing to execute due to our code constructing a name that was too long.

What surprised is is the this condition didn't bubble up an exception or an ERROR message, rather it behaved in I think the same manner as if no lock was acquired (such as the lock already acquired elsewhere). 

ie we can see this code:

https://github.com/lukas-krecan/ShedLock/blob/master/providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/JdbcTemplateStorageAccessor.java#L71

logs a warning, rather than raising an exception or printing an error.

**Expected behavior**

In our case, we would have preferred an Exception be thrown - we were calling it directly with `executeWithLock()` and an Exception would have made it clearer to us that wasn't working.

Alternatively, if that's too big a change, it would have been helpful to log it at ERROR level. Our logging setup emits metrics by log level, and any emitted ERRORs would have gotten our attention to it much quicker.

**Actual behavior**

Logged at WARN message only. The stack trace is printed, which is helpful, but my feeling is the log level at minimum should be higher.

Happy to submit a PR to change the log message to ERROR. Wanted to check first if this had been considered and rejected before.

(Thanks for a great library!)

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. The behavior is [intentional](https://github.com/lukas-krecan/ShedLock/commit/ee099bb31f65b6df37104490e2ccb9f1dd9dd3e9) but to be honest, I do not remember the reasoning behind the decision. Feel free to send the PR, logging it as ERROR definitely makes sense.
