### ISSUE TITLE
Surviving node cannot obtain the lock as soon as possible

### ISSUE THREAD

**Issue by xingxingge** [lukas-krecan/ShedLock#347]
When the node holding the lock dies, the surviving node cannot obtain the lock as soon as possible until lockAtLeastFor. There is no problem when integrated with spring.My version is 4.12.0，and the provider is zookeeper.
code:

```java
package test

import net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor;
import net.javacrumbs.shedlock.core.LockConfiguration;
import net.javacrumbs.shedlock.core.LockProvider;
import net.javacrumbs.shedlock.core.LockingTaskExecutor;
import net.javacrumbs.shedlock.provider.zookeeper.curator.ZookeeperCuratorLockProvider;
import org.apache.curator.framework.CuratorFramework;
import org.apache.curator.framework.CuratorFrameworkFactory;
import org.apache.curator.retry.RetryNTimes;
import org.junit.Test;

import java.time.Duration;
import java.util.Date;

public class lockProviderTest {

  @Test
  public void test1() throws InterruptedException {


    CuratorFramework client = CuratorFrameworkFactory
        .newClient("localhost:2181", new RetryNTimes(10, 5000));
    client.start();
    LockProvider lockProvider= new ZookeeperCuratorLockProvider(client, "/wangee");

    LockingTaskExecutor executor = new DefaultLockingTaskExecutor(lockProvider);


//    Instant lockAtMostUntil = Instant.now().plusSeconds(600);
    Runnable runnable = new Runnable() {
      @Override
      public void run() {
        System.out.println(new Date()+" execute begin...");
        try {
          Thread.sleep(2000);
          System.out.println(new Date()+" execute finished...");
        } catch (InterruptedException e) {
          e.printStackTrace();
        }
      }
    };

    while(true){
      Thread.sleep(5000);
      executor.executeWithLock(runnable, new LockConfiguration("lockName",Duration.ofSeconds(60),Duration.ofSeconds(5)));
    }
  }
}
```

**Comment by lukas-krecan** [comment]
Hi, sorry, I do not understand. Can you please explain what result are you expecting and what are you getting instead?

**Comment by xingxingge** [comment]
See the code above, when the client holding the lock dies, the surviving client gets the lock after 60s.But  in the integration test with spring, the surviving client obtained the lock after 5s. Why are the results different in these two cases?

spring code:

@Scheduled(fixedDelayString = "5000", initialDelayString = "5000")
  @SchedulerLock(name = "jobDeleteTask",
      lockAtLeastFor = "5000",
      lockAtMostFor = "60s")

**Comment by lukas-krecan** [comment]
There is a difference between a node dying and task finishing. If the tasks finishes, it releases the lock (unless `lockAtLeast` specifies otherwise). If the node dies, the behavior is different a the lock is held for `lockAtMost`.

**Comment by xingxingge** [comment]
> There is a difference between a node dying and task finishing. If the tasks finishes, it releases the lock (unless `lockAtLeast` specifies otherwise). If the node dies, the behavior is different and the lock is held for `lockAtMost`.

I means,the two cases is whether integrated with spring,not dying and task finishing.

**Comment by xingxingge** [comment]
> There is a difference between a node dying and task finishing. If the tasks finishes, it releases the lock (unless `lockAtLeast` specifies otherwise). If the node dies, the behavior is different and the lock is held for `lockAtMost`.



> There is a difference between a node dying and task finishing. If the tasks finishes, it releases the lock (unless `lockAtLeast` specifies otherwise). If the node dies, the behavior is different and the lock is held for `lockAtMost`.


I mean, this is not the difference between node death and task completion, but whether spring is integrated.
