### ISSUE TITLE
@ScheduledLock not working for all methods when using default PROXY_METHOD interceptMode

### ISSUE THREAD

**Issue by gewuerzgurke84** [lukas-krecan/ShedLock#350]
Hi there,

I think I just found a bug where not all method invocations are correctly intercepted when using the default interceptMode (PROXY_METHOD). After switching to PROXY_SCHEDULER all method invocations seem to be intercepted.

I have several spring components that use @Scheduler(cron = ...) together with @SchedulerLock:
```
@Component
@DependsOn({"cassandraLoader","kafkaAlarmConsumer"})
@ConditionalOnProperty(value = "notifyEvents.enabled", havingValue = "true")
public class NotifyEventsHandler extends CamsBasicHandler {
@Scheduled(cron = "${notifyEvents.checkCron}")
    @SchedulerLock(name = "NotifyEventsHandler_checkNotification")
    @Transactional
    public void checkNotification() {
      // impl code
    }
}

@Component
@ConditionalOnProperty(value = "notifyEvents.enabled", havingValue = "true")
public class NotifyEventsTelephoneAction {
@Scheduled(cron = "${notifyEvents.checkStatusCron}")
    @SchedulerLock(name = "NotifyEventsTelephoneAction_syncTelehoneStatus")
    @Transactional
    public void syncTelehoneStatus() {
       // impl code
    }
}
```
I do not understand why the @SchedulerLock works as expected for bean (NotifyEventsTelephoneAction) but does not intercept/lock method invocations for the first bean (NotifyEventsHandler)

I've @EnableSchedulerLock and a jdbcTemplateLockProvider configured and can see that there are no entries in the shedlock table on for NotifyEventsHandler_checkNotification

Furthermore I added breakpoints and found that DefaultLockingTaskExecutor#executeWithLock only works with one of two beans.

After switching to PROXY_SCHEDULER everything works as expected. 
Please let me know with information would be useful for analyzing this issue...

Best Regards,
 Alex

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. ShedLock by default uses Spring [AOP](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#aop-introduction-spring-defn) so if Spring AOP fails, ShedLock fails as well. Can you please check that the Transactional annotation works? Moreover, Spring usually logs if AOP fails (sometimes on INFO) so you can check the logs.

It works with PROXY_SCHEDULER since it does not depend on AOP.

**Comment by gewuerzgurke84** [comment]
I've set PROXY_METHOD again and added logging level debug for `org.springframework.aop`. Unfortuenetely there is nothing in the logs from aop, is there any other way how to configure logging for aop itsself properly?

**Comment by lukas-krecan** [comment]
I am afraid I can not help you with that, I do not remember it and I do not have time to find it out. If you add a break-point, do you see the Transactional proxy?

**Comment by lukas-krecan** [comment]
Or you can try changing the AOP mode by [this](https://github.com/lukas-krecan/ShedLock/blob/master/spring/shedlock-spring/src/main/java/net/javacrumbs/shedlock/spring/annotation/EnableSchedulerLock.java#L80).

**Comment by gewuerzgurke84** [comment]
Okay, I think for some reason spring aop ignores first method invocation:

(works)
![works](https://user-images.githubusercontent.com/29427019/98791499-70276b00-2405-11eb-9e2c-5dd8e528f826.PNG)

(doesn't work)
![doesnwork](https://user-images.githubusercontent.com/29427019/98791528-787fa600-2405-11eb-911d-fef86a0a7046.PNG)

**Comment by lukas-krecan** [comment]
I will close it, since it does not seem to be ShedLock related. Feel free to reopen.

**Comment by lukas-krecan** [comment]
Out of curiosity, did you find the reason?
