### ISSUE TITLE
The 'order' of ShedLock's "Scheduled Method proxy"

### ISSUE THREAD

**Issue by XiPengyuan** [lukas-krecan/ShedLock#354]
Is there any way to change the order of ShedLock's proxy? By default, the order of the proxy created by ShedLock should always be `Ordered.LOWEST_PRECEDENCE`, right?
If I want to add my own proxy before ShedLock's proxy, there is no problem. But if I want to add my own proxy behind ShedLock's proxy, how should I increase the priority of ShedLock's proxy?

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I can take a look at this. Are you using PROXY_SCHEDULER or PROXY_METHOD?

**Comment by XiPengyuan** [comment]
Thank you for responding to me so quickly.
I did not specify the `interceptMode`. So I think I used the default one: `PROXY_METHOD`.

**Comment by lukas-krecan** [comment]
I can add support for specifying order (see e88993e) But it seems that AspecJ AOPs are executed before Spring AOPs so your interceptor can not be created using AspectJ.

**Comment by lukas-krecan** [comment]
Released as 4.16.0
