### ISSUE TITLE
Extend ShedLock to be used as an API key.

### ISSUE THREAD

**Issue by sandeep-kumar3-by** [lukas-krecan/ShedLock#355]
Hi Lukas,
Can I extend this shedLock library to be used as a shared lock per API request basis,  consider the below example:-
let say I have an API called updateTxn which takes a request such that {"reqID":"x","payload":{bla-bla}}
can I extend shedLock to be used as below:-
1). {"reqID":"x","payload":{bla-bla1}} ----> updateTxn {in progress}
2). {"reqID":"x","payload":{bla-bla2}}----->blocked since above one is already in progress.

3). {"reqID":"y","payload":{foo-bar}}----->served since key is Y and resource is only blocked for x

**Comment by lukas-krecan** [comment]
Please, ask questions on StackOverflow.
