### ISSUE TITLE
Pass consul acl token to session creation

### ISSUE THREAD

**Issue by DrWifey** [lukas-krecan/ShedLock#358]
I've spent some time on searching why configuration via consul doesn't work and discovered that the provided token isn't being pass to a consul client.
Discovered in class `net.javacrumbs.shedlock.provider.consul.ConsulLockProvider`
But since the method `createSession` is private I just copied `ConsulLockProvider`, `ConsulSimpleLock` classes to my project and modified the required method. I didn't test the whole functionality, just the `createSession` method, but session now is creating successfully. Maybe you could add this as a feature that will work out-of-the-box?

What I've done so far:

```
    private final String aclToken;
    // Also added this to constructor

   private String createSession(LockConfiguration lockConfiguration) {
        long ttlInSeconds = Math.max(lockConfiguration.getLockAtMostFor().getSeconds(), minSessionTtl.getSeconds());
        NewSession newSession = new NewSession();
        newSession.setName(lockConfiguration.getName());
        newSession.setLockDelay(0);
        newSession.setBehavior(Session.Behavior.DELETE);
        newSession.setTtl(ttlInSeconds + "s");
        String sessionId = consulClient.sessionCreate(newSession, QueryParams.DEFAULT, aclToken).getValue(); //passing aclToken here
        logger.debug("Acquired session {} for {} seconds", sessionId, ttlInSeconds);
        return sessionId;
    }
```

**Comment by lukas-krecan** [comment]
Thanks for feedback, I will add the token parameter

**Comment by lukas-krecan** [comment]
Released as 4.17.0. Enjoy

**Comment by DrWifey** [comment]
Thank you, but if token is required for session creation (as it'd be in most cases), then it's required to all operations, e.g. `consulClient.setKVValue` and `consulClient.sessionDestroy` etc.
Also, would be nice to have an option to set KVValue keyprefix, so the lock key doesn't appear in a root entry of consul.

**Comment by lukas-krecan** [comment]
I see, can you please send a pull-request?

**Comment by DrWifey** [comment]
Okay, I'll do

**Comment by lukas-krecan** [comment]
Btw., if we are going to add additional config properties, maybe a builder as we have in JdbcTemplateProvider might be useful. The constructor is starting to get too many parameters.

**Comment by DrWifey** [comment]
Yeah, I think it'd be better this way
