### ISSUE TITLE
Accessing locks configuration

### ISSUE THREAD

**Issue by zeljko-mirovic** [lukas-krecan/ShedLock#359]
I am writing a Spring Boot based library for monitoring and managing methods annotated with @Sheduled. As we are using ShedLock as a standard solution for scheduled tasks distributed locking I want to include data about ShedLock configuration for those methods.
Reading different methods configuration is easy, but if I want to have default values for lockAtMostFor and lockAtLeastFor, I will end up writing `net.javacrumbs.shedlock.spring.aop.SpringLockConfigurationExtractor` again.
Is it possible to make that class accessible from outside or add another mechanism for retrieving method configuration values?

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback, it makes sense. The class was pubic protected to enable refactoring, but it's been quite stable recently. What would be an ideal interface for you? Something like this 1bcf74402baa5c645d57f90c2329203dc0f6a5aa? Do you want to pass in the annotation or rather targetObject and targetMethod?

**Comment by zeljko-mirovic** [comment]
#1bcf744 looks perefect. Most proabbly I will use `getLockConfiguration(Runnable)`. I can imagine someone else will like other two variants `getLockConfiguration(SchedulerLock)` and `getLockConfiguration(target, Method)`.
Investigating your code further I figured out that I also need to retrieve default values for `lockAtMostFor` and `lockAtLeastFor` which is already done by the `net.javacrumbs.shedlock.spring.aop.AbstractSchedulerLockConfiguration`. To be able to reuse your code completely, it will be nice to have that available too.
In my opinion, it is simplest to expose `SpringLockConfigurationExtractor` as a bean, but any other option will be helpful too.

**Comment by lukas-krecan** [comment]
Thanks. Most likely I will expose `LockConfigurationExtractor` as a bean. Would it be enoug to have access to he `LockConfigurationExtractor` interface? It will take me few days to do.

**Comment by zeljko-mirovic** [comment]
Access to `LockConfigurationExtractor` interface is all I need.
Maybe you can extend that interface with method `getLockConfiguration(Object, Method)` as it is already public in `SpringLockConfigurationExtractor`? I am expecting it will be useful for someone else.

**Comment by lukas-krecan** [comment]
Released as 4.19.0. LockConfigurationExtractor bean should be in the Spring context.

**Comment by zeljko-mirovic** [comment]
Work like a charm. Thank you.
