### ISSUE TITLE
Micronaut support for JdbcTemplate-LockProvider

### ISSUE THREAD

**Issue by sboeingSPA** [lukas-krecan/ShedLock#362]
It is very nice that ShedLock has support for Micronaut as well and not only for Spring.
But sadly I recognized after trying it out that the JdbcTemplate-LockProvider has a dependency on some spring libraries.
Actually I used the library first in my project but then recognized that existing integration tests broke with some `java.sql.SQLException: Connection is closed` even without that the ShedLock library was called but because of the spring dependency.

As a workaround I copied some JdbcTemplate-LockProvider classes to my project and adjusted them for Micronaut. As they are a copy of the Spring-implementation I wouldn't use them directly as a library but implement some common abstraction that is then used by some Spring/Micronaut specific library.
In general the differences between Spring and Micronaut are the `TransactionManager` implementation and that it looks like Micronaut currently doesn't bring support for named SQL-queries.

For 'inspiration' or in case other people need a workaround for this until the JdbcTemplate-LockProvider supports Micronaut I added my files to this issue:
[shedlock.zip](https://github.com/lukas-krecan/ShedLock/files/5659472/shedlock.zip)

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Can you please describe what exactly did not work? [Here](https://github.com/lukas-krecan/ShedLock/tree/master/micronaut/micronaut-test) is a test showing that Micronaut and JdbcTemplateLockProvider work quite well.
