### ISSUE TITLE
Can you support ETCD?

### ISSUE THREAD

**Issue by goudai** [lukas-krecan/ShedLock#366]
Can you support ETCD?

**Comment by lukas-krecan** [comment]
Hi, currently I do not have capacity for that, but you can provide a PR, if you want. It's quite easy, you can get inspiration in one of the other lock providers we have.

**Comment by grofoli** [comment]
@goudai @lukas-krecan I created a pull request for this. @goudai is my implementation something you can make use of?

**Comment by lukas-krecan** [comment]
Released as 4.20.0
