### ISSUE TITLE
Spring Boot 1.5.10 Compatibility

### ISSUE THREAD

**Issue by mohd-hamdallah** [lukas-krecan/ShedLock#369]
My project is a Spring Boot project version 1.5.10 release.

Can I use the Shedlock library in my project by adding the latest version of the dependency *shedlock-spring* version *4.19.0* ?

Note that I found in project github documentation under "Release notes 2.6.0" that you updated dependency to Spring 2.1.9.

Is the version *4.19.0* of  *shedlock-spring* compatible and work without problems with spring boot 1.5.10?

**Comment by lukas-krecan** [comment]
Hi, spring boot 1.5.10 is not [supported](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions) so you are on your own. Some older version od ShedLock should work with it, but I have no idea which one.

**Comment by mohd-hamdallah** [comment]
Hi Lukas,

I know that the spring boot version 1.5.10 is not supported :(

My project is developed before three years and it should go live soon, so I don't have time to upgrade to new spring boot version.

Old implementation is using 2.5 version of your shedlock, but the problem that I need to use the feature usingDbTime which is developed in 4.9.3.

so my question is can I use your library version 4.9.3 with spring boot version 1.5.10 or it is not backward compatible?

Thanks for understanding and support.
