### ISSUE TITLE
How to check lock and set lock to task without annotation

### ISSUE THREAD

**Issue by loefflefarn** [lukas-krecan/ShedLock#37]
Hello,
I have to check the shedlock-state in an managedOperation without the shedlock annotation. Is there any option to handle shedlock without the annotation?

Greetings

**Comment by clamey** [comment]
You can set up a task in spring xml like so:

<task:scheduled-tasks scheduler="scheduler">
    <task:scheduled ref="task" method="run" fixed-delay="1" fixed-rate="1"/>
</task:scheduled-tasks>

The [README](https://github.com/lukas-krecan/ShedLock/blob/master/README.md) has more detail.

If that's not what you're looking for, can you please provide more detail?

Thanks

**Comment by lukas-krecan** [comment]
Hi, I am not sure I understand the question. You can take a look at https://github.com/lukas-krecan/ShedLock/blob/master/shedlock-core/src/main/java/net/javacrumbs/shedlock/core/DefaultLockingTaskExecutor.java if it's what you need. You can call executeWithLock(task, config).

**Comment by loefflefarn** [comment]
Hey - sorry for my bad description, but the answer from @lukas-krecan helped me out! Thanks!
