### ISSUE TITLE
Spring boot 1.5.10

### ISSUE THREAD

**Issue by mohd-hamdallah** [lukas-krecan/ShedLock#370]
Hi Lukas,

I know that the spring boot version 1.5.10 is not supported :(

My project is developed before three years and it should go live soon, so I don't have time to upgrade to new spring boot version.

Old implementation is using 2.5 version of your shedlock, but the problem that I need to use the feature usingDbTime which is developed in 4.9.3.

so my question is can I use your library version 4.9.3 with spring boot version 1.5.10 or it is not backward compatible?

Thanks for understanding and support.

**Comment by lukas-krecan** [comment]
Hi, the LockProvider interface is quite stable, so new LockProvider should work with old shedlock-spring version. But there is no guarantee, and it's up to you to test it for yourself. I really do not have capacity to support obsolete versions.
