### ISSUE TITLE
Can we add more log to ShedLock

### ISSUE THREAD

**Issue by ndLong94** [lukas-krecan/ShedLock#372]
Currently I need to know which instance was skipped by ShedLock. Can we log the event, when the batch job was skipped due to another batch with the same name ran before it.

**Comment by lukas-krecan** [comment]
Something like this https://github.com/lukas-krecan/ShedLock/blob/master/shedlock-core/src/main/java/net/javacrumbs/shedlock/core/DefaultLockingTaskExecutor.java#L88 ?

**Comment by ndLong94** [comment]
@lukas-krecan-lt  So we have it by default? But I dont see any log in the second instance. And can we externalize the properties that set the lock as least for and lock as most for? I need leave them in a properties file

**Comment by lukas-krecan** [comment]
You can use SPeL for the annotation properties
