### ISSUE TITLE
Extend lock inside @Scheduled method

### ISSUE THREAD

**Issue by prayzzz** [lukas-krecan/ShedLock#374]
**Is your feature request related to a problem? Please describe.**
I have a `@Scheduled` method, which processes data in a loop. I can assume how long a single loop will take, but I don't know how many loops need to be done. It depends on the amount of data to be processed.
So the `@Scheduled` method can be done in basically no time, when no data needs to be processed. Or it will take multiple hours, if there's much data to process.

**Describe the solution you'd like**
I would like to use the `extend()` method of `SimpleLock` on every loop inside my `@Scheduled` method to keep the lock up for long runs.
Currently I have found no API of Shedlock which returns the current `SimpleLock` instance to me. It's kept inside `DefaultLockingTaskExecutor.executeWithLock()`.

Since the taskname is already stored in a ThreadLocal variable inside `LockAssert`, I thought about storing the lock there too.
It seems quite simple and easy to access for all ways of usage.

Some other way I could think of, would be to inject the lock as argument into the `@Scheduled` method. But this is quite special and would require some tinkering.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. It's not likely that I will implement such feature. As I see it, there are two categories of users. 

1. Basic - users that are using ShedLock as intended - scheduler lock. I expect them to use the annotations.
2. Advanced - users with various use-cases and various needs. I expect them to use the programatic configuration like [this](https://github.com/lukas-krecan/ShedLock#locking-without-a-framework). The `extend` method has been added for such users.

It seems that your use-case fails somewhere between the two groups, but I would recommend you to use the programmatic approach anyway (see DefaultLockingTaskExecutor for inspiration). 

The reason why I hesitate to add more stuff to the Basic API is the maintenence cost, I am afraid of API bloat.

**Comment by prayzzz** [comment]
Thanks for your answers and I can fully understand your point.

I'll go with providing my own `LockingTaskExecutor` implementation.
