### ISSUE TITLE
shedlock - - Not executing

### ISSUE THREAD

**Issue by NandiniArjun** [lukas-krecan/ShedLock#375]
Hi,

I am using shedlock library 4.20.0.

<dependency>
    		<groupId>net.javacrumbs.shedlock</groupId>
    		<artifactId>shedlock-spring</artifactId>
    		<version>4.20.0</version>
		  </dependency>
		  <dependency>
    		<groupId>net.javacrumbs.shedlock</groupId>
    		<artifactId>shedlock-provider-jdbc-template</artifactId>
    		<version>2.1.0</version>
		  </dependency>

The scheduler job is,
@Scheduled(fixedRate = 5000)
	@SchedulerLock(name = "TaskScheduler__scheduledTask", lockAtLeastForString = "PT5M", lockAtMostForString = "PT14M")
	public void reportCurrentTime() {
		LockAssert.assertLocked();
		log.info("The time is now {} {}", dateFormat.format(new Date()), dataSource);
	}

It shows @SchedulerLock as deprecated.

And the spring boot class,

@SpringBootApplication
@EnableScheduling
@EnableSchedulerLock(defaultLockAtMostFor = "PT30S")
public class DMSCaseEmulatorSpringApplication  {

    public static void main(String[] args) {
        SpringApplication.run(DMSCaseEmulatorSpringApplication.class, args);
    }
}	

When i execute the spring boot class, it triggers shedlock and creates a record in database table but in logs i keep getting as below,
19:54:39.188 [scheduling-1] DEBUG n.j.s.c.DefaultLockingTaskExecutor - Locked TaskScheduler__scheduledTask.
19:54:39.188 [scheduling-1] INFO  u.g.h.c.d.s.ScheduledTasks - The time is now 19:54:39 HikariDataSource (HikariPool-1)
19:54:39.205 [scheduling-1] DEBUG n.j.s.c.DefaultLockingTaskExecutor - Unlocked TaskScheduler__scheduledTask.
19:54:44.065 [scheduling-1] DEBUG n.j.s.c.DefaultLockingTaskExecutor - Not executing TaskScheduler__scheduledTask. It's locked.
19:54:49.062 [scheduling-1] DEBUG n.j.s.c.DefaultLockingTaskExecutor - Not executing TaskScheduler__scheduledTask. It's locked.

Any thoughts will be appreciated?

**Comment by lukas-krecan** [comment]
Duplicate https://stackoverflow.com/questions/65782269/shedlock-not-executing/65794909#65794909
