### ISSUE TITLE
Unable to change the time zone with MongoLockProvider 

### ISSUE THREAD

**Issue by ajithSkr** [lukas-krecan/ShedLock#376]
Hi, currently I am using shedlock with MongoDB, here I am facing an issue that after creation of table and entries the time on the **lockUntil** and **lockedAt** are not correct it is taking **UTC** timezone, I have to use **GMT+5:30**, is there any possibilities to override the configuration, I have look into the readme file but that only contains the way to override if we are using JDBC template but for mongo it is not there, can you please help me out of this

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Can you please explain, why do you need to use GMT+5:30? lockUntil and lockedAt are internal ShedLock values. Moreover, using times in timezones is quite tricky due to daylight saving changes.

**Comment by ajithSkr** [comment]
The locks are perfectly working, but I have asked for viewing purpose because my timezone is different from UTC, while looking into the mongo collection It is little bit difficult to predict the time

**Comment by ajithSkr** [comment]
Any way that's is not a bigger blocker for me
