### ISSUE TITLE
How to test the shedlock with spring scheduler

### ISSUE THREAD

**Issue by driptaroop** [lukas-krecan/ShedLock#377]
1. Which version do you use -> 4.20.0
2. Which Lock Provider -> JdbcTemplate(Postgres)

This is not a bug or issue. This is just a roadblock I faced while trying to test the shedlock integration in my project.

I incorporated Shedlock in my kotlin project with spring following the documentation. I used the default declarative approach using the annotations (`@SchedulerLock`)  which I imagine most of the people using shedlock followed. 

I cannot figure out how to test this. From each scheduler, I am calling a Rest Endpoint. I can maybe,
1. In the test case, startup multiple spring context in different threads. Then monitor how many times the endpoint is being called. I tried this but the schedulers are stopping after couple of seconds with or without some exception.
2. Starting up 2 different instances of the application in container and test the api calls. I'm yet to try this one.

I am very curious to know how the community tests this or if there is any testing solution provided in the Shedlock.

**Comment by lukas-krecan** [comment]
What exactly do you want to test? That ShedLock works? That it's well configured? That your application works? My experience is that if I am able to clearly answer the question about what I want to test, the test is straightforward.
