### ISSUE TITLE
Support for maintaining run history. 

### ISSUE THREAD

**Issue by anandaverma** [lukas-krecan/ShedLock#4]
Would be good to maintain run history of jobs also some way to identify which node is running the job.

**Comment by lukas-krecan-lt** [comment]
Hi, tanks for feedback. Node running the job is stored in the shedlock table/collection. I'd to keep the library minimal, so if you need job history, I recommend implementing [LockProvider](https://github.com/lukas-krecan/ShedLock/blob/master/shedlock-core/src/main/java/net/javacrumbs/shedlock/core/LockProvider.java) wrapper where you can store whatever you want.

**Comment by anandaverma** [comment]
Sure, I will add and create a PR. If you think its useful do merge.

**Comment by timlevett** [comment]
You could just add a trigger on your table for on insert that does an insert into a history table. If one was so inclined.
