### ISSUE TITLE
Config documentation issue

### ISSUE THREAD

**Issue by giovanni-landolina** [lukas-krecan/ShedLock#41]
I tried to configured my Spring env, as documented in the "Configure the task scheduler" paragraph (the ScheduledLockConfiguration bean provider), but this way, I noticed my Tomcat was unable to stop gracefully, due to the error 
"The web application [xyz] appears to have started a thread named [ThreadPoolTaskScheduler-X] but has failed to stop it. This is very likely to create a memory leak."

I worked around it by using a different configuration:

    @Bean
    public TaskScheduler taskScheduler(LockProvider lockProvider) throws Exception {
        ScheduledLockConfiguration schedulerConfig = (ScheduledLockConfigurationBuilder
                        .withLockProvider(lockProvider)
                        .withPoolSize(10)
                        .withDefaultLockAtMostFor(Duration.ofMinutes(10))
                        .build());
        SpringLockableTaskSchedulerFactoryBean configBean = (SpringLockableTaskSchedulerFactoryBean) schedulerConfig;
        return configBean.getObject();
    }

This way, it all looks working as expected.

**Comment by lukas-krecan** [comment]
Hi, thanks for reporting it. If it's the case, it's not a documentation issue but a bug. Will take a look at it.

**Comment by lukas-krecan** [comment]
Should be fixed in 0.16.1

**Comment by lukas-krecan** [comment]
In 0.16.1, TaskExecutor should be closed when configured as documented. Thanks again for reporting it.
