### ISSUE TITLE
Support for DataDog Spring Scheduling Integration

### ISSUE THREAD

**Issue by iwanryszard** [lukas-krecan/ShedLock#419]
Currently SchedLock doesn't work if you are using DataDog for Application Performance Monitoring. DataDog wraps the ScheduledMethodRunnable into [SpringSchedulingRunnableWrapper](https://github.com/DataDog/dd-trace-java/blob/75d55f167e5571639b0868503ea6d379ee35e8d9/dd-java-agent/instrumentation/spring-scheduling-3.1/src/main/java/datadog/trace/instrumentation/springscheduling/SpringSchedulingRunnableWrapper.java). As a result the `if (task instanceof ScheduledMethodRunnable)` check in **getLockConfiguration** [SpringLockConfigurationExtractor](https://github.com/lukas-krecan/ShedLock/blob/master/spring/shedlock-spring/src/main/java/net/javacrumbs/shedlock/spring/aop/SpringLockConfigurationExtractor.java) returns false and a Lock is not applied. 

Would it be OK if I open a PR that changes that check in order to support the DataDog wrapper class or could you suggest another approach that might solve this?

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Is there any reason why you do not use [AOP proxy](https://github.com/lukas-krecan/ShedLock#scheduled-method-proxy)? 

It's default since 4.0.0 to not to have deal with yet another framework who does it's own wrapping.

**Comment by iwanryszard** [comment]
Thanks for your reply. We are using 3.0.0. We'll try to upgrade and hopefully this will resolve the issue.

**Comment by richardstartin** [comment]
Hi @iwanryszard - we will address this in the Datadog tracer.

**Comment by lukas-krecan** [comment]
@richardstartin Btw new versions of ShedLock are using AOP by default which should mitigate the issue.

**Comment by richardstartin** [comment]
Hi @lukas-krecan we verify we don't interfere with 4.+ here https://github.com/DataDog/dd-trace-java/pull/2530

We will also implement a strategy to avoid perturbing the instanceof check so users of older versions of your library don't encounter issues like this. Could you add this to your known issues to encourage your users to upgrade to 4.+ please?

**Comment by lukas-krecan** [comment]
Thanks. Upgrade to newest version is step one in the [troubleshooting guide](https://github.com/lukas-krecan/ShedLock#troubleshooting). Unfortunatelly it's easier to report a bug then to read README or upgrade.

**Comment by mohammedalics** [comment]
Hi @richardstartin, we are using the latest of the DD Java Agent (0.90.0) but still have issues with Shedlock < 4.x. Is the strategy you mentioned implemented already? 

`No lock configuration for datadog.trace.instrumentation.springscheduling.SpringSchedulingRunnableWrapper@2e8d777e. Executing without lock.`

`Unknown task type datadog.trace.instrumentation.springscheduling.SpringSchedulingRunnableWrapper@7b4aecf1`

> We will also implement a strategy to avoid perturbing the instanceof check so users of older versions of your library don't encounter issues like this. Could you add this to your known issues to encourage your users to upgrade to 4.+ please?

**Comment by richardstartin** [comment]
Hi @mohammedalics I don't work at Datadog any more. I recommend you keep your dependencies up to date though - Shedlock 4.0 was released nearly 2 years ago.
