### ISSUE TITLE
Elasticsearch unlock implementation does not set refresh policy to `WriteRequest.RefreshPolicy.IMMEDIATE`

### ISSUE THREAD

**Issue by bobtiernay-okta** [lukas-krecan/ShedLock#422]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

Update to the latest version.

**Describe the bug**
1. Which version do you use - source
2. Which Lock Provider - Elasticsearch
3. ShedLock configuration - N/A
4. ShedLock logs - N/A

**Expected behavior**
Expected call to `.setRefreshPolicy(WriteRequest.RefreshPolicy.IMMEDIATE)` here:
https://github.com/lukas-krecan/ShedLock/blob/2f84ba87fb980414c1ec807aeda406acd05ad588/providers/elasticsearch/shedlock-provider-elasticsearch/src/main/java/net/javacrumbs/shedlock/provider/elasticsearch/ElasticsearchLockProvider.java#L181

But didn't see it. This implies that the unlock may not be visible during a subsequent lock operation since a refresh wasn't specified.

**Actual behavior**
This was static analysis and was never observed in practice, but wanted to at least document this and ideally comment it in the code.

**Comment by lukas-krecan** [comment]
Thanks for reporting, will fix that.
