### ISSUE TITLE
Support for external config extractor

### ISSUE THREAD

**Issue by shlomiken** [lukas-krecan/ShedLock#43]
Hi

i would like to use the library programatically (not with annotations) but still leverage spring scheduler.
i could not find this in the examples (except for using it without spring)
so i looked at the code and could not find how to do it, specially giving a custom config extractor.
any tip would help 
Shlomi

**Comment by lukas-krecan** [comment]
Hi, I assume you have seen [core package](https://github.com/lukas-krecan/ShedLock/tree/master/shedlock-core/src/main/java/net/javacrumbs/shedlock/core) I think that it should be quite easy to use DefaultLockManager with custom LockConfigurationExtractor. If you want to use spring scheduler, you just have to plug it into https://github.com/lukas-krecan/ShedLock/blob/master/shedlock-spring/src/main/java/net/javacrumbs/shedlock/spring/LockableTaskScheduler.java
