### ISSUE TITLE
Use Case with schedulerlock conditionally

### ISSUE THREAD

**Issue by User1678** [lukas-krecan/ShedLock#430]
Hi ,

i am trying to do shedlock conditionally. but it is not working. Could you please help me how to implement this

public void methodA()
{
if(true)
{
methodb(); //shedlock
}
else{
methodc();
}
}

@schedulerlock(name="lockMethod")
public void methodb()
{
syso("Test");
}

public void methodc()
{
syso("Test");
}

here, even if its going to methodb the lock is not applied. it is just behaving as method c.

**Comment by lukas-krecan** [comment]
Hi, please ask similar questions on StackOverflow. Here I assume that the issue is not ShedLock but Spring AOP which is used underneath. See the question [here](https://stackoverflow.com/questions/13564627/spring-aop-not-working-for-method-call-inside-another-method).
