### ISSUE TITLE
A springboot application is not taking the lock when deployed in multiple instances 

### ISSUE THREAD

**Issue by PietroFardella** [lukas-krecan/ShedLock#439]
Hello there,

hope you can help me with the issue described below.

**Description**
1. Springboot application, with shedlock-spring-4.20.1 and shedlock-core-4.20.1 dependencies
2. The application relies on a SQL Server DB, using the JdbcTemplateLockProvider
3. Here follows the configuration code

**Lock provider**
```
@ConditionalOnProperty(
	     value = "app.scheduling.enable", havingValue = "true", matchIfMissing = true
	  )
@Configuration
@EnableScheduling
@EnableSchedulerLock(defaultLockAtMostFor = "PT30S")
public class ShedlockConfig {

	@Bean
    public LockProvider lockProvider(@Qualifier("src2DataSource") DataSource dataSource) {
		
        return new JdbcTemplateLockProvider(dataSource, "OEE_SHED_LOCK");
    }
	
}
```
**Task**
```@Scheduled(cron = "${oee.scheduling-trigger.cron-expression}")
@SchedulerLock(name = "TaskScheduler_scheduleGetLineStatus", lockAtLeastForString = "PT10S", lockAtMostForString = "PT30S")
@Override public void scheduleGetLineStatus() throws Exception {
//some code
}
```
4. ShedLock logs
I wasn't able to enable them.

**Expected behavior**
When the application is deployed in multiple instances (two instances), I expect that all the instances with eventually take the lock once and perform the scheduled task.
**Actual behavior**
One of instance is not going to take the lock (in hours) and it won't perform the task ever. The application works well when deployed as single instance.

**Comment by lukas-krecan** [comment]
There is no such guarantee that all instaces will eventually execute the lock. The only guarantee ShedLock provides that at most one instance will execute it. Next time, please ask such questions on StackOverflow.
