### ISSUE TITLE
Can't seem to fully clear the cache of locks when testing.

### ISSUE THREAD

**Issue by jrgleason** [lukas-krecan/ShedLock#44]
We are trying to use ShedLock in some integration tests. These tests need the locks cleared after each run, however when I use `@DirtiesContext` and set it to clear after tests, locks seem to be sticking around. 

I need a way to manually clear all locks after each context.

**Comment by lukas-krecan** [comment]
Hi thanks for feedback. I do not understand what do you mean by "locks seem to be sticking around". Locks are released when the execution of locked task ends or after lockAtMost timeout if the process executing task dies. I assume that you do not kill tasks in your integration tests. What LockProvider are you using?

**Comment by jrgleason** [comment]
I am using the normal MongoLockProvider. It is more like this, I have 2 tests that run in-between I reset the Spring context. I would expect that removing from mongo(or even updating which also doesn't seem to resolve it) and reseting the Spring Application context should be enough to clear any left over lock from the previous test. However, what we are seeing is that some of the locks are sticking around. We tried using reflection on the set in LockResolver(?) as well and even that was not working. I know it is extremely nuanced so it may just be some bonehead move on my part, but in that case maybe some test helper files would be nice.

**Comment by jrgleason** [comment]
I will also try to put together a demo, but it will take some time to get it right.

**Comment by lukas-krecan** [comment]
You can try to use this https://github.com/lukas-krecan/ShedLock/pull/56

**Comment by cah-aaron-plunkett** [comment]
@lukas-krecan I realize this is a zombie issue, but it's very relevant to what I'm working on.  The fix you suggest is clearing lockRegistry (in addition to clearing from DB), but MongoLockProvider doesn't have a lockRegistry. Is cache for mongo provider somehow taken care of somewhere else, or does it just not use cache,  unlike the StorageBasedLockProvider that issue references?

**Comment by lukas-krecan** [comment]
Next time please check the source code. The answer is no, MongoLockProvider does not use cache.

**Comment by cah-aaron-plunkett** [comment]
> Next time please check the source code. The answer is no, MongoLockProvider does not use cache.

I did check the source code.  That's how I knew MongoLockProvider didn't have a lockRegistry.  I was just trying to make sure I wasn't missing anything because the comments at the top of the Mongo provider actually say that it uses cache.  As well as this issue mentioning clearing cache even though the issue was with mongo.

Regardless, thank you for a quick response.
