### ISSUE TITLE
SchedulerLock.name should support placeholders in form "${property.name}"

### ISSUE THREAD

**Issue by kosmaty** [lukas-krecan/ShedLock#45]
Currently, all the parameters of `@SchedulerLock` annotation support placeholders, with exception of `name` property. Name specified in annotation is not evaluated. 
I would like to  specify it like this:
```java
@SchedulerLock(name = "${lock.name}")
```
so that it would be evaluated to a value defined in properties/yml file.

**Comment by lukas-krecan** [comment]
Thanks for feedback. Fixed in 0.17.0, enjoy

**Comment by kosmaty** [comment]
Great! Thanks.
