### ISSUE TITLE
For shedlock-provider-cassandra, allow dynamic use of the keyspace by CqlSession

### ISSUE THREAD

**Issue by bourreta** [lukas-krecan/ShedLock#459]
With provider cassandra, shedlock assumes that the CqlSession it is passed will always be bound to the keyspace that the "lock" table is in. This makes it impossible to use the same CqlSession elsewhere in an application that interacts with different keyspaces. An improved approach would provide the user an option to pass in the keyspace and have it set dynamically by the Datastax query builder at execution time for each individual query.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Will do it in next few days. ot if you want to, you can send a PR. I jsut would not add a new constructor but just add it to the `Configuration` class and then use it in the `CassandraStorageAccessor`

**Comment by lukas-krecan** [comment]
Released as 4.22.0
