### ISSUE TITLE
Cassandra error handling

### ISSUE THREAD

**Issue by lsj-phse** [lukas-krecan/ShedLock#466]
Using the Cassandra provider, getting occasional WriteTimeoutException due to LWT.

com.datastax.oss.driver.api.core.servererrors.WriteTimeoutException: Cassandra timeout during CAS write query at consistency SERIAL (4 replica were required but only 3 acknowledged the write)

I'd like to handle the exception where the exceptions come as a warning instead.

Can I handle it from my application instead? How do I do it, in that case? Thank you!

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. It makes sense, we have something similar in JdbcTemplate lock provider. We can catch Cassandra exception and log it as warning. Do you want to provide a PR or shall I do it?

**Comment by lsj-phse** [comment]
Great! I'll create a PR for this.

**Comment by lukas-krecan** [comment]
Released as 4.22.1

**Comment by lsj-phse** [comment]
Thank you! Would be good to look into your suggestion also, about QueryExecutionException.
