### ISSUE TITLE
RedisConnectionFactory support

### ISSUE THREAD

**Issue by siposr** [lukas-krecan/ShedLock#47]
Hello there,

People who use SpringBoot and Redis have some problem with your Redis-provider. SpringBoot gives us some nice and easy configuration with RedisConnectionFactory. This CF uses the same RedisPool inside the implementation but that is private so no way to get it. Instead it gives us RedisConnection.

I created some nice implementation for your LockProvider interface. I can give it back to the community but I need some information about proper contributions here for that.

Thanks in advance.

**Comment by lukas-krecan** [comment]
Hi, thanks, do not hesitate to send a pull-request, contributions are welcome. (current Redis implementation has been contributed as well)

**Comment by siposr** [comment]
Tank you guys, I will see what can I do. :)

**Comment by siposr** [comment]
Main file is uploaded already.
Test file and pom is coming soon.

**Comment by lukas-krecan** [comment]
Cool, let me know if you need any help.

**Comment by lukas-krecan** [comment]
Hi, just in case you do not have time to work on it, I will be more than happy to finish it.

**Comment by siposr** [comment]
I was way too busy sorry. Now I can do some work with this.
It might have one bug but I just can't trace it back. Most of the time it works like charm. Maybe it is my redis setup. Locks go wrong like once in a month.

**Comment by lukas-krecan** [comment]
OK. What sometimes happens is that locked tasks are shorter than the time-shift between machines in the cluster. So the task is executed multiple times (not in parallel but one after each other). Can be prevented by setting lockAtLeastFor. Maybe it's your case, maybe not. In any case, just let me know if you need any help.

**Comment by siposr** [comment]
lockAtLeastFor is set and most of the time it works. Sometimes redis doesn't expire or delete (? under investigate) the key for the lock, so basically it stucks in the db and causes no more job execution.

**Comment by siposr** [comment]
I think we can close it now.
