### ISSUE TITLE
shedlock logger is displaying time in UTC, even though we changed the timezone in the JdbcTemplateLockProvider

### ISSUE THREAD

**Issue by streamheart** [lukas-krecan/ShedLock#499]
the logger is showing lock atleast and lock atmost as UTC but saves them in DB as GMT+3, is this the expected behaviour? or is this going to affect my system

i am using shedlock 2.5.0, spring boot 1.5.10.RELEASE

note that we cannot upgrade spring boot or scheduler.

am using =====>  JdbcTemplateLockProvider.Configuration configuration = JdbcTemplateLockProvider.Configuration.builder().withJdbcTemplate(new JdbcTemplate(dataSource)).withTableName(tableName).withTimeZone(TimeZone.getTimeZone("GMT+3")).build();

to set the timezone

the log says: 
2021-04-07 17:39:42.873 DEBUG 1300 --- [ pr-scheduler-3] n.j.s.core.DefaultLockingTaskExecutor    : Task finished, lock '****' will be released at 2021-04-07T11:44:42.866Z
but is saved in the database as 2021-04-07T02:44:42.866

i expected that the logger would print out the same value as it set in the DB.

**Comment by lukas-krecan** [comment]
Hi, it should not affect your system. The logging you mention is done in shared layer that is executed regardless the LockProvider used. TimeZone is used in a layer below that.

I do not recommend using other zones than UTC due to daylight changing issues.
