### ISSUE TITLE
Why some of the "LockConfiguration" constructors deprecated ?

### ISSUE THREAD

**Issue by DebajitKumarPhukan** [lukas-krecan/ShedLock#523]
First of all thank you so much for pushing the latest release on the CassandraProvider (4.2.3) so quickly. It helped us a lot to resolve the bug appearing in production environment on time. Hope it reaches to other developers as well. I wanted to check with you directly on a query, but since I don't have any other way to communicate with you so went ahead for creating a bug.

**Problem Statement:**
I saw that some of the LockConfiguration constructors were marked "deprecated" even though they work fine. In the readme file, I see that you have mentioned the deprecated constructor only. Was deprecation a intentional or mistake ?. If it was intentional, can you brief a bit on why it was done ?.

For JDBC provider, if we want to use the dbtime, below constructor works perfectly.

`public LockConfiguration(@NonNull String name, @NonNull Instant lockAtMostUntil)`

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. It's actually [explained](https://github.com/lukas-krecan/ShedLock/blob/master/shedlock-core/src/main/java/net/javacrumbs/shedlock/core/LockConfiguration.java#L87) in the only non-deprecated constructor. I just added JavaDoc references to it.

The deprecated constructors work, but they may be confusing when used with LockProviders that support DB time.

**Comment by lukas-krecan** [comment]
Related ticket https://github.com/lukas-krecan/ShedLock/issues/318
