### ISSUE TITLE
shedlock version 4.6.0 and later version not support spring boot version 1.5.6.RELEASE

### ISSUE THREAD

**Issue by wuhai12138** [lukas-krecan/ShedLock#527]
if your spring version is 1.5.6.RELEASE, and you try to use shedlock, your application will catch with some weird error.

some error logs : Error creating bean with name 'proxyScheduledLockAopBeanPostProcessor' defined in class path resource### 

shedlock version 4.5.2 and older version is effective.

**Comment by lukas-krecan** [comment]
Hi, Spring Boot 1.x is not supported. It's more than a year after EOL.
