### ISSUE TITLE
Clarification of usingDbTime in documentation

### ISSUE THREAD

**Issue by finlaydotb** [lukas-krecan/ShedLock#535]
In the documentation you have the following:

> By specifying usingDbTime() (introduced in 4.9.3) the lock provider will use UTC time based on the DB server time

Does this mean the lock provider will use UTC? 
Or the lock driver will use the timezone configured on the DB server? 

Can't really tell from the way the documentation is written as it is a bit ambiguous plus I am not sure what _UTC time based on DB server time_ means. I believe UTC is being used or the timezone on the server is used...not sure what _UTC time based on DB server time_ means.

Clarification will be appreciated!

**Comment by lukas-krecan** [comment]
I [clarified](https://github.com/lukas-krecan/ShedLock/commit/e6771a10a55ad340160008ca7e422ba678002483) it a bit, but I guess that if you continued reading to the following sentence, you would have understood.
