### ISSUE TITLE
upgrade to Spring 5

### ISSUE THREAD

**Issue by z0mb1ek** [lukas-krecan/ShedLock#55]
Hi. Big thx for this project. Any plans to upgrade?

**Comment by lukas-krecan** [comment]
Hi, it should work with Spring 5 without any problem (if it does not, please let me know). Upgrade to Spring 5 will take some time, we have to wait for more people adopting it, which in turn waits for Spring Boot 2 to be released and adopted.

**Comment by z0mb1ek** [comment]
Spring Boot will release in some weeks, maybe you can make some beta?

**Comment by lukas-krecan** [comment]
The issue is not the release but the adoption. I am afraid that due to backward incompatibility in some libraries like Spring Data, the adoption will take months, if not years.

**Comment by z0mb1ek** [comment]
All libs in spring stack go for spring 5

**Comment by lukas-krecan** [comment]
ShedLock is IMHO compatible with Spring 5 and upgrading the dependency would just risk cutting off Spring 4 users.
