### ISSUE TITLE
Possible to specify schema?

### ISSUE THREAD

**Issue by GeeWee** [lukas-krecan/ShedLock#57]
Heyo. I'm looking at ShedLock for locking tasks in a Spring environment. We use a setup where each tenant has their own schema and it's managed through Spring. We use SQL Server 2017 as the backing database.

Digging through ShedLock I wasn't able to find anything that would let me specify what schema to use. It would be great if we could set the schemaName in the @Scheduled annotation, or at the very least specify it in the LockProvider.

Seems like I could customly implement StorageAccessor for the second use case of specifying a schema, but it doesn't seem like the first use-case is supported.

Can you advise me, what the best approach would be?

**Comment by lukas-krecan** [comment]
Hi, unfortunately, I do not have experience with SQL server. Can you please describe how would you specify schema in plain JDBC or in Spring JdbcTemplate?

**Comment by clamey** [comment]
IIRC, schemas are set via the JDBC URL and are driver dependent :

jdbc:sqlserver://ipaddress:port;database=DBName;schema=SCHEMANAME;selectMethod=cursor;sendStringParametersAsUnicode=false;IntegratedSecurity=true

jdbc:postgresql://localhost:5432/mydatabase?currentSchema=myschema

How do you have Spring set up to talk to these schemas?  Is there something like a ConnectionPool per tenant?  Or just one pool but the schemas are prefixed and your queries include the prefixes?

**Comment by GeeWee** [comment]
Absolutely. Taking the example from insertRecord in AbstractJdbcStorageAccessor
it would look something like:

Old:
```java
@Override
    public boolean insertRecord(LockConfiguration lockConfiguration) {
        // Try to insert if the record does not exists (not optimal, but the simplest platform agnostic way)
        String sql = "INSERT INTO " + tableName + "(name, lock_until, locked_at, locked_by) VALUES(?, ?, ?, ?)";
        try (
            //...
            }
        } catch (SQLException e) {
            handleInsertionException(sql, e);
        }
        return false;
    }
```
New:
```java
@Override
    public boolean insertRecord(LockConfiguration lockConfiguration) {
        // Try to insert if the record does not exists (not optimal, but the simplest platform agnostic way)
        String sql = "INSERT INTO " + schemaName + "." + tableName + "(name, lock_until, locked_at, locked_by) VALUES(?, ?, ?, ?)";
        try (
            //...
            }
        } catch (SQLException e) {
            handleInsertionException(sql, e);
        }
        return false;
    }
```
so the written out sql statement to select from table `foo` in schema `bar`
would be something like
```sql
SELECT * from bar.foo
```

But it would be wonderful to be able to e.g. provide the schema in the @Scheduled, or at least have a schema-aware Lock-Provider. I'd be willing to try and implement one that's suitable for general purpose use if you'll point me in the right direction.

**Comment by lukas-krecan** [comment]
In such case it should be enough to pass "SCHEMA_NAME.shedlock" to LockProvider constructor.

**Comment by GeeWee** [comment]
I can't believe I didn't realise that. Thanks so much!

**Comment by hanisntsolo** [comment]
> In such case it should be enough to pass "SCHEMA_NAME.shedlock" to LockProvider constructor.

Best and simplest.
