### ISSUE TITLE
Does each node get a fair chance to acquire lock?

### ISSUE THREAD

**Issue by mengzheng** [lukas-krecan/ShedLock#570]
I have a service runs every minute in 3 nodes, A, B and C.
Assume the first minute, the node A gets the lock, and run the job. Does node B or C has preference to acquire the lock over A in next scheduled time? Does this library guarantee that all nodes can acquire the lock in round-robin style and each node gets a fair chance to run? Using library, is that possible that one node always gets the lock and the other nodes never get chance to run?

**Comment by lukas-krecan** [comment]
Hi, it's indeed possible that one node always runs. Especially, if it's clock is running earlier than clocks of the other nodes. Next time, please ask such questions on StackOverflow.
