### ISSUE TITLE
Row is not cleared during app restart or app goes down.

### ISSUE THREAD

**Issue by yournans** [lukas-krecan/ShedLock#59]
Hi Lukas, thanks for implementing this lock! I just tried using it(version:0.18.2) in my spring boot app with MS SQL server DB. I want to understand how the lock should behave in the event if the app is redeployed or server node goes down. In such cases, row in the table still exists though the task was already complete. When the app comes back up, it tries to INSERT row one more time and it fails till deleting the row manually.

What is the expected behavior? Have I missed any thing in the implementation?

@SchedulerLock(name = "someUniqueTaskName", lockAtMostFor = 60000)

**Comment by lukas-krecan** [comment]
Hi, can you please describe how the app fails? It always tries to insert the row (and if you have debug log on you can see an error), but if the insert fails it's handled and the row is updated. 

The expected behavior is that the row row is not deleted when the tasks ends, but the value in lock_until is set to 'now'.  If the process dies in the middle of the task processing, the lock is held at most for '60000'. What are you describing is fairly common use-case so I guess that the problem is in your app.

**Comment by yournans** [comment]
App works fine when it is up and running after inserting the first lock. It keeps updating lock_until information. When I deploy the app using CI tool like Jenkins, Shedlock tries to insert the row again as it may not find any thing in the lock cache. But the row in DB is still there and it produces duplicate row error. In this case none of the nodes in the app server start the scheduler. That is my problem.

**Comment by lukas-krecan** [comment]
OK, lets' dive in the code. JDBC access is handled by [AbstractJdbcStorageAccessor](https://github.com/lukas-krecan/ShedLock/blob/master/providers/jdbc/shedlock-provider-jdbc-internal/src/main/java/net/javacrumbs/shedlock/provider/jdbc/internal/AbstractJdbcStorageAccessor.java#L60) If the insertRecord method returns false, update is attempted. Now it depends on the implementation you use. If you are using [jdbc-template provider](https://github.com/lukas-krecan/ShedLock/blob/master/providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/JdbcTemplateStorageAccessor.java#L48) we are depending on Spring to correctly resolve duplicate key exception as SQLIntegrityConstraintViolationException. If it does not happen, ShedLock would rethrow the exception and fail to update the lock. In such case please try to switch to pure [jdbc-lock-provider](https://github.com/lukas-krecan/ShedLock/blob/master/providers/jdbc/shedlock-provider-jdbc/src/main/java/net/javacrumbs/shedlock/provider/jdbc/JdbcStorageAccessor.java#L38) which catches all the exceptions so such thing can not happen. If it's indeed the case, we should file a bug to Spring issue tracker so they fix it on their side.

**Comment by yournans** [comment]
Hi Lucas, thanks for the insight! Indeed it was JdbcStorageAccessor. I extended AbstractJdbcStorageAccessor to my own class similar to JdbcTemplateStorageAccessor just to view exceptions and log them. But during the process I did not suppress DataIntegrityViolationException as done in handleInsertionException() of JdbcTemplateStorageAccessor. Once I did the exact change in my class, locks are being updated. I sincerely appreciate your quick responses. Thank you so much!!

**Comment by lukas-krecan** [comment]
Next time please mention that you are using your own implementation in the original error report. For failing to do that, you are herby fined to send $10 to [EFF](https://supporters.eff.org/donate) or [MSF](http://www.msf.org/en/donate)
