### ISSUE TITLE
More of a concern

### ISSUE THREAD

**Issue by thalhamerb** [lukas-krecan/ShedLock#6]
It looks like this doesn't take into consideration the next firing time.  I believe schedulers like quartz knows when the next fire time should be and doesn't allow the job to be ran until that time comes.  So I imagine it could be possible that a task could fire a little late and run the same task if the first one finishes quickly and releases the lock.  Is this the case?

**Comment by lukas-krecan-lt** [comment]
Hi, thanks for feedback. If I understand you correctly, you have multiple nodes and the task is executed on one of them and due to clock shift on another one as well (after the first one finishes)? Yes, it may happen, the only thing ShedLock does is preventing concurrent execution. If you need more sophisticated features, use Quartz or some other sophisticated scheduler.

**Comment by lukas-krecan-lt** [comment]
I have updated README to make it clear, thanks again

**Comment by lukas-krecan-lt** [comment]
I have been thinking about it and I can add some kind of grace period or runAtMostOncePer X parameter which would make sure that the lock is not acquired (and thus the task executed) more than once per certain period of time. Would such feature help you?

**Comment by thalhamerb** [comment]
Yes the runAtMostOncePer X parameter would be great.

**Comment by nitin02** [comment]
Hi, any approximate time frame for implementation of this **runAtMostOncePer X parameter**?

**Comment by thalhamerb** [comment]
I don't want you rush you since you are providing this awesome dependency, but if 2 weeks is enough time that would be great.

**Comment by lukas-krecan** [comment]
Will take a look at it, two weeks sound more than enough :-)

**Comment by lukas-krecan** [comment]
Work in progress https://github.com/lukas-krecan/ShedLock/pull/7/files

**Comment by lukas-krecan** [comment]
Released as 0.7.0
