### ISSUE TITLE
Reactive Mongo Support

### ISSUE THREAD

**Issue by ghahramani** [lukas-krecan/ShedLock#60]
Hi,

Do you have any plan to support reactive MongoClient?

**Comment by lukas-krecan** [comment]
Just to make sure I understand the use-case correctly, you only have reactive Mongo driver and you do not want to use synchronous Mongo driver just for ShedLock?

**Comment by lukas-krecan** [comment]
Other than that, asyc driver does not make much sense for ShedLock since we need to wait for the result of lock attempt. Feel free to send PR, it should be quite easy to create a new lock provider.
