### ISSUE TITLE
Error when executing liquibase scripts

### ISSUE THREAD

**Issue by jdieber42** [lukas-krecan/ShedLock#600]
I'm running the shedlock in my project together with liqubase (3.10.2). Maven builds are working and also the shedlock is running as expected, but when I want to execute liquibase on the project we are getting following error:

[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.10.2:diff (default-cli) on project sepoc-journal-service:
[ERROR] Error setting up or running Liquibase:
[ERROR] org.springframework.core.annotation.AnnotationConfigurationException: Attribute 'proxyBeanMethods' in annotation [org.springframework.boot.autoconfigure.SpringBootApplication]
is declared as an @AliasFor nonexistent attribute 'proxyBeanMethods' in annotation [org.springframework.context.annotation.Configuration].
[ERROR] -> [Help 1]

It does not directly say with what annotation it has an issue, but if I remove the ...
<dependency>
    <groupId>net.javacrumbs.shedlock</groupId>
    <artifactId>shedlock-spring</artifactId>
</dependency>
... dependency and its implementations, liquibase is executing the command without an error.

Do you have an idea whats wrong? I tried the latest version of liquibase and shedlock, nothing changed. I'm currently running spring-boot 2.3.3, also tried with 2.5.1, nothing changed.

**Comment by lukas-krecan** [comment]
Hi, what ShedLock version do you have?

**Comment by lukas-krecan** [comment]
It seems like some incompatibilities in your dependencies. In this case I would guess that you have too old spring-context module for your spring boot.
