### ISSUE TITLE
Shift lock_until if a task is still running

### ISSUE THREAD

**Issue by makcon** [lukas-krecan/ShedLock#606]
The documentation says:
 
_You have to set lockAtMostFor to a value which is much longer than normal execution time_

but normally it's hard to predict the execution time of a task. I'd suggest to add an optional feature to shit the time in case of a task is still running:

- Before a task will start create a scheduler that runs every n time
- If a task is still running and `lock_until` is about to expire then update the field (`lock_until` + n time)

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. It's possible but you have to create the lock manually. See this https://github.com/lukas-krecan/ShedLock/issues/443

**Comment by lukas-krecan** [comment]
You can try this (just released) https://github.com/lukas-krecan/ShedLock#extending-the-lock

**Comment by makcon** [comment]
Hi Lukas, as I understood, to use it I have to manually check for a task completion and call the new static method to extend a lock, right? I'm expecting to hide it under library and just use `@SchedulerLock` for scheduled method.
I created my own class `ExtendableLockingTaskExecutor` that extends `DefaultLockingTaskExecutor` and put logic to track a task completion and add some time if it's still running. It's working but I didn't have time to test it carefully. If you are interested I can share my solution.

**Comment by makcon** [comment]
Hi @lukas-krecan, I made the simple change and we are gonna test it. Please take a look https://github.com/lukas-krecan/ShedLock/pull/668/files
