### ISSUE TITLE
Is there a way to configure the lock holder to come from a different source?

### ISSUE THREAD

**Issue by froilan** [lukas-krecan/ShedLock#63]
I am looking for a way to use maybe an environment variable instead of the hostname for it. 
Is that possible?

**Comment by lukas-krecan** [comment]
Hi, the hostname is just a debugging information. Nevertheless, if you need to change it, you can override getHostname in StorageAccessor (depending on which Lock Provider you are using) and use it like this https://github.com/lukas-krecan/ShedLock/blob/master/providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/JdbcTemplateLockProvider.java
