### ISSUE TITLE
Clock skew/drift prevention across nodes

### ISSUE THREAD

**Issue by aaiezza** [lukas-krecan/ShedLock#639]
This library is really incredible and useful.

# Clock drift

One thing I noticed and wanted to raise for discussion is how ShedLock handles clock drift between multiple nodes.
As described in #263, if you are using the [JdbcTemplate LockProvider](https://github.com/lukas-krecan/ShedLock#jdbctemplate), you can simply use the `usingDbTime()` method to ensure the clock is synchronized.
However, in other LockProvider implementations, this is not an option.

The `lockAtLeastUntil` functionality introduced in #7 (and discussed in #6), does allow for that "wiggle room" in the clock drift. So perhaps, this is sufficient for most implementations.

I also see one thing that could be done, is leverage the work #204 to establish a central/synchronized clock across nodes. But that could come with its own challenges.

## Amazon DynamoDB Locking Client solution

While this library takes the cake on simplicity and support for multiple types of lock providers, Amazon's DynamoDB lock client library handles clock skew in a very creative (and open-source) way: https://github.com/awslabs/amazon-dynamodb-lock-client#how-we-handle-clock-skew.
If I have the bandwidth, I would like to see what it would take to implement this more-robust solution in ShedLock.

Thoughts?

**Comment by lukas-krecan** [comment]
Hi, you are right, the assumption is that NTP together with `lockAtLeastUntil` should provide good-enough solution. Perfect solution is far more tricky.

I do not see how we would be able to implement "central/synchronized clock across nodes" better than NTP.

I do not understand how you want to implement the Amazon DynamoDB solution. Do you mean in general, for all LockProviders? If that's the case, it would be a huge change, it would basically mean to reimplement all LockProviders. While that's possible, I doubt it's worth it.

I wonder what's your motivation, did you encounter a problem or are you looking for someting interesting to solve. If the former, can you plese describe the problem?

Kudos for your reasearch, I have never seen such well-research issue.

**Comment by aaiezza** [comment]
@lukas-krecan thank you for the feedback!

The Amazon DynamoDB lock client solution is fairly elegant, and keeps timestamps out of the lock provider implementation entirely. While this feels like a more robust solution, I agree with your other sentiment on the blast radius. It would be a lot of work to touch and test every implementation.

I have not personally run into a problem yet actually, especially after increasing the `lockAtLeastUntil`.

I plan to use this library in a large enterprise application and would have perhaps preferred a similar locking mechanism implemented in AWS.

The `lockAtLeastUntil` solution gives plenty of wiggle-room for clock drift; So I would call this a non-issue for now.

**Comment by lukas-krecan** [comment]
Cool, thanks
