### ISSUE TITLE
Utilizing ShedLock with dynamically reloadable tasks/schedules without Spring restart

### ISSUE THREAD

**Issue by Hr0bar** [lukas-krecan/ShedLock#662]
Hi, used ShedLock in the regular annotation way previously, but a new need arised for me, where we need to reload the cron schedule of a task dynamically from a configuration file without restarting the whole Spring app. Some resources that we utilized:

https://stackoverflow.com/questions/37335351/schedule-a-task-with-cron-which-allows-dynamic-update
https://stackoverflow.com/questions/20546403/spring-scheduler-change-cron-expression-dynamically
https://stackoverflow.com/questions/46974272/how-to-add-new-schedule-job-dynamically-with-spring

Unfortunately, cant get this requirement to work with ShedLock, if I execute the tasks manually from elsewhere in the code by calling ScheduledTasks.syncDataBase(false), the lock gets applied OK, but the automatic execution does not apply any locks. Tried also doing it with the internal LockableTaskScheduler and LockManager and LockableRunnable etc from ShedLock, but couldnt get it to work.

Is it possible to meet this requirement with ShedLock? If so how to do it in the cleanest possible way? Thanks a lot

This is how the current attempt looks like:

```
package xxxx;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.TimeZone;
import java.util.concurrent.ScheduledFuture;
import javax.sql.DataSource;
import xxxx.configs.Props;
import xxxx.logic.LogicSNOW;
import xxxx.logic.LogicTasks;
import xxxx.models.Dao;
import xxxx.models.SystemLog;
import net.javacrumbs.shedlock.core.LockProvider;
import net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateLockProvider;
import net.javacrumbs.shedlock.spring.annotation.EnableSchedulerLock;
import net.javacrumbs.shedlock.spring.annotation.SchedulerLock;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.scheduling.TaskScheduler;
import org.springframework.scheduling.support.CronTrigger;
import org.springframework.stereotype.Component;

@Component
@EnableSchedulerLock(defaultLockAtMostFor = "60m")
public class ScheduledTasks {

  @Autowired
  private Dao dao;
  @Autowired
  private DataSource dataSource;

  final private ArrayList<ScheduledFuture<?>> tasks;
  final private Props env;
  final private TaskScheduler scheduler;

  @Bean
  public LockProvider lockProvider() {
    return new JdbcTemplateLockProvider(
     JdbcTemplateLockProvider.Configuration.builder()
      .withJdbcTemplate(new JdbcTemplate(dataSource))
      .usingDbTime()
      .build()
    );
  }

  @Autowired
  public ScheduledTasks(TaskScheduler scheduler, Props env) {
    this.scheduler = scheduler;
    this.env = env;

    tasks = new ArrayList<>();
    addTasks();
  }

  public void reloadTasks() {
    int taskNr;

    for (taskNr = 0; taskNr < tasks.size(); taskNr++) {
      tasks.get(taskNr).cancel(true);
    }
    tasks.clear();

    addTasks();
  }

  private void addTasks() {
    addTask("databasesync", new SyncDataBase());
  }

  private void addTask(String name, Runnable task) {
    ScheduledFuture<?> scheduledFuture;
    String cron;

    cron = env.getProperty("tasks." + name);
    if (!cron.isEmpty()) {
      scheduledFuture = scheduler.schedule(task, new CronTrigger(cron, TimeZone.getTimeZone(TimeZone.getDefault().getID())));
      tasks.add(scheduledFuture);
    }
  }


  private class SyncDataBase implements Runnable {

    @Override
    public void run() {
      syncDataBase(true);
    }
  }



  @SchedulerLock(name = "syncDataBase", lockAtMostFor = "60m", lockAtLeastFor = "15s")
  public void syncDataBase(boolean logging) {
    doSomething();
  }

}

```

**Comment by lukas-krecan** [comment]
Hi, can you please specify which version of ShedLock are you using. If it's a recent one, it is using Spring AOP which usually does not work if you are calling a method of the same class. That may be the reason.

Alternatively, you can try to use [TaskScheduler proxy](https://github.com/lukas-krecan/ShedLock#taskscheduler-proxy).

**Comment by lukas-krecan** [comment]
Next time, please ask on StackOverflow

**Comment by Hr0bar** [comment]
Thanks, its latest ShedLock+latest Spring. Managed to get it working with autowiring self to trigger the AOP.

  @Autowired
  private ScheduledTasks self;

and then calling

 self.syncDataBase(true);

Thanks again.
