### ISSUE TITLE
Add support for customizable transaction isolation level settings [JDBC]

### ISSUE THREAD

**Issue by ssherwood** [lukas-krecan/ShedLock#667]
In some situations it would be useful to have the ability to override the default transaction isolation level when setting up the `JdbcTemplateLockProvider`.

Specifically it looks like an extension could be made to the `JdbcTemplateLockProvider.Configuration` class so that the desired isolation level could then be passed into the `JdbcTemplateStorageAccessor` for use by the _transactionTemplate_ in the constructor.  As it is currently implemented, I'm not sure how to do this via overrides since `JdbcTemplateStorageAccessor` is not public.

**Comment by lukas-krecan** [comment]
Hi, sorry, I have somehow missed this issue. Would it be enough if we let you to set configured transactionTemplate to the `Configuration` class?

**Comment by ssherwood** [comment]
Yes, I think that would be a reasonable solution and may open up other configuration options pretty easily.

**Comment by lukas-krecan** [comment]
Just out of curiosity, what is the use-case, why do you need to set the siolation level?

**Comment by ssherwood** [comment]
Well, specifically with the default isolation level there are errors showing up in the database logs regarding transactions needing to be restarted due to all of the running instances waking up vying to run the job.  I've noticed that if I elevate isolation to SERIALIZABLE, these errors go away.  However, I don't want to use SERIALIZABLE on all of my connections, so having this as a customizable feature just for Shedlock solves the problem for me.

**Comment by ruiyang** [comment]
would be great if this could be fixed asap as if two threads could hold the same lock, it defeats the purpose of the lock. please let me know if you need any help, eg. a repo to reproduce the issue or a pull request. thanks.

**Comment by lukas-krecan** [comment]
@ruiyang Hi, can you please report it as a separate issue. What you are claiming is quite unlikely. Not only is the locking behaviour tested on all major databases, it's also used for years by quite a lot of people. 

In the issue please specify the database and provide the logs showing that two threads are indeed holding the same lock. Thanks.

**Comment by ruiyang** [comment]
@lukas-krecan Hi, great timing. I just created a repo and reported a new issue at https://github.com/lukas-krecan/ShedLock/issues/702. Please help to have a look when you are free. 
Thanks

**Comment by lukas-krecan** [comment]
Released as 4.27.0
