### ISSUE TITLE
Wrong @Bean/type in the README file

### ISSUE THREAD

**Issue by marcosbarbero** [lukas-krecan/ShedLock#67]
Hello, @lukas-krecan I'm trying to set up this library to use on a side project but the documentation in the `README` file doesn't seem to be correct.

It says:

>if you already have an instance of ScheduledExecutorService

```java
@Bean
public TaskScheduler taskScheduler(ScheduledExecutorService executorService, LockProvider lockProvider) {
    return ScheduledLockConfigurationBuilder
        .withLockProvider(lockProvider)
        .withExecutorService(executorService)
        .withDefaultLockAtMostFor(Duration.ofMinutes(10))
        .build();
}
```

However, the code above returns incompatible types.

**Comment by lukas-krecan** [comment]
Thanks, fixed
