### ISSUE TITLE
Retrieve lock if it exists

### ISSUE THREAD

**Issue by jeffzoch** [lukas-krecan/ShedLock#675]
**Is your feature request related to a problem? Please describe.**
I would like to make sure i only schedule some task against one *entity* at a time. While the scheduling can happen at any node, id like to take a lock and say "this *entity* is the only one allowed to be worked on right now". 

**Describe the solution you'd like**
If I could create a shared-lock with value that represents my *entity's* name and be able to retrieve it and extend it i could:
- Try and create a lock for *entity* foo
- If i could not, try again later.
- Otherwise, give me back the lock if it already exists or create a new one (aka extend or create)

Is this possible with shedlock currently? It is sort of hard to tell by the api if the locked_by value can be changed constantly and if we can conditionally create / extend locks

**Comment by lukas-krecan** [comment]
Hi, I am not sure I understand you correctly, but it seems to me that you can use lock name for that. If you use entity ID as a lock name, it should work as you are describing, shouldn't it?
