### ISSUE TITLE
Use of opentelemetry agent seems to disable shedlock

### ISSUE THREAD

**Issue by uweschaefer** [lukas-krecan/ShedLock#689]
We had a hard time figuring out what is going on, as this error was not reproducible on a dev machine as we use opentelemetry in AWS only and the debug level for shedlock was not enabled by default.

**Describe the bug**
1. Which version do you use

**4.25.0**

2. Which Lock Provider

**JdbcTemplateLockProvider**

3. ShedLock configuration

on the configuration:

@EnableScheduling
@EnableSchedulerLock(
  defaultLockAtMostFor = "PT30m",
  interceptMode = InterceptMode.PROXY_SCHEDULER
)

on the method:

@Scheduled(cron = "0 0 0 * * *")
@SchedulerLock(
    name = "something",
    lockAtMostFor = "120m"
  )

4. ShedLock logs

log.level | DEBUG
-- | --
 log.logger | net.javacrumbs.shedlock.core.DefaultLockManager
message | No lock configuration for **io.opentelemetry.javaagent.instrumentation**.spring.scheduling.SpringSchedulingRunnableWrapper@7431c1da. Executing without lock.

**Expected behavior**
if possible, resolve the configuration despite the indirection, or at least log an ERROR level log message if this is unexpected.

**Actual behavior**
Execution without a lock, breaking randomly in multinode environment.

**Comment by uweschaefer** [comment]
Thanks for the quick analysis. Apparently, we did not have a compelling reason for PROXY_SCHEDULER :laughing: 
METHOD works fine for us. However, maybe i miss some use-cases, but isn't this situation worth a WARN level log line (at least)?

**Comment by lukas-krecan** [comment]
Cool, I am glad it helped. The trouble is thet there can be tasks without a lock executed by the scheduler and you do not want to get WARN for them. It's impossible to recognize whether the missing configuration is due to lack of lock or due to some library messing with the scheduler.
