### ISSUE TITLE
Running in Docker/K8

### ISSUE THREAD

**Issue by mbagliojr** [lukas-krecan/ShedLock#69]
Will this work in a container? If running in a clustered environment where multiple nodes have the same hostname, will this produce an issue?

**Comment by lukas-krecan** [comment]
Hi, we use it in K8S without any problem. Hostname is used only for debugging purposes (btw. you pods in K8S have unique hostname)

**Comment by rockxsj** [comment]
> Hi, we use it in K8S without any problem. Hostname is used only for debugging purposes (btw. pods in K8S have unique hostname)

the pods in K8S have unique hostname is the problem. Because everytime when I release a new deployment, the pod get the special lock will be destroyed, so the lock will only be released when timeout. can I use the node name as the locked_by column, but not pod name?
