### ISSUE TITLE
JdbcTemplateLockProvider lock is not mutual exclusive

### ISSUE THREAD

**Issue by ruiyang** [lukas-krecan/ShedLock#702]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

Update to the latest version.

**Describe the bug**
1. Which version do you use:  4.25.0
2. Which Lock Provider:  shedlock-provider-jdbc-template
3. A complete git repo to reproduce the issue:
https://github.com/ruiyang/shedlock_spike.git

**Expected behavior**
In a concurrent scenario, there should be only one thread holding the lock.

**Actual behavior**
Multiple threads reported to hold the lock at similar time.

**Comment by ruiyang** [comment]
Hi, I might be doing sth wrong in my example.
there are some moving parts, not sure if related:
1. I'm using mysql docker instead of a real mysql server. 
2. To release the lock, I have to extend the SimpleLock to set a new config to atLeast and atMost to now.

Another thoughts would be:
could it be because two updates were executed at a very close timestamp so they both returned true for the where clause? Then how could we prevent this?

I want to use a lightweight lock solution. I could switch to use redis, but hesitate to bring redis into the app only for the sake of locking. would be great if JdbcTemplateLockProvider could work as expected since we already have had db in the app.

Thanks

**Comment by ruiyang** [comment]
I also checked changing the isolation level made no difference. so it might not be because how transactions are handled.

**Comment by lukas-krecan** [comment]
Sorry, I do not have capacity to debug your code. My guess would be that the lock is held for more than `lockAtMostFor` and is automatically released. You can try newly introduced [KeepAliveLockProvider](https://github.com/lukas-krecan/ShedLock#keepalivelockprovider).
