### ISSUE TITLE
How can I use this library to schedule things programmatically, not from annotation

### ISSUE THREAD

**Issue by goravsingal** [lukas-krecan/ShedLock#703]
I have a configuration having N number of entries. 
```
Example:
- Task1, schedule=xyz
- Task2, schedule=abc
```

I understood the annotation route. But, it works when I know how many schedules I need to set.
In my case, this is dynamic. And, by reading from config, I want to set schedule programmatically.

```
Example:

class Task {
  String name;
  String schedule; //cron schedule
}

t1 = new Task("task1", "* */10 * * *");
t2 = new Task("task2", "* */20 * * *");
schedule.schedule(t1);
schedule.schedule(t2);

```
I should be able to set the callback function, which will be executed on schedule trigger.

How can I achieve this? I couldn't see this in any documentation.

Thanks

**Comment by lukas-krecan** [comment]
Hi, please ask questions on StackOverflow, it will be more likely someone else answers. 

ShedLock is only for locking, how to access it programatically is explaind [here](https://github.com/lukas-krecan/ShedLock#locking-without-a-framework). For scheduling you can use for example executor service `Executors.newScheduledThreadPool(20)`
