### ISSUE TITLE
Neo4j support

### ISSUE THREAD

**Issue by thimmwork** [lukas-krecan/ShedLock#728]
I'm working on a project that uses a Neo4j database, and I saw Shedlock does not support this yet.
So I took the time and implemented a provider.

PR is here:
https://github.com/lukas-krecan/ShedLock/pull/729

Tests were mostly copied from jdbc modules and merged into a single integration test class.

**Notes on the implementation:**
Neo4j uses read-committed isolation, which may lead to lost updates when not taken care of.
I used explicit node locking as described in [Neo4j's documentation about lost updates](https://neo4j.com/docs/java-reference/current/transaction-management/#transactions-isolation-lostupdates) to accommodate for this. FuzzTester tells me this is fine.

Please let me know what you think.

**Comment by lukas-krecan** [comment]
Released as 4.28.0. Could you please send PR with Readme update? Thanks again.
