### ISSUE TITLE
Decouple @Scheduled and @SchedulerLock

### ISSUE THREAD

**Issue by spartanhooah** [lukas-krecan/ShedLock#730]
**Is your feature request related to a problem? Please describe.**
We have two datacenters, each with their own Hazelcast grid. To ensure scheduled tasks do not have conflicts, we're locking them with ShedLock, and then checking to make sure we're in the "retry datacenter". The problem we've run into is that if a node in the wrong datacenter grabs the lock, we'll miss that iteration of the scheduled task (task is locked -> task is not running in the correct datacenter -> task does nothing). We tried having the scheduled task check which datacenter it's in, then call the method with the `@SchedulerLock` annotation, but it appears that having `@Scheduled` and `@SchedulerLock` on two different methods did not work as expected - we saw lots of locks being acquired.

**Describe the solution you'd like**
Being able to do something like the below would fulfill our need:
```
@Scheduled(cron = "0 */5 * * * *")
public void checkIfCanStartTask() {
    if (retryEnvironment.isRetryDatacenter()) {
        startTask()
    }
}

@SchedulerLock(name = "retryTask", lockAtLeastFor = "4m", lockAtMostFor = "5m")
public void startTask() {
    // do business logic here
}
```

**Describe alternatives you've considered**
Emulating a home-grown locking solution that another team devised. I don't understand it, myself, so I can't really explain it, unfortunately.

**Comment by lukas-krecan** [comment]
Hi, there already are decoupled. I suspect the trouble is that you are calling the methods in the same instance. ShedLock by default uses Spring AOP and it does not work when you call a method in the same instance (you can find the reason in Spring documentation). 

I do not understand what "we saw lots of locks being acquired" means.

**Comment by spartanhooah** [comment]
What do you mean by "instance"? I don't _think_ we're using Spring AOP, but Spring Boot can be deceptive sometimes.

"We saw lots of locks being acquired" means in logs in different nodes we saw the same lock get acquired during the `lockAtLeastFor` duration.

**Comment by lukas-krecan** [comment]
ShedLock is using AOP. Instance as a class instance.
