### ISSUE TITLE
Inconsistent behaviour for defaultLockAtMostFor

### ISSUE THREAD

**Issue by dadepo** [lukas-krecan/ShedLock#732]
**Describe the bug**
1. Which version do you use
    - 4.24.0
2. Which Lock Provider
    - JdbcTemplateLockProvider
3. ShedLock configuration
```
@Configuration
@EnableAspectJAutoProxy(proxyTargetClass = true)
@EnableScheduling
@EnableSchedulerLock(defaultLockAtMostFor="23h")
@ImportResource(value = "classpath:applicationContext-api.xml")
``` 
4. ShedLock logs
 - N/A

**Expected behavior**
The `lock_until` should contain a date that is 23hrs after the time a job kicks in. 

**Actual behavior**
The `lock_until` contain the moment after job finishes. This is the behaviour I see on the servers (linux). But running the same application on my local development environment (mac) the `lock_until` contains a date value that is 23hrs after the time a job kicks in - which is the value I expect.

What could be responsible for this different behaviour on the servers?

**Comment by lukas-krecan** [comment]
Hi, I think you will be able to answer this one youself. Try to find out, how does the unlock work.

**Comment by dadepo** [comment]
I think I should add, this change in behaviour showed up after upgrade from version `2.5.0` to `4.24.0`.

So the question is, has there been an undocumented change in the behaviour of the lock/unlock that can explains this? Nothing in the change log mentions this by the way.

**Comment by lukas-krecan** [comment]
Do you know how unlocking works?

**Comment by dadepo** [comment]
The documentation says:

> This is just a fallback, under normal circumstances the lock is released as soon the tasks finishes. 

I have a situation where this is currently not the case, and a situation where this changed after an upgrade.

**Comment by lukas-krecan** [comment]
In my opinion it's the difference between a task that finished successfully and a task which is currently running or where the node died (or was switched-off) in the middle of the task execution. If you think it's not the case, please provide more details why you think so.
