### ISSUE TITLE
node1 unlock may overwrite node2's lock's info in MongoLockProvider?

### ISSUE THREAD

**Issue by TNT-Boom** [lukas-krecan/ShedLock#74]
In mongoProvider, if node1 running a task gets a lock at 9:00, lockuntil's value is 9:30, but the task is blocked until 9:40.
At 9:30, another node2 running the shcedule task can get the lock by the following code and set lockuntil is 10:00:

` 
@Override
        public boolean updateRecord(LockConfiguration lockConfiguration) {
            Date now = now();
            Bson update = combine(
                set(LOCK_UNTIL, Date.from(lockConfiguration.getLockAtMostUntil())),
                set(LOCKED_AT, now),
                set(LOCKED_BY, hostname)
            );
            Document result = getCollection().findOneAndUpdate(
                and(eq(ID, lockConfiguration.getName()), lte(LOCK_UNTIL, now)),
                update
            );
            return result != null;
        }
`
When the times comes to 9:40, node1 unlocks lock and update LOCK_UNTIL to now(9:40)
`
@Override
        public void unlock(LockConfiguration lockConfiguration) {
            // Set lockUtil to now or lockAtLeastUntil whichever is later
            getCollection().findOneAndUpdate(
                eq(ID, lockConfiguration.getName()),
                combine(set(LOCK_UNTIL, Date.from(lockConfiguration.getUnlockTime())))
            );
        }
`
`
public Instant getUnlockTime() {
        Instant now = Instant.now();
        return lockAtLeastUntil.isAfter(now) ? lockAtLeastUntil : now;
    }
`
the node1 changes node2's lock info through unlock ? should add "lockedBy" check in unlock operation?

**Comment by TNT-Boom** [comment]
if the task duration is 5 minutes, the lockAtMostFor =30min is ok. but in some exceptions or other conditions, the task run 40 minutes unfortunately, the unlock operation will overwrite node2's LOCK_UNTIL.

Should add "lockedBy" check in unlock operation? Using this check to ensure that only unlock oneself lock.

**Comment by lukas-krecan** [comment]
"lockedBy" check would defeat the reason for lockAtMostFor existence so you just can set lockAtMostFor to some large value and you are done. Imagine that you execute the task in Kubernetes or some similar environment and the node running the task crashes. New one with different hostname is created which means that "lockedBy" check would always fail and the the lock would have been kept indefinitely.
