### ISSUE TITLE
Not executing task if create 'shedlock' table after the application was started

### ISSUE THREAD

**Issue by paranoiddemon** [lukas-krecan/ShedLock#753]
I am using the 4.28 version and JDBC template lock provider.

If I start the application first, then I create the table 'shedlock' in database. 
The lock will not work and keep saying "Not executing task. It's locked."  Shedlock will not insert the lock even the table is created later. Got to restart the instance to solve the problem.

It seems that the doLock() method in class StorageBasedLockProvider is doing caching in lockRecordRegistry even the insertRecord() not succeed.  
```
protected boolean doLock(LockConfiguration lockConfiguration) {
        String name = lockConfiguration.getName();
        if (!lockRecordRegistry.lockRecordRecentlyCreated(name)) {
            // create record in case it does not exist yet
            if (storageAccessor.insertRecord(lockConfiguration)) {
                lockRecordRegistry.addLockRecord(name);
                // we were able to create the record, we have the lock
                return true;
            }
            // we were not able to create the record, it already exists, let's put it to the cache so we do not try again
            lockRecordRegistry.addLockRecord(name);
        }

        // let's try to update the record, if successful, we have the lock
        return storageAccessor.updateRecord(lockConfiguration);
    }
```

**Comment by lukas-krecan** [comment]
hi, sorry for late response. This is strange, `storageAccessor.insertRecord` should return false if there is an exception. What DB engine are you using?

**Comment by paranoiddemon** [comment]
> hi, sorry for late response. This is strange, `storageAccessor.insertRecord` should return false if there is an exception. What DB engine are you using?

I am using Oracle 11g.

**Comment by basclaessen** [comment]
Even if `storageAccessor.insertRecord` is returning false, the lock is cached right after the `if`.
As a result of this the `storageAccessor.insertRecord` will never be called again during the lifetime of the JVM.
