### ISSUE TITLE
Possibility to add retry ability

### ISSUE THREAD

**Issue by frankiedrake** [lukas-krecan/ShedLock#776]
I cannot find a way to intercept a session creation / destruction in a `ConsulLockProvider` to make it retryable.
The problem is that sometimes the connection to consul is lost / reset and then sessions are hold until the `defaultLockAtMostFor` is reached. Reducing this time isn't convenient cause the method actually could take a lot time to execute.
I tried to extend this class to override the desired methods, but `destroy` method is private so that's impossible, by the same reason I'd not want to aspect them 
Would be nice to add an option to configure `RetryTemplate` or some boolean `retry` variable to let these methods be retryable.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. As I am not a Consul expert I did not get get part about RestTemplate, can you please elaborate? 

One possible way of solving the problem might be to extend the `ConsulClient` and do the retry there, what do you think?

**Comment by frankiedrake** [comment]
Sorry about `RestTemplate` , I meant `RetryTemplate`. 
I also tried to extend the `ConsulClient` but in configures automatically by `Spring` and simply exteding it calls the default constructor that sets all properties to default values (host: localhost, etc), which is not suitable for me. Interefrring in a Spring autoconfiguration process seems to be wrong. I'll try to play with it more and maybe I'll be able to do something. Thanks

**Comment by lukas-krecan** [comment]
As far as I know, overriding autoconfigured beans is expected and pretty common. But I do not know how easy it would be in case of Consul. If it's a problem, we can provide an abstraction that would be easier to override. So let me know if overriding the ConsulClient is not feasible.

**Comment by frankiedrake** [comment]
I've overriden the default `ConsulClient` `sessionCreate`/`sessionDestroy` methods, however constructor isn't very elegant, but it's seems working. Hope it will also work in production

**Comment by lukas-krecan** [comment]
@frankiedrake Hi, did it work?

**Comment by gclsoft** [comment]
This is too easy, just add `@Retryable(value = [Exception::class], maxAttempts = 3, backoff = Backoff(delay = 5400000L))` to the inner service, not the same position code with @SchedulerLock, in the inner service called by the schedule, I tested it ok.
 @lukas-krecan  @frankiedrake
