### ISSUE TITLE
AWS DynamoDB

### ISSUE THREAD

**Issue by peruzzo** [lukas-krecan/ShedLock#80]
Hi,

Do you have any plan to support for DynamoDB?

**Comment by lukas-krecan** [comment]
Hi, I do not plan it, but it should be quite easy to implement. Pull requests are welcomed.

**Comment by jrehwaldt** [comment]
Just as reference for others not watching the PR list like me: #108 and #112 are adding such provider once merged.

**Comment by lukas-krecan** [comment]
Released as 2.2.0
