### ISSUE TITLE
Simple lock for tests

### ISSUE THREAD

**Issue by kkocel** [lukas-krecan/ShedLock#805]
**Is your feature request related to a problem? Please describe.**
I would like to have a special lock that can be used in tests or for running single local instance

**Describe the solution you'd like**
I would like to have a simple in memory lock.

**Describe alternatives you've considered**
Using testcontainers with some DB can be an option but it takes more time for test to run. For simple tests I would like to have in memory solution.

**Comment by lukas-krecan** [comment]
Hi, you an try [this](https://github.com/lukas-krecan/ShedLock/blob/master/shedlock-core/src/test/java/net/javacrumbs/shedlock/core/ReentrantLockProvider.java).

**Comment by kkocel** [comment]
@lukas-krecan I thought to use In Memory implementation and movie it to core.

My use is that I want to use it with Spring profile "local" that's why it would be better to have it in main instead of tests.
