### ISSUE TITLE
Oracle support

### ISSUE THREAD

**Issue by TheAvalanche** [lukas-krecan/ShedLock#81]
Have tested with Oracle, here is Oracle SQL script in case someone needs it:

```
CREATE TABLE SHEDLOCK (
  name VARCHAR2(64 CHAR),
  lock_until TIMESTAMP,
  locked_at TIMESTAMP,
  locked_by  VARCHAR2(255 CHAR),
  PRIMARY KEY (name)
);
```

Thanks for you work!

**Comment by lukas-krecan** [comment]
Thanks, I will add it to readme

**Comment by PengIvanSun** [comment]
This might not be accurate. Grants privilege might also be needed in Oracle DB
