### ISSUE TITLE
Spring4 support

### ISSUE THREAD

**Issue by chence** [lukas-krecan/ShedLock#82]
Hi, I got an exception as follows:
java.lang.NoSuchMethodError:org.springframework.core.annotation.AnnotatedElementUtils.getMergedAnnotation

Spring version: 4.1.6.RELEASE. 
ShedLock version: 1.0.0, 1.1.0(in fact all version after 0.11.0 will throw this exception cause spring 4.1.6 really no such method)
LockProvider: jdbc / jedis / zookeeper

Could anyone resolve this?

Thanks.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. You are right, getMergedAnnotation is in Spring since 4.2. Unfortunately, I have no motivation to support obsolete versions of Spring so I can only recommend you to update.
