### ISSUE TITLE
Support for Hazelcast 5

### ISSUE THREAD

**Issue by holgerstolzenberg** [lukas-krecan/ShedLock#843]
**Is your feature request related to a problem? Please describe.**
At the moment I am integrating Hazelcast and SchedLock in a Spring Boot app.
Both frameworks are working perfectly together, I am now at the point of making Kubernetes Hazelcast discovery happen.
Hazelcast discovery moved from an external project (https://github.com/hazelcast/hazelcast-kubernetes) directly into Hazelcast recently.

**Describe the solution you'd like**
I'd really like to use/upgrade to Hazelcast 5 and cleanup dependencies, but still want to stick with ShedLock as it works and can be used really well. I could not find a dependency of schedlock to be used with Hazelcast 5. Maybe it as compatible with the 4 version of the ShedLock Provider, but docs do not tell about this.

**Describe alternatives you've considered**
Have not found any meaningful.

**Additional context**
None.

**Comment by holgerstolzenberg** [comment]
In the first place it would be very cool to have at least any information if Hazelcast 5 support is planned so that we can elaborate on our upgrade policy.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback, I just run the tests with Hazelcast 5 driver and they all passed. It's hard to name the modules as you never know beforehand which library will break backwards compatibility. I will update the docs

**Comment by holgerstolzenberg** [comment]
Thanks for the quick response. I already could verify on my own, that everything stills seems to work.
Still, it looks a bit weird to have Hazelcast 5 dependencies mixed up with your dependencies at version 4:

```groovy
// caching
implementation 'org.springframework.boot:spring-boot-starter-cache'
implementation "com.hazelcast:hazelcast:${hazelcastVersion}"
implementation "com.hazelcast:hazelcast-spring:${hazelcastVersion}" // being 5.0.2
implementation "net.javacrumbs.shedlock:shedlock-spring:${schedLockVersion}"
// looks like ShedLock provider for v4 is compatible with v5
// see https://github.com/lukas-krecan/ShedLock/issues/843
implementation "net.javacrumbs.shedlock:shedlock-provider-hazelcast4:${schedLockVersion}" // <- having the 4 in artifact name
```

Does it make sense to introduce a `shedlock-provider-hazelcast4` artifact?

**Comment by lukas-krecan** [comment]
This is an impossible task to solve. I do not want to introduce `shedlock-provider-hazelcast5` artifact that would be the same as `shedlock-provider-hazelcast4`, it would be in my opinion more confusing. Besides, other lock providers that do not break backwards compatibility have just one variant.

Let's pretend that the `4` in the name is a base version - the minimal version the provider works with.

**Comment by holgerstolzenberg** [comment]
Alright agreed. Maybe it is a good idea to update the docs a bit upon this conclusion.
