### ISSUE TITLE
Advice on extending spring

### ISSUE THREAD

**Issue by chenlingmin** [lukas-krecan/ShedLock#85]
Hi.
I've been following the project for a long time, Very good.

Are you going to do that? like this
[spring-boot-klock-starter](https://github.com/kekingcn/spring-boot-klock-starter)

```
@Lock(keys = "#user.id") // Spring spel expression
public saveUser(User user) {
     // any
}
```

**Comment by lukas-krecan** [comment]
Sorry, I do not understand

**Comment by chenlingmin** [comment]
Some time, We need to add distributed locks to the business methods. And a good way is to annotate the business method. Just like your annotation `@SchedulerLock`.

but annotation value is static. Spring spel is a good choice if we want to achieve dynamic effects. 

like this, If I want to dynamically lock the user id
```
@Lock(keys = "#user.id") // Spring spel expression
public saveUser(User user) {
     // any
}
```

The project linked above does this, but it doesn't scale well enough to be as elegant and scalable as your project.

**Comment by lukas-krecan** [comment]
Currently it is not supported but you can easily implement it yourself by using Spring AOP together with https://github.com/lukas-krecan/ShedLock#running-without-spring
