### ISSUE TITLE
Shedlock Support for Spring Cloud Function @PollableBean

### ISSUE THREAD

**Issue by Mahm0ud** [lukas-krecan/ShedLock#866]
**Is your feature request related to a problem? Please describe.**
The Spring cloud function was released while ago, and with it, many code bases are shifting to a more functional-style methods, this entailed some changes to the normal scheduled job, for example, a normal `Scheduled` job that emits elements to a Kafka topic for example would look like this
```
@Scheduled(cron=..)
public void runScheduledJob(){ 
    boolean result = subscribableChannel.send("hello world");
    log.info("The message sending operation result was: "+result);
}
```

Now, using Spring cloud function, a bean with return type Supplier and annotated as `@Pollable` can replace this function as follows:
```
@PolllableBean
public Supplier<String> getScheduledJob(){ 
    return () -> return "hello world";
}
```

Please note that the cron for this can be configured within the application.properties file using `spring.cloud.stream.poller.cron=0 0/10 * * * *
`
The issue here as probably notices is that Shedlock annotation would not work here, and although you are free to add it, however it would not only be useless, but shall in case of there is a lock on the method prevent the bean for being registered (I have already tried that https://stackoverflow.com/questions/70623688/an-error-creating-bean-with-name-functionbindingregistrar-exception-every-ti/70671570#70671570 and asked if there is a solution [here](https://stackoverflow.com/questions/70684735/shedlock-with-spring-cloud-function-pollablebean)) 

**Describe the solution you'd like**
It would always be easy to say: Could you please add support for Spring Cloud function suppliers? I don't have any solution that I can think of

**Describe alternatives you've considered**
The only way around is to revert back to the good old normal method and dump spring cloud function Supplier implementation all together 

**Additional context**
None

**Comment by lukas-krecan** [comment]
Hi, this is really interesting. I see two ways of solving this. 

1. The most straigntforward is to use AOP on another method

```java
@PolllableBean
public Supplier<Void> getScheduledJob(){ 
    return otherBean::doIt;
}

class OtherBean {
  @SchedulerLock(...)
  public void doIt() {
    ....
  }
}
```
please note that the method is implemented on different class to allow AOP to work. Also I had to change the return type to `Void` as we would not know what to return in case the lock is locked.

2. The other option is to use [locking without framework](https://github.com/lukas-krecan/ShedLock#locking-without-a-framework)

**Comment by Mahm0ud** [comment]
Thanks for you quick turn around Lukas, I have tried the first approach, however, it seems that the lock is not activated, please find a running sample of the code here https://github.com/Mahm0ud/ShedlockWithSpringCloudFunction.

**Comment by lukas-krecan** [comment]
By default ShedLock is using Spring AOP. In order for it to work, the ShedulerLock annotation has to be on a bean (a class instantiated by Spring). Your ScheduledTask class is not a bean.
