### ISSUE TITLE
shedlock-provider-jdbc and autocommit

### ISSUE THREAD

**Issue by blaluc** [lukas-krecan/ShedLock#867]
In the executeCommand method of JdbcStorageAccessor class (shedlock-provider-jdbc module), the connection is forced to autocommit before applying the statement without restoring its previous value any after, and this could be indesiderable, specially if the connection is released to a pool and then consumed by other threads.
Perhaps the correct behaviour would be to save the previous autocommit value of the connection and restore it in a finally block.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Is this a theoretical concern or does it causes you any issues?

**Comment by blaluc** [comment]
Hi Lukas, actually I have an application relying on a connection pool with autocommit set to false. So, after the JdbcStorageAccessor calls the executeCommand it releases the connection to the pool with a non-default (for the pool) state and it causes problems on subsequent calls that, expecting a non autocommit connection, try to manage the boundaries of the transaction.

**Comment by lukas-krecan** [comment]
Released as 4.32.0
