### ISSUE TITLE
spring cloud 

### ISSUE THREAD

**Issue by siaron** [lukas-krecan/ShedLock#87]
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 2 of method bindingService in org.springframework.cloud.stream.config.BindingServiceConfiguration required a single bean, but 2 were found:
	- defaultSockJsTaskScheduler: defined by method 'defaultSockJsTaskScheduler' in class path resource [org/springframework/web/socket/config/annotation/DelegatingWebSocketConfiguration.class]
	- messageBrokerTaskScheduler: defined by method 'messageBrokerTaskScheduler' in class path resource [org/springframework/web/socket/config/annotation/DelegatingWebSocketMessageBrokerConfiguration.class]

**Comment by lukas-krecan** [comment]
I do not see how this is connected to ShedLock but it seems you have multiple task schedulers in the project a Spring does not know which one to use. In such case you have to wire them by hand

**Comment by siaron** [comment]
sorry ,when 
    @Bean
    public BindingService bindingService(BindingServiceProperties bindingServiceProperties,
                                         BinderFactory binderFactory, TaskScheduler taskScheduler) {
        return new BindingService(bindingServiceProperties, binderFactory, taskScheduler);
    }

spring cloud stream only one taskScheduler bean , you example 

@Bean
public ScheduledLockConfiguration taskScheduler(LockProvider lockProvider) {
    return ScheduledLockConfigurationBuilder
        .withLockProvider(lockProvider)
        .withPoolSize(10)
        .withDefaultLockAtMostFor(Duration.ofMinutes(10))
        .build();
}

Will prompt 

Parameter 2 of method bindingService in org.springframework.cloud.stream.config.BindingServiceConfiguration required a single bean, but 2 were found:

Just change taskScheduler the name.

Can close this issue
