### ISSUE TITLE
Question: How does ShedLock manage / help with FixedRate or FixedDelay type Scheduled tasks?

### ISSUE THREAD

**Issue by rpsandiford** [lukas-krecan/ShedLock#870]
I can clearly see how ShedLock helps with multi-node handling for a cron type schedule.

However - if I have a FixedRate or FixedDelay type schedule, how does ShedLock manage that?

e.g. suppose I have 2 nodes, and each has the same task set up with:
`  @Scheduled(fixedDelay = 60000)`
meaning I want to run the task, and when it completes, I want to run it again 60 seconds later (i.e. 60 seconds between end of one task execution and start of next task execution).

And suppose I also have the ShedLock annotation like this:
`  @SchedulerLock(name = "FixedDelayTask", lockAtLeastFor = "10s", lockAtMostFor = "30s"`

(I'm not set on those timings - this is just an example)

Node 1 fires at (say) 1:00:00 and is able to insert / update the shedlock row, and execute the task.  It completes at (say) 1:00:05, and releases the lock.  I don't want the task to start up again until 1:01:05.

Node 2 fires the task at (say) 1:00:20 (because there's no synchronization between nodes, there's no way node 2 'knows' that it shouldn't fire until 1:01:05.  Node 2 tries to get the lock and succeeds, and executes the task.  Too soon.

Node 1 fires at 1:01:05 and gets the lock - so the task keeps executing twice per minute-ish, rather than just once.

Am I missing something that would help with this situation?   (I would have the same question about fixedRate tasks...)

Thanks!

Bob.

**Comment by lukas-krecan** [comment]
Hi, that's exatly what `lockAtLeastFor` is for.

**Comment by rpsandiford** [comment]
OK - I can see that for the fixed rate case.   However - for the fixedDelay case - once you have the lock, can you update the lock_until value (e.g. for the fixedDelay - update the lock_until at the end of the task.  In the example - node 1 would update the lock_until to be 1:01:05?

**Comment by lukas-krecan** [comment]
You can simply set `lockAtLeastFor` to 59s, can't you?

**Comment by rpsandiford** [comment]
Yes - which will be a guesstimate for a fixedDelay type setup...

**Comment by rpsandiford** [comment]
Understood.  However - fixedDelay means run the task again at a fixed delay AFTER THE PREVIOUS INSTANCE HAS COMPLETED.  So - a fixedDelay of 60 seconds doesn't mean run it every 60 seconds - it means run it again 60 seconds after completion of the previous run.  Setting it for 59 seconds in essence converts a 'fixedDelay' to a 'fixedRate'.

**Comment by lukas-krecan** [comment]
I see.

**Comment by niezuxue** [comment]
> I see.

So what should we do for the issue

**Comment by lukas-krecan** [comment]
Use a task scheduler like db-scheduler or JobRunr
