### ISSUE TITLE
Do not check lock if @SchedulerLock method called

### ISSUE THREAD

**Issue by bnjdpn** [lukas-krecan/ShedLock#876]
I have a method annoyed with @Scheduled and @SchedulerLock that I can call from an other Spring bean (like a @Service).

But when I call it from my service it don’t call my method with @Scheduled since there is already a lock…

Is there any way to bypass the lock except creating a new method without @SchedulerLock ?

**Comment by lukas-krecan** [comment]
Hi, I am sorry to hear that ShedLock annoyed your method 😸 . I would recommend to create a new method, it feels like a cleaner design than any other way that comes to my mind.
