### ISSUE TITLE
Quartz Job not supported

### ISSUE THREAD

**Issue by khwajamoiz01** [lukas-krecan/ShedLock#89]
If my job is not using Springs sheduled and insted using Quartz job beans then it is not working.

**Comment by lukas-krecan** [comment]
Frankly, I am glad to hear that. If you are using Quartz, you do not need ShedLock at all since Quartz is able to prevent multiple task executions by itself.

**Comment by khwajamoiz01** [comment]
Do you mean by using quartz clustering feature?
Actually I want to go for clustering for my scheduled jobs application where some are in quartz and some using spring 'scheduled'.

**Comment by lukas-krecan** [comment]
I am working on AOP support which should enable Quartz integration

**Comment by lukas-krecan** [comment]
You can try this https://github.com/lukas-krecan/ShedLock#scheduled-method-proxy. If you do, please let me know if it helped
