### ISSUE TITLE
Increase lock_until value when Spring scheduled task takes longer to finish

### ISSUE THREAD

**Issue by indrekots** [lukas-krecan/ShedLock#9]
Is is possible to increase the `lock_until` value while the task is still running?

I could set the `lockAtMostFor` to some large value. This (mostly) ensures that the scheduled task is able to finish before the lock is released again. But I'm worried about what will happen if the node running this task is killed. Then other nodes in the cluster would have to wait until the large `lockAtMostFor` value times out.

**Comment by akhil6095** [comment]
Yes, you're right if the node is down then other node will have to wait for specified amount of time which may cause unexpected results if the list of scheduled jobs is big

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Can you please describe what your use-case is? How often do you execute the task, how long does it usually take to execute the task?

**Comment by akhil6095** [comment]
My use case is to run a scheduler which will pick some data (from DB) and then push it to kafka topics, but the frequency of db operation is high and the application can be deployed in cluster, the nature of jobs is such that they have to executed once and only once, I guess that can be achieved by lockAtMostFor  but that has other implications like one we discussed above i.e. what if a node dies

**Comment by lukas-krecan-lt** [comment]
I am afraid that ShedLock is not fit for such use-case, it would be better to use a distributed scheduler.

**Comment by akhil6095** [comment]
Yeah, that is what I was thinking, because having distributed scheduler backed with MySql (to maintain ACID) will make sure that a task is executed once and only once, anyways great work simple to use and configure, keep up the good work  :+1:

**Comment by vaibhavdeshmukh17** [comment]
Hello Every one ,
am having long Schedule Task and frequency is after every one minute, we have distributed environment where 3 instances running. what happening is because of smaller value specified in lockAtLeastFor (45Sec) the execution is happening in all 3 instances as lock is released in 45Sec. how can we set dynamic value to lock_untill to total execution time of Task ??
