### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by ivanwolkow** [lukas-krecan/ShedLock#91]
Hi,
first of all, thank you for developing such a handy and minimalistic locking tool which i'm pretty fascinated of :)

Here is the problem: I recently noticed an unexpected behavior when using ShedLock on several machines each running in a different timezone. Simply put, the values of "lock_until" and "locked_at" are stored as a timestamp without timezone, meaning that the value actually written/read to the database will differ depending on the local timezone offset. Because of that it doesn't make sense to use the ShedLock within a multiple timezone environment.
Please confirm I am not missing anything and that my conclusions are correct, and if that is so, are you planning on fixing it somehow or implementing an additional functionality for that purpose in the near future?

Thanks.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Timestamp handling in JDBC is quite a mess https://blog.jooq.org/tag/timestamp-with-time-zone/ I am afraid that there is no universal way to solve it but I may provide some extension point that would enable you to override the default behavior. In the meantime you can create your own LockProvider, it just few lines of code. It would help me if you could send me your solution so I know how to design the extension point.

5. 10. 2018 16:37, 16:37, android2308 <notifications@github.com> napsal/a:

**Comment by android2308** [comment]
I created a custom LockProvider which uses my implementation of AbstractStorageAccessor. That implementation is nothing but a clone of JdbcTemplateStorageAccessor with all calls of `setTimestamp(int parameterIndex, java.sql.Timestamp x)` replaced to `setTimestamp(int parameterIndex, java.sql.Timestamp x, Calendar cal)` where cal is an instance of Calendar with timezone `TimeZone.getTimeZone("UTC"))` . This should make the JDBC save timestamps always in UTC time zone no matter the local time zone.

**Comment by lukas-krecan** [comment]
is this something that would help you https://github.com/lukas-krecan/ShedLock/commit/756cfe170ccbbbbc3a9ba98a151fab100c73963a#diff-4634d90dfb5ea05cf7defbe7f2363dbfR31 ?

**Comment by lukas-krecan** [comment]
Released as 1.3.0
