### ISSUE TITLE
Sponsoring

### ISSUE THREAD

**Issue by waschmittel** [lukas-krecan/ShedLock#918]
Hello from https://github.com/dm-drogeriemarkt @lukas-krecan 

We've been using this project for about 2 years now and are very happy with it - so are considering sponsoring it.
Since there is no Github Sponsors set up for this project, please contact me if you are interested. 

Our only requirement for sponsoring would be a badge or something with similar visibility in the Readme.
(Because missing attribution would make it a donation instead of sponsoring, we cannot do this without attribution due to tax reasons)

Greetings from Karlsruhe

**Comment by lukas-krecan** [comment]
Wow, thanks. I have to check how is it taxed first, but it's a pleasant surprise.

**Comment by lukas-krecan** [comment]
Hi, I have decided I am not going into the Sponsorship. It would really complicated my taxes. See this [analysis](https://twitter.com/rafaelcodes/status/1365795326418948097). And besides, I am contributing to OS for fun and fame, not profit 😸 . So thanks again, I really appreciate it and I am really glad that the project is useful for you. But it would make me happier if you send the donation to another project or to a non-profit of your choice.

**Comment by waschmittel** [comment]
Thanks for the quick decision, then. I appreciate the sentiment of fun and fame. 🙃 So we'll contribute in a non-monetary way when possible.

Just so you know: We didn't want to use Github Sponsors specifically - I just mentioned it as an example because there wasn't any statement about sponsoring regarding this project.
