### ISSUE TITLE
Change access modifier of `wrap` method in `LockableTaskScheduler`

### ISSUE THREAD

**Issue by petromir** [lukas-krecan/ShedLock#960]
I'm developing a multi-tenancy application that connects to different database servers. When configuring the lock provider our Datasource already supports multi-tenancy
```java
@Bean
public LockProvider scheduledJobLockProvider(final DataSource dataSource) {
return new JdbcTemplateLockProvider(JdbcTemplateLockProvider.Configuration
		.builder()
                // The datasource is multi-tenant
		.withJdbcTemplate(new JdbcTemplate(dataSource))
		.withTableName("scheduled_tasks")
		.usingDbTime()
		.build());
}
```
but in order to work, we need to set the tenant in each `Runnable` of `TaskScheduler` using `ThreadTenantContext.set("TENANT_1")` before actual lock.
As I see the only way to achieve this is to wrap `LockableRunnable` by extending `LockableTaskScheduler`

**Describe the solution you'd like**
Please change the access modifier of `wrap` method in `LockableTaskScheduler` from private to protected.

**Describe alternatives you've considered**
Create my own implementation of `TaskScheduler` similar to `LockableTaskScheduler`

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Isn't it possible to do the same by wrapping the `LockProvider` and set the thread local there?
