### ISSUE TITLE
Dynamic load runnable tasks runing by ThreadPoolTaskScheduler. No lock configuration for task.

### ISSUE THREAD

**Issue by lixplor** [lukas-krecan/ShedLock#979]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

Update to the latest version.

**Describe the bug**
1. Which version do you use: 4.33.0
2. Which Lock Provider: Jedis
3. ShedLock configuration: That's what i'm looking for
4. ShedLock logs:
```
SpringLockConfigurationExtractor:getLockConfiguration:67 - Unknown task type xxxx
DefaultLockManager.executeWithLock:49 - No lock configuration for xxx. Executing without lock.
```

**Expected behavior**
I'm using a `ThreadPoolTaskScheduler` to load task information from MySQL. Creating task beans which implementing `Runnable`. Then call `threadPoolTaskScheduler.scheduleAtFixedRate(task, initialDelay, interval)` to start all tasks

My expectation is to run multiple application nodes at same time and use Shedlock to avoid duplicate tasks running from every node.

After reading doc I thought [TaskSchedulere Proxy](https://github.com/lukas-krecan/ShedLock/blob/master/README.md#taskscheduler-proxy) mode may be suitable for my use case? I added `@EnabledSchedulerLock(interceptMode = PROXY_SCHEDULER, ...)`, and set JedisConnectionFactory.

But when I check debug log, Shedlock shows `Unknown task xxx` and `No lock configuration for xxx`. I read source code it shows DefaultLockManager's getLockConfiguration only deal with `ScheduledMethodRunnable`?

In my case, how should I made my runnable to be proxied as a `ScheduledMethodRunnable`? Or is there any mistake I make it wrong?

**Actual behavior**
Multiple appplication nodes run fixed rate scheduler tasks with Shedlock.

Thanks

**Comment by lukas-krecan** [comment]
Hi, it seems you are trying to implement your own scheduler. Please use an existing one, I can recommend [db-scheduler](https://github.com/kagkarlsson/db-scheduler).

If you insist on implemnting your own, I would recommend on [using locking without framework approach](https://github.com/lukas-krecan/ShedLock#locking-without-a-framework).
