### ISSUE TITLE
Delete locks in database

### ISSUE THREAD

**Issue by agent0** [lukas-krecan/ShedLock#982]
We have an application that processes incoming files and we are using the LockingTaskExecutor to prevent files from being processed on mutliple nodes. The name of the lock is the filename being processed and since this filename contains a timestamp, a new lock is created for each file. This leads to a large number of locks in the database as these locks are never deleted.

I would like to a have a method  to delete these logs safely from the database. Obviously I can delete old locks manually, but since this discouraged in the documentation I was looking for a better solution.

**Comment by lukas-krecan** [comment]
Hi, feel free to delete the locks rows in the database, if you are sure you will never need them again (after a day/week). If you want to be super-sure, you can call `clearCache()` on the lock provider right after the clean-up.

**Comment by agent0** [comment]
Ok, thank you for your reply.
